(ns whitakers-clj.dict-f)

(def dict-f
  {"faba" "bean"
   "fabae" "bean"
   "fabārum" "of beans"
   "fabās" "beans"
   "faba, fabae" "bean"

   "faber" "craftsman, smith"
   "fabrōrum" "of smiths"
   "faber, fabrī" "craftsman, smith"
   
   "fābula" "story"
   "fābulam" "story"
   "fābulīs" "stories, play, talk"
   "fābula, fābulae" "story"
   
   "faciē" "shape, figure, appearance, look"
   "faciēbus" "shapes, figures, appearances"
   "faciēs" "shape, figure, appearance, look"
   "faciem" "shape, figure, appearance, look"
   "faciēs, faciēī" "shape, figure, appearance, look"
   

   "faciēbant" "they were doing, they were making"   
   "faciam" "I will make, I (might) make"
   "faciat" "he (might) do/make"
   "faciātis" "you (might) be making"
   "faciēbam" "I was doing"
   "faciēbat" "he was doing"
   "faciet" "it will make"
   "faciendum" "making, doing"
   "faciendī" "of making, doing"
   "facere" "to make, to do"
   "faceret" "he did"
   "facerent" "they did"
   "faciāmus" "we (might) do, make"
   "faciunt" "they are making, they are doing"
   "fēcēre" "they did, made"
   "faciō, facere, fēcī, factus" "to do, to make"
   "facis" "you do, you make"
   "facit" "he makes"
   "facite" "make! do!"
   "facta" "having been made"
   "factae" "having been made"
   "factī" "having been made, done"
   "factō" "made"
   "factūrōs" "to be made"
   "factum" "having been made"
   "factus" "made"
   "fīēbat" "it was being made"
   "faciundī" "to be made"
   "fēcisset" "he (might) have had made"
   "faciendae" "doing, making"
   "fac" "do! make!"
   "fēcerant" "they had made, done"
   "factūrī" "having been done"
   "factūrum" "doing"
   "fierent" "it might be happening"
   "faciēmus" "we will make"

   "facile" "easy"
   "facilius" "easier"
   "facilis, facile, facilior -or -us, facillimus -a -um" "easy"

   "facinus" "crime, outrage"
   "facinoris" "crime, outrage"
   "facinus, facinoris" "crime, outrage"

   "factūra" "making, manufacture, creation"
   "factūra, factūrae" "making, manufacture, creation"

   "facultās"  "means, ability"
   "facultāte" "means, ability"
   "facultās, facultātis" "means, ability"

   "fallāx" "deceitful, misleading"
   "fallācia" "deceitful, misleading"
   "fallācibus" "deceitful, misleading"
   "fallācium" "deceitful, misleading"
   "fallāx, fallācis (gen.), fallācior -or -us, fallācissimus -a -um" "deceitful, misleading"

   "fallam" "I will deceive"
   "fallere" "to deceive"
   "fallō, fallere, fefellī, falsus" "to deceive"

   "falsa" "untruths, deceits, lies"
   "falsum" "untruth, deceit, lie"
   "falsum, falsī" "untruth, deceit, lie"

   "fāma" "fame, rumor"
   "famulentus" "rumor, reputation"
   "fāma, fāmae" "fame, rumor"
   
   "familia" "family"
   "familia, familiās" "family"
   "familiae" "family"
   "familiam" "family"

   "familiāris" "servant, familiar friend"
   "familiāris, familiāris" "servant, familiar friend"

   "famem" "hunger"
   "famēs" "hunger"
   "famēs, famis" "hunger"
   "famē" "hunger"

   "fāmōsum" "famed"
   "fāmōsus, fāmōsa, fāmōsum" "famed"

   "famulātum" "obedience, servitude"
   "famulātus" "obedience, servitude"
   "famulātus, famulātūs" "obedience, servitude"
   
   "famulī" "servant, companion"
   "famulō" "servant, companion"
   "famulīs" "servants, companions"
   "famulōrum" "of servants, of companions"
   "famulōs" "servants, companions"
   "famulus, famulī" "servant, companion"

   "fānum" "temple"
   "fānī" "temple"
   "fānum, fānī" "temple"

   "farīna" "flour, meal, ground corn"
   "farīnam" "flour, meal, ground corn"
   "farīna, farīnae" "flour, meal, ground corn"
   
   "fasciculum" "small bundle"
   "fasciculus, fasciculī" "small bundle"
   
   "fateor" "I admit"
   "fateor, fatērī, fassus sum" "to admit, to confess (deponent)"

   "fatīgābat" "it was wearying"
   "fatīgātī" "having been wearied, fatigued"
   "fatīgāre" "to grow weary, to fatigue"
   "fatīgō, fatīgāre, fatīgāvī, fatīgātus" "to grow weary, to fatigue"

   "fāta" "fates"
   "fātum" "fate"
   "fātum, fātī" "fate"

   "favente" "favoring"
   "favēre" "to favor"
   "faveō, favēre, fāvī, fautus" "to favor"
   
   "favilla" "ember"
   "favilla, favillae" "ember"

   "facient" "they will do, they will make"
   "fēcerit" "he will have made"
   "fēcērunt" "they did, they made"
   "fēcī" "I did, I made"
   "fēcimus" "we made"
   "fēcit" "he did"
   "fēcisse" "to have made"
   "fēcissent" "they (might) have had done"
   "fēcistis" "you made"
   "fēcerat" "he had done"

   "fēlīcitās" "happiness, fruitfulness"
   "fēlīcitātis" "happiness, fruitfulness"
   "fēlīcitās, fēlīcitātis" "happiness, fruitfulness"

   "felicēs" "happy"
   "fēlīcī" "happy"
   "fēlīx"  "happy"
   "fēlīx, fēlīcis (gen.), fēlīcior -or -us, fēlīcissimus -a -um" "happy"

   "fēmina"  "woman, wife"
   "fēminae" "woman, wife"
   "fēminam" "woman, wife"
   "fēminārum" "of women, wives"
   "fēminās" "woman, wives"
   "fēminīs" "women, wives"
   "fēmina, fēminae" "woman, wife"
   
   "fenestra" "window"
   "fenestram" "window"
   "fenestrās" "windows"
   "fenestrīs" "windows"
   "fenestra, fenestrae" "window"

   "fēnō" "hay"
   "fēnum, fēnī" "hay"

   "fera" "wild, savage"
   "ferae" "wild, savage"
   "ferus, fera, ferum" "wild, savage"

   "fēria" "festival, holiday"
   "fēria, fēriae" "festival, holiday"
   
   "tulērunt" "they brought"
   "tulissent" "they (might) have had brought"
   "tulit" "he brought"
   "ferret" "he was bringing"
   "ferre" "to bring, to bear"
   "ferō, ferre, tulī, lātus" "to bring, to bear"
   "ferēbātur" "it was brought"
   "ferēbāntur" "they were brought"
   "fertur" "it is brought"
   "ferēns" "bringing, bearing"
   "ferentēs" "bringing, bearing"
   "ferēbant" "they were bringing, bearing"
   "fer" "bring!"
   "ferimus" "we bring, carry"
   "fers" "you bring, carry"
   "fert" "he brings, carries"
   "fertis" "you bring, carry"

   "feriēbant" "they were hitting, striking, killing"
   "ferientem" "hitting, striking, killing"
   "ferīre" "to hit, strike, kill"
   "feriō, ferīre, -, -" "to hit, strike, kill"

   "feritās" "wildness"
   "feritās, feritātis" "wildness"

   "ferōcem" "wild, bold, defiant"
   "ferōcēs" "wild, bold, defiant"
   "ferōcī" "wild, bold, defiant"
   "ferōcis" "wild, bold, defiant"
   "ferōciter" "ferociously, wildly, defiantly"
   "ferōx" "wild, bold, defiant"
   "ferōx, (gen.), ferōcis" "wild, bold, defiant"
   
   "ferrāmentīs" "iron tools"
   "ferrāmentum, ferrāmentī" "iron tool"

   "ferrī" "iron"
   "ferrō" "iron"
   "ferrum" "iron"
   "ferrum, ferrī" "iron"
   
   "ferreae" "made of iron"
   "ferream" "made of iron"
   "ferreās" "made of iron"
   "ferreīs" "made of iron"
   "ferreōs" "made of iron"
   "ferreum" "made of iron"
   "ferreus" "made of iron"
   "ferreus, ferrea, ferreum" "made of iron"
   
   "fertilitāte" "fruitfulness, fertility"
   "fertilitās, fertilitātis" "fruitfulness, fertility"
   "fervēre" "to boil"
   "ferveō, fervēre, ferbuī, -" "to boil"

   "fervor" "boiling heat"
   "fervōre" "boiling heat"
   "fervōris" "boiling heat"
   "fervor, fervōris" "boiling heat"

   "fessa" "tired"
   "fessus, fessa, fessum" "tired"

   "festīnātiōne" "haste"
   "festīnātiō, festīnātiōnis" "haste"
   
   "fēstī" "festive"
   "festīnābant" "they were hastening"
   "festīnantēs" "hastening"
   "festīnāre" "to hasten, to hurry"
   "festīnāvit" "he hastened, he hurried"
   "festīnāvissent" "they (might) have had hastened"
   "festīnent" "they might hasten"

   "festīnus" "swift, fast, hastening"
   "festīnus, festīna, festīnum" "swift, fast, hastening"
   
   "festīnō, festīnāre, festīnāvī, festīnātus" "to hasten, to hurry"
   "fēstīvitāte" "festivity"
   "fēstīvitātem" "festivity"
   "fēstīvitās, fēstīvitātis" "festivity"
   "fēstīvitātibus" "festivity"
   
   "fēstīs" "festive"
   "fēsta" "festivals"
   "fēstam" "festival"
   "fēstō"  "festival"
   "fēstum" "festival"
   "fēstum, fēstī" "festival"

   "fēstōs" "festive"
   "fēstus, fēsta, fēstum" "festive"

   "fētentia" "stinking, smelling bad"
   "fēteō, fētēre, -, -" "to stink, smell bad"
   
   "fētor" "stench, foulness"
   "fetōribus" "stenches, foulness"
   "fētor, fētōris" "stench, foulness"
   
   "fīat" "may it be"
   "fībulās" "brace, brooch, clasp"
   "fībula, fībulae" "brace, brooch, clasp"

   "fīcī" "fig trees"
   "fīcus,  fīcī" "fig tree"

   "fidēlēs" "faithful persons, confidants"
   "fidēlibus" "faithful persons, confidants"
   "fidēlis" "faithful person, confidant"
   "fidēlis, fidēlis" "faithful person, confidant"

   "fidēlissimum" "most faithful"
   "fidēlis, fidēle, fidēlior -or -us, fidēlissimus -a -um" "faithful"

   "fidēlitās" "faithfulness, fidelity"
   "fidēlitāte"  "faithfulness, fidelity"
   "fidēlitātem" "faithfulness, fidelity"
   "fidēlitās, fidēlitātis" "faithfulness, fidelity"

   "fidem" "faith"
   "fidēs" "faith"
   "fideī" "faith"
   "fidē" "faith"
   "fidēs, fideī" "faith"

   "fīdūcia" "trust, confidence, courage"
   "fīdūciam" "trust, confidence, courage"
   "fīdūcia, fīdūciae" "trust, confidence, courage"
   
   "fīgite" "fasten! fix!"
   "fīxam" "having been fixed, having been fastened"
   "fīxērunt" "they set up, they fixed"
   "fīximus" "we fixed"
   "fīxit" "he fastened"
   "fīgō, fīgere, fīxī, fīxus" "to fasten, to fix"

   "figūra" "shape, form, figure"
   "figūra, figūrae" "shape, form, figure"
   
   "fīlī" "son"
   "fīliolī"  "young sons"
   "fīliolō"  "young son"
   "fīliolum" "young son"
   "fīliolus" "young son"
   "fīliolus, fīliolī" "young son"

   "fīlia" "daughter"
   "fīliābus" "daughters"
   "fīliae" "daughters"
   "fīliam" "daughter"
   "fīliās" "daughters"
   "fīlia, fīliae" "daughter"
   
   "fīliī" "sons"
   "fīliīs" "sons"
   "fīliō" "son"
   "fīliōs" "sons"
   "fīlium" "son"
   "fīlius" "son"
   "fīlius, fīlī" "son"

   "ficta" "having been molded, having been created"
   "fingēns" "molding, forming, creating"
   "fingentēs" "feigning, deceiving"
   "fingunt" "they mold, form, create"
   "fingentum" "having been molded, created"
   "fīnxērunt" "they molded, created"
   "fīnxit" "he feigned"
   "fingō, fingere, fīnxī, fictus" "to mold, to form, to create"
   
   "fīniēbat" "they were limiting, they were finishing"
   "fīniantur" "he might be finishing"
   "fīnītur" "it is finished, it is limited"
   "fīnīvit" "he finished, he limited"
   "fīnīre" "to limit, to finish"
   "fīniō, fīnīre, fīnīvī, fīnītus" "to limit, to finish"

   "fīne" "boundary, end, limit"
   "fīnem" "boundary, end, limit"
   "fīnēs" "boundaries, ends, limits"
   "fīnibus" "boundaries, ends, limits"
   "fīnis" "boundary, end, limit"
   "fīnium" "boundary, end, limit"
   "fīnis, fīnis" "boundary, end, limit"

   "fīnitimī" "neighbors"
   "fīnitimōs" "neighbors"
   "fīnitimus, fīnitimī" "neighbor"
   
   "fīnitimīs" "neighboring"
   "fīnitimus, fīnitima, fīnitimum" "neighboring"
   
   ;;   "fīnītus, fīnīta, fīnītum"
   "fit" "it happened, it occurred"
   "fīēbant" "they were done"
   "fieret" "it happened"
   "fierī" "to happen, to occur"
   "fīō, fierī, factus sum" "to happen, to occur"
   
   "firmāmentī" "strengthening, support"
   "firmāmentum, firmāmentī" "strengthening, support"

   "fīrmat" "he confirms, hardens"
   "fīrmāta" "having been hardened, confirmed"
   "fīrmātum" "having been hardened, confirmed"
   "fīrmāre" "to harden, confirm"
   "fīrmō, fīrmāre, fīrmāvī, fīrmātus" "to harden, confirm"

   "fīrma" "firm"
   "fīrmī" "firm"
   "fīrmissimōs" "very firm"
   "fīrmus, fīrma -um, fīrmior -or -us, fīrmissimus -a -um" "firm"

   "flagellāvit" "he whipped"
   "flagellō, flagellāre, flagellāvī, flagellātus" "to whip"

   "flāgitābant" "they were demanding, requiring"
   "flāgitō, flāgitāre, flāgitāvī, flāgitātus" "to demand urgently, require"

   "flagrābat" "he was burning"
   "flagrāns" "burning"
   "flagrō, flagrāre, flagrāvī, flagrātus" "to blaze, to burn"
   
   "flammās" "flames"
   "flammīs" "flames"
   "flamma, flammae" "flame"
   
   "flābat" "he was blowing, he was breathing"
   "flat" "it blows"
   "flāre" "to breathe, to blow"
   "flō, flāre, flāvī, flātus" "to breathe, to blow"

   "flātiō" "blowing"
   "flātiō, flātiōnēs" "blowing"

   "flandrēnsem" "Flemish; from Flanders"
   "flandrensī" "Flemish; from Flanders"
   "flandrensis" "Flemish; from Flanders"

   "flātū" "blowing, breathing, haughtiness"
   "flātus" "blowing, breathing, haughtiness"
   "flātus, flātūs" "blowing, breathing, haughtiness"
   
   "flectēbat" "they were bending"
   "flectentēs" "bending"
   "flexīs" "having been bent, flexed"
   "flectere" "to bend"
   "flectō, flectere, flēxī, flexum" "to bend"

   "flēre" "to cry"
   "fleō, flēre, flēvī, flētus" "to cry"
   "flētū" "weeping"

   "flōrida" "flowery"
   "flōridus, flōrida, flōridum" "flowery"

   "flōruit" "it blossomed"
   "flōreō, flōrēre, flōruī, -" "to blossom"
   
   "flōre" "flower"
   "flōribus" "flowers"
   "flōs, flōris" "flower"

   "fluēbant" "they were flowing"
   "fluentēs" "flowing"
   "fluit" "it flows"
   "fluunt" "they flow"
   "fluere" "to flow"
   "fluō, fluere, flūxī, flūxus" "to flow"

   "flūctus" "wave, billow, turbulence"
   "flūctuum" "of waves, of billows, of turbulence"
   "flūctibus" "waves, billows, turbulence"
   "flūctus, flūctūs" "wave, billow, turbulence"
   
   "flūmen" "river"
   "flūmina" "rivers"
   "flūmine" "river"
   "flūminibus" "rivers"
   "flūminis" "river"
   "flūminum" "of rivers"
   "flūmen, flūminis" "river"
   
   "fluvium" "river"
   "fluvius" "river"
   "fluvius, fluviī" "river"
   
   "focum" "hearth, fireplace, altar"
   "focus, focī" "hearth, fireplace, altar"

   "fōdērunt" "they dug"
   "fodere" "to dig"
   "foderēmus" "we were digging"
   "fodiēbant" "they were digging"
   "fodite" "dig!"
   "fodiō, fodere, fōdī, fossus" "to dig"

   "foedus" "treaty"
   "foedera" "treaties"
   "foederis" "treaty"
   "foedus, foederis" "treaty"

   "foenum" "hay"
   "foenī" "hay"
   "foenum, foenī" "hay"
   
   "folia" "leaves"
   "foliīs" "leaves"
   "folium, foliī" "leaf"
   
   "follium" "of bellows"
   "follis, follis" "bellows"
   
   "fōns" "fountain"
   "fontibus" "fountains"
   "fontis" "fountain"
   "fōns, fontis" "fountain"
   "fonte" "fountain"
   "fontem" "fountain"
   "fontēs" "fountains"
   "fontium" "of fountains"
   
   "forāmen" "opening, hole"
   "forāmina" "openings, holes"
   "forāmen, forāminis" "opening, hole"

   "forcipe" "tongs, forceps"
   "forcipem" "tongs, forceps"
   "forceps, forcipis" "tongs, forceps"

   "forēs" "doors"
   "foribus" "doors"
   "forīs, foris" "door"

   "formīdō" "fear, alarm, dread"
   "formīdine" "fear, alarm, dread"
   "formīdinis" "fear, alarm, dread"
   "formīdō, formīdinis" "fear, alarm, dread"

   "fōrmāverint" "they will have formed"
   "fōrmāre" "to form"
   "fōrmō, fōrmāre, fōrmāvī, fōrmātus" "to form"

   "fōrmōsa"  "beautiful, formly"
   "fōrmōsum" "beautiful, formly"
   "fōrmōsus" "beautiful, formly"
   "fōrmōsus, fōrmōsa -um, fōrmōsior -or -us, fōrmōsissimus -a -um" "beautiful, formly"
   
   "formidāre" "to dread"
   "formidō, formidāre, formidāvī, formidātus" "to dread"
   "fōrmula" "shape, formula"
   "fōrmula, fōrmulae" "shape, formula"

   "fortēs" "strong"
   "fortī" "strong"
   "fortior" "stronger"
   "fortiōrum" "of the stronger"
   "fortiōrēs" "stronger"
   "fortis" "strong"
   "fortissimē" "very strong"
   "fortissimō" "very strong"
   "fortissimum" "very strong"
   "fortis, forte, fortior -or -us, fortissimus -a -um" "strong"

   "fortissima" "very strong"
   "fortissimam" "very strong"
   "fortissimī" "very strong"
   "fortissimus" "very strong"
   
   "fortitūdō" "strength, fortitude"
   "fortitūdinis" "strength, fortitude"
   "fortitūdinem" "strength, fortitude"
   "fortitūdō, fortitūdinis" "strength, fortitude"
   "fortium" "strengh, fortitude"

   "fortunam" "luck, fate"
   "fortūna, fortūnae" "luck, fate"

   "forō" "forum"
   "forum, forī" "forum"
   
   "fossa" "ditch, moat"
   "fossam" "ditch, moat"
   "fossa, fossae" "ditch, moat"

   "fovea" "pit"
   "foveae" "pit"
   "foveam" "pit"
   "foveās" "pits"
   "fovea, foveae" "pit"

   "frāctiōnem" "breaking"
   "frāctiō, frāctiōnis" "breaking"

   "fragmentum, fragmentī" "fragment"
   "fragmentum" "fragment"
   "fragmentī" "fragment"
   "fragmentīs" "fragments"

   "fragor" "breaking, shattering"
   "fragor, fragōris" "breaking, shattering"

   "fragrāntiam" "fragrance"
   "fragrāntoia, fragrānciae" "fragrance"

   "frāctā" "having been broken"
   "frāctae" "having been broken"
   "frāctīs" "having been broken"
   "frāctō" "having been broken"
   "frēgit" "he broke, he shattered, he crushed"
   "frangī" "to be broken"
   "frangentem" "breaking, shattering, crushing"
   "frangere" "to break, to shatter, to crush"
   "frangō, frangere, frēgī, frāctus" "to break, to shatter, to crush"
   
   "frāter" "brother"
   "frāter, frātris" "brother"
   "frātre" "brother"
   "frātrem" "brother"
   "frātrēs" "brothers"
   "frātrī" "brother"
   "frātrīs" "brothers"
   "frātribus" "brothers"
   "frātrum" "of brothers"

   "frāternae" "fraternal"
   "frāternus, frāterna, frāternum" "fraternal"

   "frātruēlem" "fraternal nephew"
   "frātruēlis, frātruēlis" "fraternal nephew"

   "fraus" "fraud"
   "fraudis" "fraud"
   "fraude" "fraud"
   "fraudem" "fraud"
   "fraus, fraudis" "fraud"

   "fraxinum" "ash tree, spear of ash"
   "fraxinus" "ash tree, spear of ash"
   "fraxinus, fraxinī" "ash tree, spear of ash"

   "fremēns" "roaring, raging"
   "fremit" "he roars, rages"
   "fremere" "to roar, rage"
   "fremō, fremere, fremuī, fremitus" "to roar, rage"

   "frēna" "bridle"
   "frēnī" "bridle"
   "frēnīs" "bridle"
   "frēnō" "bridle"
   "frēnum" "bridle"
   "frēnum, frēnī" "bridle"
   
   "frequentātur" "it is crowded, it is frequented"
   "frequentō, frequentāre, frequentāvī, frequentātus" "to crowd, to frequent"

   "frequentius" "more frequently"
   "frequenter" "frequently"
   "frequēns, frequentis (gen.), frequentior -or -us, frequentissimus -a -um" "frequent"
   
   "fretō" "strait, channel"
   "fretum, fretī" "strait, channel"

   "fricantēs" "rubbing"
   "fricāre" "to rub"
   "fricō, fricāre, fricuī, frictus" "to rub"

   "frīgida"  "cold"
   "frīgidā"  "cold"
   "frīgidus" "cold"
   "frīgidus, frīgida -um, frīgidior -or -us, frīgidissimus -a -um" "cold"

   "frīgidum" "cold"
   "frīgidum, frīgidī" "cold"
   
   "frīgus, frīgoris" "cold"
   "frīgus" "cold"
   "frīgoris" "cold"

   "frōns"   "forehead, front"
   "fronte"  "forehead, front"
   "frontem" "forehead, front"
   "frōns, frontis" "forehead, front"
   
   "frūctū" "fruit"
   "frūctus" "fruit"
   "frūctum" "fruit"
   "frūctibus" "fruits"
   "frūctus, frūctūs" "fruit"

   "frūmentī" "corn, grain"
   "frūmentō" "corn, grain"
   "frūmentum" "corn, grain"
   "frūmentum, frūmentī" "corn, grain"

   "frūmentātum" "having gotten grain"
   "frūmentor, frūmentārī, frūmentātus" "to get grain"

   "frūmentāriā" "concerning grain"
   "frūmentāriae" "rich in grain"
   "frūmentārius, frūmentāria, frūmentārium" "rich in grain"
   
   "fuerat" "he had been"
   "fuērunt" "they were"

   "fuga" "flight, escape"
   "fugae" "flight, escape"
   "fugam" "flight, escape"
   "fuga, fugae" "flight, escape"

   "fugāvit" "he routed, chased away"
   "fugārunt" "they routed, chased away"
   "fugāvērunt" "they routed, chased away"
   "fugātus" "having been routed, chased away"
   "fūgerant" "they had routed, chased away"
   "fugāre" "to rout, to chase away"
   "fugō, fugāre, fugāvī, fugātus" "to rout, to chase away"

   "fūgerat" "he fled"
   "fugere" "to flee"
   "fugeret" "he fled"
   "fugerent" "they might have fled"
   "fūgērunt" "they fled"
   "fugiāmus" "we might have fled"
   "fugiēbat" "he was fleeing"
   "fugiēbant" "they were fleeing"
   "fugiendō" "fleeing"
   "fugiēns" "fleeing"
   "fugientēs" "fleeing"
   "fugis" "you flee"
   "fugit" "he flees, he fled"
   "fugite" "flee"
   "fugientem" "fleeing"
   "fugientum" "fleeing"
   "fūgistī" "you fled"
   "fugiunt" "they fled"
   "fugiō, fugere, fūgī, fugitus" "to flee, to avoid"

   "fuerit" "it will have been"
   "fuī" "I was"
   "fuimus" "we were"
   "fuisse" "to have been"
   "fuissem" "I (might) have had been"
   "fuisset" "he (might) have had been"
   "fuissent" "they (might) have had been"
   "fuistī" "you were"
   "fuit" "he was"
   "fuistis" "you were"
   "fuerant" "they had been"
   "fuēre" "they were, alternative spelling of fuērunt"

   "fulciēbātur" "it was supported"
   "fulcītur" "it is supported"
   "fulcīre""to prop up, support"
   "fultī" "having been supported"
   "fultum" "having been supported"
   "fulciō, fulcīre, fulsī, fultus" "to prop up, support"

   "fulgēbat" "it was flashing, shining, glowing"
   "fulgēre" "to flash, shine, glow"
   "fulgeō, fulgēre, fulsī, -" "to flash, shine, glow"
   
   "fūmōsus" "smoky"
   "fūmōsus, fūmōsa, fūmōsum" "smoky"
   "fūmus" "smoke"
   "fūmō" "smoke"
   "fūmus, fūmī" "smoke"
   
   "fundāmentum" "foundation"
   "fundāmentum, fundāmentī" "foundation"

   "funda" "sling"
   "fundīs" "slings"
   "funda, fundae" "sling"

   "fundāvit" "he founded"
   "fundō, fundāre, fundāvī, fundātus" "to found"
   
   "fūnēs" "ropes"
   "fūnibus" "ropes"
   "fūnis, fūnis" "rope"
   
   "fūniculōs" "slender ropes, cords"
   "fūniculus, fūniculī" "slender rope, cord"
   
   "furcae" "fork"
   "furca, furcae" "fork"

   "furiīs" "frenzies, furies"
   "furia" "frenzy, fury"
   "furia, furiae" "frenzy, fury"

   "furōrem" "frenzy, rage, madness"
   "furor" "frenzy, rage, madness"
   "furor, furōris" "frenzy, rage, madness"
   
   "fūrtī" "theft, stolen article"
   "fūrtō" "theft, stolen article"
   "fūrtum" "theft, stolen article"
   "fūrtum, fūrtī" "theft, stolen article"
   
   "futūra" "future"
   "futūrō" "future"
   "futūrus, futūra, futūrum" "future"
   })
