(ns whitakers-clj.dict-o)

(def dict-o
  {"obaerātōs" "debtors"
   "obaerātus" "debtor"
   "obaerātus, obaerātī" "debtor"

   "obaudīvit" "he obeyed, listened to"
   "obaudiō, obaudīre, obaudiī, obaudītus" "to obey, to listen to"

   "obdormīvit" "he fell asleep"
   "obdormīvissent" "they (might) have had fallen asleep"
   "obdormiō, obdormīre, obdormīvī, obdormītus" "to fall asleep"
   
   "obēdiāmus" "let us obey"
   "obēdientem" "obeying"
   "obēdīre" "to obey"
   "obēdiō, obēdīre, obēdīvī, obēdītus" "to obey"

   "oblīviō, oblīviōnis" "forgetfulness"
   "oblīviōnem" "forgetfulness"

   "obnūbilābant" "they were obscuring, clouding"
   "obnubilāre" "to obscure, cloud"
   "obnubilō, obnubilāre, obnubilāvī, obnubilātus" "to obscure, cloud"
   
   "oboedientiam" "obedience"
   "oboedientia, oboedientiae" "obedience"

   "obrizō" "refined (gold)"
   "obrizus, obriza, obrizum" "refined (gold)"

   "obscūritās"  "darkness, lowliness, meanness"
   "obscūritāte" "darkness, lowliness, meanness"
   "obscūritās, obscūritātis" "darkness, lowliness, meanness"

   "obscūra" "dark, unknown"
   "obscūrus, obscūra -um, obscūrior -or -us, obscūrissimus -a -um" "dark, unknown"

   "obsecrō" "I entreat, beseech, pray"
   "obsecrāre" "to entreat, beseech, pray"
   "obsecrō, obsecrāre, obsecrāvī, obsecrātus" "to entreat, beseech, pray"
   
   "obsequium" "allegiance, obedience"
   "obsequium, obsequiī" "allegiance, obedience"

   "observābat" "he was watching"
   "observāre" "to observe, to watch"
   "observāte" "watch!"
   "observō, observāre, observāvī, observātus" "to observe, to watch"

   "obsīdēbat" "he was besieging"
   "obsideret" "they besieged"
   "obsēdimus" "we besieged"
   "obsēdit" "he besieged"
   "obsidēre" "to besiege"
   "obsēderant" "they had besieged"
   "obsēdērunt" "they besieged"
   "obsessa"  "having been besieged"
   "obsessī"  "having been besieged"
   "obsessīs" "having been besieged"
   "obsident" "they besiege"
   "obsidentem" "besieging"
   "obsideō, obsidēre, obsēdī, obsessus" "to besiege"
   "obsīdendī" "besieging, blockading"
   
   "obsidēs" "hostages"
   "obsidibus" "hostages"
   "obsidum" "of hostages"
   "obses, obsidis" "hostage"

   "obsessiō" "siege"
   "obsessiōne" "siege"
   "obsessiō, obsessiōnis" "siege"

   "obsidiō" "siege"
   "obsidiōne" "siege"
   "obsidiōnem" "siege"
   "obsidiō, obsidiōnis" "siege"

   "obsistere" "to oppose, resist, withstand"
   "obsistō, obsistere, obstitī, obstitus" "to oppose, resist, withstand"

   "obtestātus" "having been implored"
   "obtestor, obtestārī, obtestātus sum" "to implore"

   "obstācula" "obstacles, hindrances"
   "obstāculum" "obstacle, hindrance"
   "obstāculum, obstāculī" "obstacle, hindrance"

   "obstāns" "opposing"
   "obstāre" "to oppose"
   "obstō, obstāre, obstitī, obstātus" "to oppose"

   "obtentūrus" "will be obtaining"
   "obtinēbat" "he was obtaining"
   "obtinēbant" "they were obtaining"
   "obtinuerat" "he had obtained"
   "obtinuerant" "they had obtained"
   "obtinuērunt" "they obtained"
   "obtinuisset" "he had obtained"
   "obtinuit" "he obtained"
   "obtinēre" "to obtain"
   "obtineō, obtinēre, obtinuī, obtentus" "to obtain"
   
   "obumbrāvit" "it overshadowed, it darkened"
   "obumbrāvisset" "he (might) have had overshadowed"
   "obumbrō, obumbrāre, obumbrāvī, obumbrātus" "to overshadow, to darken"

   "obviant" "they oppose, resist"
   "obviantēs" "opposing, resisting"
   "obviāvērunt" "they opposed, resisted"
   "obviāre" "to oppose, resist"
   "obviō, obviāre, obviāvī, obviātus" "to oppose, resist"
   
   "ōceanī" "ocean"
   "ōceanō" "ocean"
   "ōceanus" "ocean"
   "ōceanus, ōceanī" "ocean"
   "ōceanum" "ocean"

   "occāsum" "setting, end"
   "occāsus" "setting, end"
   "occāsus, occāsūs" "setting, end"

   "occāsiōnem" "occasion, opportunity"
   "occāsiō, occāsiōnis" "occasion, opportunity"
   
   "occidentālis, occidentālis, occidentāle" "western"
   "occidentālem" "western"
   "occidentālis" "western"
   "occidentālibus" "western"

   "occiduā" "westerly"
   "occiduus, occidua, occiduum" "western"
   
   "occīdī" "I killed"
   "occīdō" "I kill"
   "occīsī" "having been killed"
   "occīsum" "having been killed"
   "occīsus" "having been killed"
   "occīdō, occīdere, occīdī, occīsus" "to kill"

   "occīsiō"    "massacre, slaughter, murder"
   "occīsiōne"  "massacre, slaughter, murder"
   "occīsiōnem" "massacre, slaughter, murder"
   "occīsiōnis" "massacre, slaughter, murder"
   "occīsiō, occīsiōnis" "massacre, slaughter, murder"

   "occubuit" "she laid dead"
   "occubāre" "to lie dead"
   "occubō, occubāre, occubuī, occubitus" "to lie dead"

   "occultant" "they hide"
   "occultantur" "they are hidden"
   "occultābant" "they were hiding"
   "occultāverant" "they had hidden"
   "occultāvērunt" "they hide"
   "occultāret" "he was hiding"
   "occultāre" "to hide"
   "occultō, occultāre, occultāvī, occultātus" "to hide"

   "occultō" "secrecy"
   "occultum" "secrecy"
   "occultum, occultī" "secrecy"

   "occultē" "secretly"
   "occultus, occulta -um, occultior -or -us, occultissimus -a -um" "secret"

   "occupāret" "he (might) have seized"
   "occupātō" "attack!"
   "occupāta" "having been seized"
   "occupātis" "having been seized"
   "occupātōs" "having been seized"
   "occupāvērunt" "they seized, overtook, attacked"
   "occupāvit" "he seized, attacked"
   "occupābit" "he will seize, overtake, attack"
   "occupō, occupāre, occupāvī, occupātum" "to seize, to overtake, to attack"

   "occurrerat" "he had run"
   "occurrērunt" "they ran"
   "occurrit" "he ran"
   "occurrere" "to run"
   "occurrō, occurrere, occurrī, occursus" "to run"

   "occursum" "meeting"
   "occursus, occursūs" "meeting"
   
   "octō" "8"
   "octōgintā" "80"
   "octōginta, octōgēsimus -a -um, octōgēnī -ae -a, octōgiē (n)s" "80"
   "oculī" "eye"
   "oculīs" "eyes"
   "oculōs" "eyes"
   "oculus, oculī" "eye"
   "oculōrum" "eyes"
   "odōrem" "odor, scent"
   "odor" "odor, scent"
   "odōre" "odor, scent"
   "odor, odōris" "odor, scent"

   "offendentem" "offending, annoying"
   "offenditis" "you offend"
   "offendere" "to offend, annoy"
   "offendō, offendere, offendī, offēnsus" "to offend, annoy"

   "obtulit" "he offered, presented"
   "offerebant" "they were offering"
   "offerō, offerre, obtulī, oblātus" "to offer"

   "officī" "having been impeded"
   "officere" "to impede"
   "officiō, officere, offēcī, offectus" "to impede"
   
   "officīnam" "workshop, manufactory"
   "officīnās" "workshops"
   "officīnīs" "workshops"
   "officīna, officīnae" "workshop, manufactory"
   
   "officiō" "duty, service, favor"
   "officium" "duty, service, favor"
   "officium, officiī" "duty, service, favor"

   "ogdoade" "eight, eight-year cycle; singular feminine ablative from ogdoas, ogdoadis"
   "ogdoas, ogdoadis" "eight, eight-year cycle"

   "oleum" "olive oil"
   "oleum, oleī" "olive oil"
   
   "ōlla" "pot, jar"
   "ōlla, ōllae" "pot, jar"
   
   "omne"  "all, every"
   "omnem" "all, every"
   "omnen" "all, every"
   "omnēs" "all, every"
   "omnī" "all, every"
   "omnia" "all, every"
   "omnis" "all, every"
   "omnis, omnis, omne" "all, every"
   "omnium" "of all"
   "omnibus" "all"
   "omnipotēns" "all-powerful"
   "omnipotentis" "all-powerful"
   "omnipotēns, (gen.), omnipotentis" "all-powerful"
   
   "onerantibus" "loading"
   "onerāre" "to load, to burden"
   "onerāta" "having been burdened"
   "onerātis" "you load, you burden"
   "onerāvērunt" "they loaded"
   "onerāverant" "they had loaded"
   "onerāvit" "he loaded"
   "onerō, onerāre, onerāvī, onerātus" "to load, to burden"

   "onerāriās" "burdened"
   "onerāriīs" "burdened"
   "onerārius, onerāria, onerārium" "burdened"

   "onere" "burden"
   "oneris" "burden"
   "onus" "burden"
   "onus, oneris" "burden"

   "onustās" "laden"
   "onustīs" "laden"
   "onustōs" "laden"
   "onustus, onusta, onustum" "laden"

   "operītur" "it is covered"
   "operuit" "he covered"
   "operiō, operīre, operuī, opertus" "to cover"

   "opīmīs" "well-fed, fat, fertile"
   "opīmus, opīma, opīmum" "well-fed, fat, fertile"
   
   "oportet" "it is right/proper/necessary"
   "oportere" "it is right/proper/necessary"
   "oportet, oportere, oportuit, -" "it is right/proper/necessary"

   "oportūnō" "opportune"
   "oportunissimō" "very opportune"
   "oportūnus, oportūna -um, oportunior -or -us, oportunissimus -a -um" "opportune"

   "oppida" "towns"
   "oppidīs" "towns"
   "oppidō" "town"
   "oppidum" "town"
   "oppidum, oppidī" "town"

   "opportūnō" "opportune, suitable"
   "opportūnissimō" "very opportune, a suitable time"
   "opportūnus, opportūna -um, opportūnior -or -us, opportūnissimus -a -um" "opportune, a suitable time"

   "oppugnātiō" "assault, attack"
   "oppugnātiōne" "assault, attack"
   "oppugnātiōnem" "assault, attack"
   "oppugnātiōnis" "assault, attack"
   "oppugnātiō, oppugnātiōnis" "assault, attack"

   "optimae" "very good"
   "optimam" "very good"
   "optimās" "very good"
   "optimīs" "very good"
   "optimōs" "very good"

   "opera" "works, deeds"
   "opere" "work, deed"
   "operibus" "works, deeds"
   "operis" "work, deed"
   "opus" "work, deed"
   "opus, operis" "work, deed"

   "oppressiō" "pressing down, overthrow"
   "oppressiōne" "pressing down, overthrow"
   "oppressiō, oppressiōnis" "pressing down, overthrow"

   "oppressī" "having been oppressed"
   "oppressīs" "having been oppressed"
   "oppressus" "having been oppressed"
   "opprimere" "to press down, to oppress"

   "oppūgnābant" "they were attacking"
   "oppūgnandīs" "to be attacked"
   "oppūgnātum" "having been attacked"
   "oppūgnāvī" "I attacked"
   "oppūgnāre" "to attack"
   "oppūgnō, oppūgnāre, oppūgnāvī, oppūgnātus" "to attack"

   "optāmus" "we choose, wish"
   "optāre" "to choose, wish"
   "optō, optāre, optāvī, optātus" "to choose, wish"

   "ōrācula" "oracles, divine announcements"
   "ōrāculum" "oracle, divine announcement"
   "ōrāculum, ōrāculī" "oracle, divine announcement"

   "ōrās" "border, edge, frontier"
   "ōra, ōrae" "border, edge, frontier"

   "ōrātiōne"  "oration, speech, discourse"
   "ōrātiōnem" "oration, speech, discourse"
   "ōrātiōnēs" "speeches, discourses"
   "ōrātiō, ōrātiōnis" "oration, speech, discourse"
   "ōrātiōnibus" "oration, speech, discourse"

   "ōrantēs" "praying"
   "ōrāvērunt" "they prayed"
   "ōrārent" "they prayed"
   "ōrāret" "he prayed"

   "ōrātōris" "speaker"
   "ōrātor, ōrātōris" "speaker"
   
   "ōrātōriō" "oratory, building for prayer"
   "ōrātōrium" "oratory, building for prayer"
   "ōrātōrium, ōrātōriī" "oratory, building for prayer"

   "orbāta" "having been deprived"
   "orbāre" "to deprive, bereave of parents"
   "orbō, orbāre, orbāvī, orbātus" "to deprive, bereave of parents"

   "orbem" "sphere, orbit, circle, ring"
   "orbis" "sphere, orbit, circle, ring"
   "orbis, orbis" "sphere, orbit, circle, ring"
   
   "ōrdinem" "order"
   "ōrdinēs" "order"
   "ōrdinibus" "order"
   "ōrdinis" "order"
   "ōrdinum" "order"
   "ōrdō" "order"
   "ōrdō, ōrdinis" "order"
   "ōrdine" "order"

   "ōrdinandō" "setting in order"
   "ōrdinābat" "he was setting in order"
   "ōrdināta" "having been set in order"
   "ōrdinātae" "having been set in order"
   "ōrdinātās" "having been set in order"
   "ōrdināvērunt" "they ordained, set in order"
   "ōrdināvit" "he ordained, set in order"
   "ōrdinātī" "having been set in order, ordained"
   "ōrdinō, ōrdināre, ōrdināvī, ōrdinātus" "to set in order, ordain"
   
   "ōre" "mouth"
   
   "organum" "organ, instrument"
   "organī" "organ, instrument"
   "organum, organī" "organ, instrument"
   
   "oriēns" "daybreak, dawn, East"
   "oriente" "daybreak, dawn, East"
   "orientis" "daybreak, dawn, East"
   "orientem" "daybreak, dawn, East"
   "oriēns, orientis" "daybreak, dawn, East"
   
   "orientālem" "eastern"
   "orientālēs" "eastern"
   "orientālī" "eastern"
   "orientālis, orientālis, orientāle" "eastern"

   "orīgine" "origin"
   "orīginis" "origin"
   "orīgō" "origin"
   "orīgō, orīginis" "origin"

   "ōrābat" "he was praying"
   "ōrābant" "they were praying"
   "ōrandī" "praying"
   "ōrāns" "praying"
   "ōrāre" "to pray"
   "ōrāvit" "he prayed"
   "ōrent" "let them pray"
   "ōrō, ōrāre, ōrāvī, ōrātus" "to pray"

   "ōrnāmenta" "ornament, jewelry, equipment"
   "ōrnāmentīs" "ornaments, jewelry, equipment"
   "ōrnāmentō" "ornaments, jewelry, equipment"
   "ōrnāmentōrum" "of ornaments, jewelry, equipment"
   "ōrnāmentum" "ornament, jewelry, equipment"
   "ōrnāmentum, ōrnāmentī" "ornament, jewelry, equipment"

   "ōrnat" "he/she/it adorns"
   "ōrnant" "they adorn"
   "ōrnātur" "he/she/it is adorned"
   "ōrnantur" "they are adorned"

   "orta" "having arisen"
   "ortae" "having arisen"
   "ortī" "having arisen"
   "oriuntur" "they originate, they arise"
   "orīrī" "to originate, to arise"
   "orior, orīrī, ortus sum" "to originate, to arise"

   "ortū" "rising, beginning"
   "ortum" "rising, beginning"
   "ortus" "rising, beginning"
   "ortus, ortūs" "rising, beginning"
   
   "ōs, ōris" "mouth"
   "ōscula" "kisses"
   "ōsculō" "kiss"
   "ōsculum" "kiss"
   "ōsculum, ōsculī" "kiss"
   
   "ōsculābantur" "they were kissing"
   "ōsculantibus" "kissing"
   "ōsculārētur" "he (might) have been kissing"
   "ōsculātus" "ōsculātus est = he kissed"
   "ōsculāns" "kissing"
   "ōsculātīs" "having been kissed"
   "ōsculor, ōsculārī, ōsculātus sum" "to kiss"

   "ostendant" "they show"
   "ostendātur" "he (might) be being shown"
   "ostendit" "he shows, he showed"
   "ostendentēs" "showing"
   "ostendet" "you will show"
   "ostenditur" "it is shown"
   "ostendunt" "they show"
   "ostende" "show!"
   "ostendere" "to show"
   "ostendō, ostendere, ostendī, ostentus" "to show"

   "ostensiō"    "presenting, showing, exhibiting"
   "ostensiōnem" "presenting, showing, exhibiting"
   "ostensiōnis" "presenting, showing, exhibiting"
   "ostensiō, ostensiōnis" "presenting, showing, exhibiting"

   "os" "bone"
   "ossa" "bones"
   "ossibus" "bones"
   "os, ossis" "bones"
   
   "ōstia" "doors"
   "ōstiī" "doors"
   "ōstiō" "door"
   "ōstium" "door"
   "ōstium, ōstiī" "door"
   "ōstium, ōsti(ī)" "door"

   "ōstiāriō"  "doorman"
   "ōstiārius" "doorman"
   "ōstiārius, ōstiāriī" "doorman"

   "ovāns" "rejoicing"
   "ovāre" "to rejoice"
   "ovō, ovāre, ovāvī, ovātus" "to rejoice"
   
   "ovem" "sheep"
   "ovēs" "sheep"
   "ovibus" "sheep"
   "ovis" "sheep"
   "ovium" "of sheep"
   "ovis, ovis" "sheep"

   "ōva" "eggs"
   "ōvum" "egg"
   "ōvum, ōvī" "egg"
   })
