(ns whitakers-clj.dict-h)

(def dict-h
  {"habeam" "I (might) have"
   "habeat" "let him have"
   "habeant" "let them have"
   "habēbat" "he had"
   "habēbant" "they had"
   "habentem" "having"
   "habentēs" "having"
   "habēbis" "you will have"
   "habēbitis" "you will have"
   "habeō" "I have"
   "habitum" "having been held"
   "habitāvit" "he inhabited"
   "habēmus" "we have"
   "habēns" "having"
   "habent" "they have"
   "habēs" "you have"
   "habet" "he has"
   "habētis" "you have"
   "habuērunt" "they had"
   "habuerit" "you will have had"
   "habēre" "to have"
   "habēret" "he (might) have had"
   "habita" "having been had"
   "habērent" "they (might) have been having"
   "habēbimus" "we will have"
   "habēbit" "he will have"
   "habēbunt" "they will have"
   "habuī" "I had"
   "habētur" "it is had"
   "habuissem" "I might have had"
   "habeāmus" "let us have"
   "habuerant" "they had had"
   "habeō, habēre, habuī, habitus" "to have"

   "habitat" "he lives"
   "habitābam" "I was living"
   "habitantem" "living, inhabiting"
   "habitantium" "inhabiting"
   "habitāre" "to inhabit"
   "habitābat" "he was living"
   "habitābant" "they were living"
   "habitābitis" "you will have"
   "habitandum" "living"
   "habitant" "they inhabit"
   "habitantēs" "inhabiting"
   "habitāret" "he inhabited"
   "habitāta" "having been inhabited"
   "habitāvērunt" "they inhabited"
   "habitāvī" "I inhabited"
   "habitāverint" "they inhabited"
   "habitō, habitāre, habitāvī, habitātus" "to inhabit"
   
   "habitātiō" "dwelling"
   "habitātiōne" "dwelling"
   "habitātiō, habitātiōnis" "dwelling"
   "habitātōre" "dweller"
   "habitātōrēs" "dwellers"
   "habitātōribus" "dwellers"
   "habitātor, habitātōris" "dweller"
   
   "habuimus" "we had"
   "habuisset" "he (might) have had"
   "habuissēmus" "we (might) have had"
   "habuit" "he had"
   "habitū" "habit, character"
   "habitus, habitūs" "habit, character"
   "hauriendam" "drawing, drinking, exhausting"
   "hauriō, haurīre, hausī, haustus" "to draw up, to drink, to exhaust"

   "haeresēs" "heresies"
   "haeresis, haeresis" "heresy"

   "haesitet" "it might hesitate"
   "haesitāre" "to hesitate"
   "haesitō, haesitāre, haesitāvī, haesitātus" "to hesitate"

   "hastae" "spears"
   "hastīs" "spears"
   "hasta, hastae" "spear"

   "Helvētiī" "Helvetii, members of a Gallic tribe (sing. gen. or pl. nom.)"
   "helvētiī" "Helvetii, members of a Gallic tribe (sing. gen. or pl. nom.)"
   "Helvētiīs" "Helvetii, members of a Gallic tribe (plural dat. or abl.)"
   "helvētiīs" "Helvetii, members of a Gallic tribe (plural dat. or abl."
   "Helvētiōrum" "Helvetii, members of a Gallic tribe (plural genitive)"
   "helvētiōrum" "Helvetii, members of a Gallic tribe (plural genitive)"
   "Helvētiōs" "Helvetii, members of a Gallic tribe (plural accusative)"
   "helvētiōs" "Helvetii, members of a Gallic tribe (plural accusative)"
   "Helvētium" "Helvetii, members of a Gallic tribe (plural genitive)"
   "helvētium" "Helvetii, members of a Gallic tribe (plural genitive)"
   
   "herba" "grass, herb"
   "herbā" "grass, herb"
   "herbae" "grass, herb"
   "herbam" "grass, herb"
   "herbārum" "grass, herbs"
   "herba, herbae" "grass, herb"
   "herbīs" "herbs, grass"
   "herbās" "herbs"
   
   "herbōsa" "grassy, herbaceous"
   "herbōsam" "grassy, herbaceous"
   "herbōsus" "grassy, herbaceous"

   "herculis" "of Hercules"
   "Herculis" "of Hercules"
   "Herculēs, Herculis" "Hercules"
   
   "hērēditātem" "inheritance"
   "hērēditāte" "inheritance"
   "hērēditātēs" "inheritance"
   "hērēditās, hērēditātis" "inheritance"
   
   "heremita" "hermit"
   "heremitae" "hermit"
   "heremitam" "hermit"
   "heremita, heremitae" "hermit"

   "hērēdēs" "heirs"
   "hērēs, hērēdis" "heir"

   "hēreticōrum" "of heretics"
   "hēreticus, hēretica, hēreticum" "heretic"

   "hesternō" "yesterday's"
   "hesternus, hesterna, hesternum" "yesterday's"

   "hīberna" "winter camp"
   "hībernō" "winter, winter camp"
   "hībernī" "winter, winter camp"
   "hībernīs" "winter camp"
   "hībernum, hībernī" "winter camp"

   "hībernia" "Ireland"
   "hīberniam" "Ireland"
   "Hībernia, Hīberniae" "Ireland"

   "hiemāre" "to winter"
   "hiemārī" "to be wintery"
   "hiemō, hiemāre, hiemāvī, hiemātus" "to winter"

   "hiemem" "winter"
   "hiemis" "of winter"
   "hiemps" "winter"
   "hiemps, hiemis" "winter"

   "hiems" "winter"
   "hiems, hiemis" "winter"
   
   "hilaritās, hilaritātis" "good humor"
   "hilaritās" "good humor"
   "hilaritātis" "good humor"
   "hilaritāte" "good humor"

   "hispāniae" "of Hispania"
   "Hispāniae" "of Hispania"
   "Hispāniam" "Hispania"
   "hispāniam" "Hispania"
   "Hispānia, Hispāniae" "Hispania"
   "hispānia" "Hispania"
   "hispānī" "Hispanic"
   "hispānīs" "Hispanics"
   "hispānia, hispāniae" "Hispania"
   
   "hispidum" "rough, shaggy"
   "hispidus" "rough, shaggy"
   "hispidus, hispida, hispidum" "rough, shaggy"

   "historia" "history, story"
   "historiae" "history, story"
   "historia, historiae" "history, story"

   "hodiernā" "today"
   "hodiernum" "today"
   "hodiernum, hodiernī" "today"

   "hodiernus, hodierna, hodiernum" "modern, of today"

   "homine" "person"
   "hominem" "person"
   "hominēs" "persons"
   "hominī" "person, man"
   "hominis" "of a person"
   "hominum" "of persons, of men"
   "hominibus" "persons, men"
   "homō" "person"
   "homō, hominis" "person"

   "hominium" "homage; variant spelling from homāgium or homināticum"
   "homāgium, homāgiī" "homage, vassaldom"

   "honestāvit" "he honored, dignified"
   "honestō, honestāre, honestāvī, honestātum" "to honor, dignify"

   "honestē" "honestly, distinguishedly, worthily"
   "honestum" "honest, distinguished, worthy"
   "honestissimīs" "very honest, distinguished, worthy"
   "honestissimō" "very honest, distinguished, worthy"
   "honestissimam" "very honest, distinguished, worthy"
   "honestissimum" "very honest, distinguished, worthy"
   "honestissimus" "very honest, distinguished, worthy"
   "honestus, honesta -um, honestior -or -us, honestissimus -a -um" "honest, distinguished, worthy"

   "honor"  "honor"
   "honore" "honor"
   "honorem" "honor"
   "honor, honōris" "honor"

   "honōrābilia" "honorable"
   "honōrābile" "honorable"
   "honōrābilem" "honorable"
   "honōrābilēs" "honorable"
   "honōrābilis" "honorable"
   "honōrābilis, honōrābilis, honōrābile" "honorable"

   "honōrificet" "let him honor"
   "honōrificāre" "to honor"
   "honōrificō, honōrificāre, honōrificāvī, honōrificātus" "to honor"
   
   "hōram" "hour, time"
   "hōra" "hour, time"
   "hōrae" "hour, time"
   "hōrās" "hours, times"
   "hōrīs" "hours, times"
   "hōra, hōrae" "hour, time"

   "hordeō" "barley"
   "hordeum" "barley"
   "hordeum, hordeī" "barley"

   "hōrologiō" "clock"
   "hōrologium" "clock"
   "hōrologium, hōrologiī" "clock"

   "horret" "he dreads, shudders"
   "horrent" "they dread, shudder"
   "horreō, horrēre, horruī" "to dread, shudder"

   "horrendīs" "horrendous"

   "horrida"  "dreadful, horrid, rude"
   "horridum" "dreadful, horrid, rude"
   "horridus" "dreadful, horrid, rude"
   "horridus, horrida, horridum" "dreadful, horrid, rude"

   "horrificum" "horrific"
   "horrificus, horrifica, horrificum" "horrific"
   
   "hortor, hortārī, hortātus sum" "to exhort"
   "hortābātur" "he was exhorting"
   "hortātī" "having been exhorted"

   "hortātū" "encouragement, exhortation"
   "hortātus" "encouragement, exhortation"
   "hortātus, hortātūs" "encouragement, exhortation"

   "hortō"  "garden"
   "hortum" "garden"
   "hortus" "garden"
   "hortus, hortī" "garden"

   "hospitārī" "to be lodged"
   "hospitātī"  "having been lodged"
   "hospitātō"  "having been lodged"
   "hospitātus" "having been lodged"
   "hospitāre" "to offer hospitality, to lodge"
   "hospitō, hospitāre, hospitāvī, hospitātus" "to offer hospitality, to lodge"
   
   "hospes, hospitis" "guest"
   "hospitēs" "guests"
   "hospitibus" "guests"
   "hospitum" "of the guests"

   "hospitiō" "hospitality"
   "hospitium" "hospitality"
   "hospitium, hospitiī" "hospitality"

   "hospitālis" "hospitable"
   "hospitālis, hospitālis, hospitāle" "hospitable"

   "hostīlēs" "enemies"
   "hostīliter" "in a hostile manner (adverb)"
   "hostīlis, hostīlis, hostīle" "enemy"

   "hoste" "enemy"
   "hostēs" "enemies"
   "hostibus" "enemies"
   "hostem" "enemy"
   "hostis" "enemy"
   "hostium" "of enemies"
   "hostis, hostis" "enemy"

   "hūmānitās"  "humanity, civilization"
   "hūmānitāte" "humanity, civilization"
   "hūmānitās, hūmānitātis" "humanity, civilization"
   
   "hūmāna" "human, cultured, refined"
   "hūmānae" "human, cultured, refined"
   "hūmānam" "human, cultured, refined"
   "hūmānārum" "human, cultured, refined"
   "hūmānō" "human, cultured, refined"
   "hūmānum" "human, cultured, refined"
   "hūmānus, hūmāna -um, hūmānior -or -us, hūmānissimus -a -um" "human, cultured, refined"

   "humātus" "having been buried"
   "humāvissent" "they had buried"
   "humāre" "to bury"
   "humō, humāre, humāvī, humātus" "to bury"

   "humerīs" "shoulders"
   "humerōs" "shoulders"
   "humerus" "shoulder"
   "humerus, humerī" "shoulder"

   "humidam" "humid, wet, moist"
   "humidus, humida, humidum" "humid, wet, moist"

   "humiliāvērunt" "they humiliated"
   "humiliāre" "to humble, to abase, to humililate"
   "humiliō, humiliāre, humiliāvī, humiliātus" "to humble, to abase, to humililate"
   "humilitās, humilitātis" "humility, insignificance, commonplaceness"
   "humilitāte" "humility, insignificance, commonplaceness"

   "humilem" "humble, small"
   "humilēs" "humble, small"
   "humillimā" "very humble"
   "humiliter" "humbly"
   "humilis, humile, humilior -or -us, humillimus -a -um" "humble, small"

   "hūmor" "liquid"
   "hūmōre" "liquid"
   "hūmor, hūmōris" "liquid"
   
   "hymnīs" "hymns"
   "hymnō" "hymn"
   "hymnōs" "hymns"
   "hymnus" "hymn"
   "hymnum" "hymn"
   "hymnus, hymnī" "hymn"
   })
