(ns whitakers-clj.dict-a)

(def dict-a
  {"abbās" "abbot"
   "abbātibus" "abbots"
   "abbātis" "abbot"
   "abbās, abbātis" "abbot"
   "abbātem" "abbot"

   "abdita" "having been hidden, removed"
   "abdō, abdere, abdidī, abditus" "to hide, to remove"

   "abeunt" "they depart"
   "abībant" "they were departing"
   "abiērunt" "they departed"
   "abit" "he departs"
   "abī" "depart!"
   "abīre" "to depart"
   "abeō, abīre, abiī, abitus" "to depart"

   "abigere" "to drive away"
   "abigō, abigere, abēgī, abāctus" "to drive away"

   "abesse" "to be absent"
   "abest" "he is absent"
   "absunt" "they are absent"
   "absum, abesse, āfuī, abfutūrus" "to be absent"

   "ablātīvī" "ablative"
   "ablātīvō" "ablative"
   "ablātīvum" "ablative"
   "ablātīvus" "ablative"
   "ablātīvus, ablātīvī" "ablative"

   "abneget" "he denies"
   "abnegāre" "to deny, to refuse"
   "abnegō, abnegāre, abnegāvī, abnegātus" "to deny, to refuse"

   "abscessit" "he left"
   "abscesserat" "he had left"
   "abscēdere" "to leave"
   "abscēdō, abscēdere, abscessī, abscessus" "to leave"

   "abscondit" "he hid, concealed"
   "abscondō, abscondere, abscondī, absconditus" "to hide, to conceal"
   "absconditōrum" "of things hidden"

   "absēns" "absent"
   "absēns, (gen.), absentis" "absent"
   
   "absentia" "absence"
   "absentia, absentiae" "absence"

   "absolūtī" "having been absolved"
   "absolvere" "to absolve"
   "absolvō, absolvere, absolvī, absolūtus" "to absolve"
   
   "abstinentia" "abstinence, self-restraint"
   "abstinentiae" "abstinence, self-restraint"
   "abstinentia, abstinentiae" "abstinence, self-restraint"

   "abstrāximus" "we dragged away"
   "abstrahere" "to drag away"
   "abstrahō, abstrahere, abstrāxī, abstractus" "to drag away"

   "abundantia"  "abundance, plentifulness"
   "abundantiam" "abundance, plentifulness"
   "abundantia, abundantiae" "abundance, plentifulness"

   "abundat" "it abounds"
   "abundāre" "to abound"
   "abundō, abundāre, abundāvī, abundātus" "to abound"
   
   "abyssī" "abyss"
   "abyssus, abyssī" "abyss"

   "accēde" "approach!"
   "accēderet" "he (might) have been approaching"
   "accēdit" "he approaches"
   "accessit" "he approached"
   "accēdere" "to approach"
   "accēdō, accēdere, accessī, accessus" "to approach"

   "accelerābat" "he was speeding up"
   "accelerāret" "he was speeding up"
   "accelerō, accelerāre, accelerāvī, accelerātus" "to speed up"

   "accēnsum" "having been lit on fire"
   "accēnsō" "having been lit on fire"
   "accendere" "to light on fire"
   "accendō, accendere, accendī, accēnsus" "to light on fire"

   "accentū" "accent, intonation, accentuation"
   "accentus" "accent, intonation, accentuation"
   "accentus, accentūs" "accent, intonation, accentuation"

   "accidere" "to fall upon, to happen"
   "accidō, accidere, accidī, accāsus" "to fall upon, to happen"

   "acceptiō" "acceptance"
   "acceptiōne" "acceptance"
   "acceptiōnis" "acceptance"
   "acceptiō, acceptiōnis" "acceptance"
   
   "accēpērunt" "they accepted, they received"
   "acceptā" "having been accepted"
   "acceptīs" "having been accepted"
   "acceptō" "having been accepted"
   "acceptus" "having been accepted"
   "accipere" "to take, to grasp, to receive, to accept"
   "acciperet" "he accepted, received"
   "accipiamus" "let us accept"
   "accipiēbant" "they were receiving, they were accepting"
   "accipientēs" "accepting"
   "accipimus" "we accept, we take"
   "accipiunt" "they accept"
   "accēpit" "he received, he grasped"
   "accipiēns" "receiving"
   "accipiō, accipere, accēpī, acceptus" "to take, to grasp, to receive, to accept"
   "accipe"   "accept! receive!"
   "accipite" "accept! receive!"
   "acceptum" "having been received"
   "accēpisset" "he had received"
   "acciperent" "they received"
   "accēpimus" "we received"
   "accipit" "he receives"

   "accurrit" "he runs to"
   "accurrere" "to run to"
   "accurrō, accurrere, accurrī, accursus" "to run to"
   
   "ācrius" "harsher"
   "ācer" "harsh"
   "ācerrimum" "very keen, harsh"
   "ācerrimus" "very keen, harsh"
   "ācer, ācris -e, ācrior -or -us, ācerrimus -a -um" "harsh"

   "acervī" "heap, pile, stack"
   "acervus, acervī" "heap, pile, stack"

   "aciē" "battle line"
   "aciem" "sharpness, battle line"
   "aciēs" "battle line"
   "aciēs, aciēī" "battle line"

   "acquiēscās" "you might rest, relax"
   "acquiēsceret" "he might rest, relax"
   "acquiēscere" "to rest, relax"
   "acquiēscō, acquiēscere, acquiēvī, acquiētus" "to rest, relax"
   
   "acquīsīverō" "I will have acquired, obtained"
   "acquīrere" "to acquire, obtain"
   "acquīrō, acquīrere, acquīsīvī, acquīsītus" "to acquire, obtain"

   "adfuērunt" "they were present"
   "adfuit" "he was present"
   "adesset" "he (might) have been present"
   "affuit" "he was present"
   "adesse" "to be present"
   "assum, adesse, affuī, affuturus" "to be present"
   
   "addidit" "he added"
   "addidērunt" "they added"
   "addit" "he adds"
   "addō, addere, addidī, additus" "to add"

   "adductī" "having been lead, having been persuaded"
   "addūxit" "he lead, he persuaded"
   "addūcere" "to lead, to persuade"
   "addūxērunt" "they lead, persuaded"
   "addūcī" "to be led, persuaded"
   "addūcō, addūcere, addūxī, adductus" "to lead, to persuade"

   "adeptus" "having been gained, overtaking"
   "adipīscī" "to gain, to obtain, to overtake"
   "adipīscor, adipīscī, adeptum" "to gain, to obtain, to overtake"

   "adlātō" "having been brought to"
   "adferrentur" "they might be brought"
   "adferō, adferre, adtulī, adlātus" "to bring to"

   "adficiēbantur" "they were being equipped, they were being affected"
   "adficere" "to equip, to affect"
   "adficiō, adficere, adfēcī, adfectus" "to equip, to affect"

   "adflīctae" "having been striken"
   "adflīctābat" "he was damaging"
   "adflīctāre" "to damage"
   "adflīctō, adflīctāre, adflīctāvī, adflīctātum" "to damage"

   "adgregābat" "he was bringing together"
   "adgregō, adgregāre, adgregāvī, adgregātus" "to bring together"

   "adhibitum" "having been summoned"
   "adhibitus" "having been summoned"
   "adhibēre" "to summon"
   "adhibeō, adhibēre, adhibuī, adhibitus" "to summon"

   "adiacet" "it lies next to"
   "adiacēre" "to lie next to"
   "adiaceō, adiacēre, adiacuī, adiacitus" "to lie next to"

   "adiciēns" "adding, raising"
   "adiciō, adicere, adiēcī, adiectus" "to add, to raise"

   "adimplēbō" "I will fulfill"
   "adimplēre" "to fill up, to fulfill"
   "adimpleō, adimplēre, adimplēvī, adimplētum" "to fill up, to fulfill"

   "adeunt" "they go to"
   "adit" "he goes to"
   "adiēns" "approaching, visiting"
   "adīvit" "he approached, visited"
   "adeō, adīre, adivī(iī), aditus" "to approach, visit"
   
   "aditus" "approach, entrance"
   "aditus, aditūs" "approach, entrance"

   "adiūdicātum" "having been judged"
   "adiūdicō, adiūdicāre, adiūdicāvī, adiūdicātus" "to judge"

   "adiūnctīs" "having been joined"
   "adiungere" "to join"
   "adiungō, adiungere, adiūnxī, adiūnctus" "to join"
   
   "adiūrō" "I adjure, I swear, I charge"
   "adiūrō, adiūrāre, adiūrāvī, adiūrātus" "to adjure, to swear, to charge"
   "adiūtor" "helper, assistant"
   "adiūtor, adiūtōris" "helper, assistant"

   "adiūtōriō" "help, support"
   "adiūtōrium" "help, support"
   "adiūtōrium, adiūtōriī" "help, support"

   "adiūtus" "having been helped"
   "adiuvābō" "I will help"
   "adiūverat" "he had helped"
   "adiuvante" "helping"
   "adiuvet" "may he help"
   "adiūvī" "I helped"
   "adiūvit" "he helped"
   "adiuvāret" "he might help"
   "adiuvāre" "to help"
   "adiuvō, adiuvāre, adiūvī, adiūtus" "to help"

   "administrandī" "attending to"
   "administrārētur" "he (might) have been being attended to"
   "administrāre" "to attend to"
   "administrō, administrāre, administrāvī, administrātus" "to attend to"
   
   "admīrāminī" "admire!"
   "admīrāmur" "we admire"
   "admīror" "to admire"
   "admīror, admīrārī, admīrātus sum" "to admire"

   "admissum" "crime"
   "admissī" "crime"
   "admissō" "crime"
   "admissum, admissī" "crime"

   "admitte" "admit! let in!"
   "admitteretur" "he (might) have been admitted"
   "admittis" "you admit, let in"
   "admittit" "he admits, lets in"
   "admittēris" "you will be admitted, let in"
   "admittere" "to admit, let in"
   "admittō, admittere, admīsī, admissus" "to admit, let in"

   "admōtīs" "having been moved up, brought near"
   "admovēre" "to move up, bring near"
   "admoveō, admovēre, admōvī, admōtus" "to move up, bring near"

   "adolēscentem" "young man"
   "adolēscēns, adolēscentis" "young man"

   "adoptiō" "adoption"
   "adoptiōnis" "adoption"
   "adoptiō, adoptiōnis" "adoption"

   "adōrābunt" "they will adore, they will pray to"
   "adōrāvit" "he adored, he prayed to"
   "adōrō, adōrāre, adōrāvī, adōrātus" "to adore, to pray to"

   "adoriēbantur" "they were attacking"
   "adortī" "having been attacked"
   "adorio, adorīre, -, adorītus" "to attack"

   "adpropinquāvērunt" "they had had approached"
   "adpropinquārent" "they (might) have had approached"
   "adpropinquō, adpropinquāre, adpropinquāvī, adpropinquātus" "to approached"

   "adquiēvit" "he rested, relaxed"
   "adquiēscere" "to rest, relax"
   "adquiēscō, adquiēscere, adquiēvī, adquiētus" "to rest, relax"

   "adquīrere" "to obtain; alternative spelling from acquirō" 
   "adquīrō, adquīrere, adquīsīvī, adquīsītum" "to obtain; alternative spelling from acquirō" 

   "adscendissent" "they (might) have had climbed"
   "adscendere" "to climb"
   "adscendō, adscendere, adscendī, adscēnsus" "to climb"

   "adscīscunt" "they admit, approve, associate"
   "adscīscere" "to admit, to approve, to associate"

   "adūnāvērunt" "united, brought together"
   "adūnō, adūnāre, adūnāvī, adūnātus" "to unite, bring together"

   "advenit" "he comes to"
   "adveniēns" "arriving"
   "advenientibus" "arriving"
   "advenīre" "to arrive"
   "adveniō, advenīre, advēnī, adventus" "to arrive"
   
   "adventum" "arrival, approach"
   "adventū" "arrival, approach"
   "adventus" "arrival, approach"
   "adventus, adventūs" "arrival, approach"

   "adverbia" "adverbs"
   "adverbium" "adverb"
   "adverbiī" "adverb"
   "adverbiīs" "adverb"
   "adverbiō" "adverb"
   "adverbiōrum" "adverb"
   "adverbium, adverbiī" "adverb"

   "adversa" "opposite, hostile"
   "adversus" "opposite, hostile"
   "adversus, adversa, adversum" "opposite, hostile"

   "aedificābitur" "it will be built"
   "aedificārī" "to be built"
   "aedificāta" "having been built"
   "aedificāvērunt" "they built"
   "aedificāvit" "he built"
   "aedificāre" "to build"
   "aedificō, aedificāre, aedificāvī, aedificātus" "to build"

   "aedificia" "buildings"
   "aedificiīs" "buildings"
   "aedificium, aedificiī" "building, structure"

   "aeger" "sick"
   "aegrum" "sick"
   "aegrī" "sick"
   "aegrō" "sick"
   "aegrōs" "sick"
   "aeger, aegra -um, aegrior -or -us, aegerrimus -a -um" "sick"

   "aegrōtantem" "being sick"
   "aegrōtantī"  "being sick"
   "aegrōtat" "he is sick"
   "aegrōtāns" "being sick"
   "aegrōtāre" "to be sick"
   "aegrōtō, aegrōtāre, aegrōtāvī, aegrōtātus" "to be sick"

   "aegritūdine" "illness, sickness"
   "aegritūdō, aegritūdinis" "illness, sickness"

   "aegyptiī" "Egyptian"
   "Aegyptius, Aegyptiī" "Egyptian"
   
   "aequālem" "equal"
   "aequālī" "equal"
   "aequālis" "equal"
   "aequālis, aequāle, aequālior -or -us, aequālissimus -a -um" "equal"

   "aequantur" "they are compared"
   "aequāre" "to compare"
   "aequō, aequāre, aequāvī, aequātus" "to compare"
   
   "aequor" "level surface"
   "aequor, aequōris" "level surface"
   "aequōra" "level surfaces"
   
   "āēr" "air"
   "āēr, āeris" "air"
   "āerem" "air"
   "āeris" "air"

   "aere" "copper"
   "aes" "copper"
   "aes, aeris" "copper"

   "aestimābat" "he was judging"
   "aestimantēs" "judging, valuing, estimating"
   "aestimāre" "to value, estimate, judge"
   "aestimō, aestimāre, aestimāvī, aestimātus" "to value, estimate, judge"

   "aestimātiō" "valuation, estimation"
   "aestimātiōne" "valuation, estimation"
   "aestimātiōnis" "valuation, estimation"
   "aestimātiō, aestimātiōnis" "valuation, estimation"
   
   "aestīvāle" "summer"
   "aestīvō" "summer"
   "aestīvālis, aestīvālis, aestīvāle" "summer"

   "aestās" "summer"
   "aestātis" "summer"
   "aestās, aestātis" "summer"
   
   "aestus" "heat"
   "aestus, aestūs" "heat"
   "aestuābat" "it was boiling"
   "aestuāns" "boiling"
   "aestuantēs" "boiling"
   "aestuāre" "to boil, to be agitated"
   "aestuō, aestuāre, aestuāvī, aestuātus" "to boil, to be agitated"

   "aetās" "lifetime, age"
   "aetāte" "lifetime, age"
   "aetātibus" "ages"
   "aetātis" "lifetime, age"
   "aetās, aetātis" "lifetime, age"
   
   "aeternam" "eternal"
   "aeternum" "eternal"
   "aeternus, aeterna -um, aeternior -or -us, aeternissimus -a -um" "eternal"
   
   "aethera" "sky, heaven, aether"
   "aethēr, aetheris" "sky, heaven, aether"
   
   "Aethiopum" "Ethiopian, black man"
   "Aethiops, Aethiopis" "Ethiopian"

   "afficiātis" "you might equip, affect, weaken"
   "afficere" "to equip, affect, weaken"
   "afficiō, afficere, affēcī, affectus" "to equip, affect, weaken"

   "afflictiō, afflictiōnis" "affliction, pain"
   "afflictiōne" "affliction, pain"

   "afflīgeret" "he was striking, throwing down"
   "afflīgō, afflīgere, afflīxī, afflīctus" "to strike, throw down"

   "africa"  "Africa"
   "Āfrica"  "Africa"
   "Āfricae" "of Africa"
   "africam" "Africa"
   "Africa, Africae" "Africa"

   "āfricō" "southwest, southwest wind"
   "āfricus, āfricī" "southwest, southwest wind"

   "aggerem" "bulwark, rampart"
   "agger, aggeris" "bulwark, rampart"

   "aggrederētur" "they were attacking"
   "aggredio, aggredere, aggressī, aggressus" "to attack"

   "aggredimur" "he attacks"
   "aggredī" "to attack"
   "aggredior, aggredī, aggressus" "to attack"

   "aggregātō" "group together!"
   "aggregō, aggregāre, aggregāvī, aggregātus" "to group, to flock together"

   "agilī" "quick, nimble, agile"
   "agilis, agile, agilior -or -us, agilissimus -a -um" "quick, nimble, agile"
   
   "agitābātur" "to be stirred up"
   "agite" "act! conduct (yourself)!"
   "agitāre" "to act, to put in motion"
   "agitō, agitāre, agitāvī, agitātus" "to act, to put in motion"
   "āgnita" "having been recognized, having been acknowledged"
   "agnōscās" "you might recognize"
   "agnōscerētur" "it was acknowledged"
   "āgnōscis" "you recognize, realize, acknowledge"
   "āgnōscō" "I recognize, realize, acknowledge"
   "āgnōscō, āgnōscere, āgnōvī, āgnitus" "to recognize, to realize, to acknowledge"
   "āgnōvit" "he recognized, he realized"

   "ager" "field"
   "agrī" "fields"
   "agrīs" "fields"
   "agrō" "field"
   "agrōs" "fields"
   "agrum" "field"
   "ager, agrī" "field"

   "agmina" "marching armies"
   "agmen" "marching army"
   "agmine" "marching army"
   "agminī" "marching army"
   "agminis" "marching army"
   "agmen, agminis" "marching army"

   "agnōminis" "surname, nickname"
   "agnōmen, agnōminis" "surname, nickname"
   
   "agnam" "lamb"
   "agna, agnae" "lamb"
   "agnus" "lamb"
   "agnum" "lamb"
   "agnō" "lamb"
   "agnus, agnī" "lamb"

   "agant" "they might be doing"
   "ēgimus" "we conducted, we acted"
   "agit" "he acts, he conducts"
   "agitis" "you act, you conduct"
   "ēgissent" "you might have had conducted"
   "agēbat" "he drove, conducted"
   "agēbant" "they drove, conducted"
   "agēbantur" "they were being driven"
   "agendum" "to be done"
   "agō" "I conduct, act"
   "agerentur" "they were being conducted"
   "agendīs" "conducting"
   "agendō" "conducting, acting, doing"
   "ēgērunt" "they conducted, acted"
   "āctūrōs" "to be conducted"
   "age" "go! do!"
   "agente" "doing, acting"
   "agis" "you do"
   "agere" "to conduct, to act"
   "agō, agere, ēgī, āctus" "to conduct, to act"
   
   "āit" "he said"
   "āiēbat" "he was saying"
   "āiere" "to speak, to affirm"
   "āiunt" "they said"

   "alerētur" "he (might) have nursed, fed"
   "alō, alere, aluī, altus" "to nurse, to feed"
   
   "attulit" "he brought"
   "attulērunt" "they had carried"
   "affer" "bring!"
   "afferrī" "to be brought"
   "allāta" "having been carried"
   "allātīs" "having been carried"
   "afferēbant" "they were bringing in"
   "afferō" "I carry"
   "affert" "they carry"
   "afferre" "to carry"
   "afferō, afferre, attulī, allātus" "to carry"
   
   "āla, ālae" "wing"
   
   "alacritās" "cheerfulness, liveliness"
   "alacritāte" "cheerfulness, liveliness"
   "alacritās, alacritātis" "cheerfulness, liveliness"
   
   "ālae" "wings"
   "ālārum" "of wings"
   "ālās" "wings"

   "alba" "white"
   "albārum" "white"
   "albō" "white"
   "albōs" "white"
   "album" "white"
   "albus" "white"
   "albus, alba -um, albior -or -us, albissimus -a -um" "white"
   "albī" "white"
   "albīs" "white"
   "albae" "white"

   "āles" "bird"
   "āles, ālitis" "bird"

   "alga" "seaweed"
   "algae" "seaweed"
   "algīs" "seaweed"
   "alga, algae" "seaweed"
   
   "alia" "other"
   "aliae" "other"
   "aliārum" "others"
   "aliās" "others"
   "aliōs" "others"
   "aliī" "others"
   "aliīs" "others"
   "alimōnia" "food, nourishment"
   "alimōnia, alimōniae" "food, nourishment"
   "aliō" "other"
   "ālīs" "wings"

   "aliēnigenīs" "strangers, foreigners"
   "aliēnigena, aliēnigenae" "stranger, foreigner"
   
   "aliēnāvit" "he alienated"
   "aliēnārī" "to be alienated"
   "aliēnāre" "to alienate, to give up"
   "aliēnō, aliēnāre, aliēnāvī, aliēnātus" "to alienate, to give up"

   "aliēnum" "strange, unfamiliar"
   "aliēnus, aliēna -um, aliēnior -or -us, alienissimus -a -um" "strange, unfamiliar"

   "alimenta" "food, nourishment, sustenance"
   "alimentīs" "food, nourishment, sustenance"
   "alimentōrum" "of food, nourishment, sustenance"
   "alimentum" "food, nourishment, sustenance"
   "alimentum, alimentī" "food, nourishment, sustenance"

   "aliquantulum" "little, small"
   "aliquantulus, aliquantula, aliquantulum" "little, small"

   "aliōrum" "of others"
   "alium" "other"
   "aliud" "other"
   "alius" "other"
   "alius, alia, aliud" "other"

   "alloquēns" "addressing, speaking to"
   "alloquor, alloquī, allocūtus sum" "to address, to speak to"

   "alluit" "it flows, bathes"
   "alluō, alluere, alluī, -" "to flow, to bathe"
   
   "alligāvissent" "they (might) have had tied"
   "alligāvit" "he tied"
   "alligō, alligāre, alligāvī, alligātus" "to bind, to tie"

   "alma" "nourishing"
   "almus, alma, almum" "nourishing"

   "alpīnārum" "Alpine"
   "Alpīnārum" "Alpine"
   "alpīnus, alpīna, alpīnum" "Alpine"
   "Alpīnus, Alpīna, Alpīnum" "Alpine"

   "Alpibus" "the Alps"
   "Alpis, Alpis" "the Alps"
   
   "altāre" "alter"
   "altāre, altāris" "alter"
   "altāria" "alters"
   
   "alter" "the other"
   "altera" "the other"
   "alterae" "the others"
   "alteram" "the other"
   "alterī" "the other"
   "alterō" "the other"
   "alterōrum" "of others"
   "alterum" "the other"
   "alter, altera, alterum" "the other"

   "altercābātur" "he was disputing"
   "altercor, altercārī, altercātus" "to dispute"

   "altercātiō" "dispute"
   "altercātiōnem" "dispute"
   "altercātiō, altercātiōnis" "dispute"

   "alternē" "alternatively"
   "alternus, alterna, alternum" "alternative"
   
   "altitūdine" "height, depth"
   "altitūdinem" "height, depth"
   "altitūdinis" "height, depth"
   "altitūdō, altitūdinis" "height, depth"
   
   "alta" "height"
   "altae" "high"
   "altās" "high"
   "altō" "height"
   "altum" "height"
   "altī" "height"
   "altius" "higher"
   "altum, altī" "height"
   "altior" "higher"
   "altus" "high"
   "altīs" "highs"
   "altissimam" "highest"
   "altissimō" "highest"
   "altissimus" "highest"
   "altus, alta -um, altior -or -us, altissimus -a -um" "high"

   "alumnī"  "nursling, pupil, foster-son"
   "alumnum" "nursling, pupil, foster-son"
   "alumnus" "nursling, pupil, foster-son"
   "alumnus, alumnī" "nursling, pupil, foster-son"

   "alveō" "cavity, trough"
   "alveum" "cavity, trough"
   "alveus, alveī" "cavity, trough"
   
   "amantissimī" "most loving"
   "amāns, amantis (gen.), amantior -or -us, amantissimus -a -um" "loving"

   "amābat" "he was loving"
   "amābant" "they were loving"
   "amābō" "I will love"
   "amat" "he loves"
   "amāre" "to love"
   "amāret" "he loved"
   "amāvit" "he loved"
   "amāverās" "you had loved"
   "amet" "he might love"
   "amō, amāre, amāvī, amātus" "to love"

   "amārā"  "bitter, harsh"
   "amārīs" "bitter, harsh"
   "amārissimē" "very bitter, harsh"
   "amārus, amāra, amārum" "bitter, harsh"

   "ambītur" "it is incircled"
   "ambīre" "to go around, circle, embrace"
   "ambiō, ambīre, ambīvī, ambītus" "to go around, circle, embrace"

   "ambitū" "edge, orbit, circuit"
   "ambitus" "edge, orbit, circuit"
   "ambitus, ambitūs" "edge, orbit, circuit"

   "ambulā" "walk!"
   "ambulābāmus" "we were walking"
   "ambulābat" "he was walking"
   "ambulābant" "they were walking"
   "ambulantibus" "walking"
   "ambulāns" "walking"
   "ambulāre" "to walk"
   "ambulat" "he walks"
   "ambulant" "they walk"
   "ambulāvērunt" "they walked"
   "ambulāvit" "he walked"
   "ambulandī" "walking"
   "ambulātum" "having walked"
   "ambulō, ambulāre, ambulāvī, ambulātus" "to walk"

   "amīca" "friend"
   "amīcā" "friend"
   "amīcae" "friends"
   "amīce" "friend"
   "amīcī" "friend"
   "amīcīs" "friends"
   "amīcō" "friend"
   "amīcōs" "friends"
   "amīcum" "friend"
   "amīcus" "friend"
   "amīcus, amīcī" "friend"

   "amīcitia" "friendship"
   "amīcitiam" "friendship"
   "amīcitia, amīcitiae" "friendship"

   "āmīserat" "he had lost, dismissed"
   "āmīsit" "he lost, dismissed"
   "āmissīs" "having been lost, dismissed"
   "āmittēs" "you will lose"
   "āmittit" "he lost, dismissed"
   "āmīsisse" "to have lost"
   "āmittere" "to lose, to dismiss"
   "āmittō, āmittere, āmīsī, āmissus" "to lose, to dismiss"
   
   "ammonēbat" "he was admonishing, he was advising"
   "ammōnēbant" "they were admonishing, they were advising"
   "ammonēre" "to admonish, to advise"
   "ammoneō, ammonēre, ammonuī, ammonitus" "to admonish, to advise"

   "amnis" "river"
   "amne" "river"
   "amnem" "river"
   "amnis, amnis" "river"

   "amor" "love"
   "amōre" "with love"
   "amōrem" "love"
   "amōrum" "of loves"
   "amor, amōris" "love"

   "amphibrachibus" "amphibrachs, metricial feet that is short-long-short"
   "amphibrachy" "amphibrach, a metricial foot that is short-long-short"
   "amphibrachyn" "amphibrach, a metricial foot that is short-long-short"
   "amphibrachys" "amphibrach, a metricial foot that is short-long-short"
   "amphibrachyos" "amphibrach, a metricial foot that is short-long-short"
   "amphibrachys, amphibrachyos" "amphibrach, a metricial foot that is short-long-short"

   "amphimacrus" "amphimacer, a metrical foot that is long-short-long"
   "amphimacrus, amphimacrī" "amphimacer, a metrical foot that is long-short-long"
   
   "amphoram" "two-handled earthenware jug"
   "amphora, amphorae" "two-handled earthenware jug"
   
   "amplificatur" "being enlarged"
   "amplificō, amplificāre, amplificāvī, amplificātus" "to enlarge, to amplify"

   "ampla" "large"
   "amplior" "ampler, larger"
   "amplius" "ampler, larger"
   "amplus, ampla -um, amplior -or -us, amplissimus -a -um" "ampler, larger"

   "amputāvit" "he cut off, he shortened"
   "amputāre" "to cut off, to shorten"
   "amputō, amputāre, amputāvī, amputātus" "to cut off, to shorten"
   
   "anachōrita, anachōritae" "hermit, anchorite"
   "anachōritārum" "of anchorites, of hermits"

   "analogia" "analogy, similarity"
   "analogiae" "analogy, similarity"
   "analogiam" "analogy, similarity"
   "analogiārum" "of analogies, similarities"
   "analogiās" "analogies, similarities"
   "analogiīs" "analogies, similarities"
   "analogia, analogiae" "analogy, similarity"

   "anapaestus" "anapest, a metrical foot of short, short, long"
   "anapaestī" "of an anapest, a metrical foot of short, short, long"
   "anapaestīs" "anapests, metrical feet of short, short, long"
   "anapaestō" "anapest, a metrical foot of short, short, long"
   "anapaestōrum" "of anapests, metrical feet of short, short, long"
   "anapaestōs" "anapests, metrical feet of short, short, long"
   "anapaestum" "anapest, a metrical foot of short, short, long"
   "anapaestus, anapaestī" "anapest, a metrical foot of short, short, long"

   "ancilla" "maid-servant"
   "ancillae" "maid-servant's"
   "ancillās" "maid-servants"
   "ancillīs" "maid-servants"
   "ancilla, ancillae" "maid-servant"

   "ancorās" "anchors"
   "ancorīs" "anchors"
   "ancora, ancorae" "anchor"

   "ānfrāctibus" "bends, curves, turnings"
   "ānfrāctus, ānfrāctūs" "bend, curve, turning"

   "angariōs" "public messengers, couriers"
   "angarius" "public messenger, courier"
   "angarius, angariī" "public messenger, courier"
   
   "angelī" "angel"
   "angelīs" "angel"
   "angelō" "angel"
   "angelōs" "angels"
   "angelus" "angel"
   "angelus, angelī" "angel"
   
   "angulōs" "corners, angles"
   "angulus, angulī" "corner, angle"

   "anglōrum" "of the Anglos, Englishmen"
   "Anglus, Anglī" "Anglo, Englishman"
   
   "angelicō" "angelic"
   "angelicus, angelica, angelicum" "angelic"
   
   "angustiam" "small space, narrow passage, being boxed in"
   "angustia" "small space, narrow passage, being boxed in"
   "angustiās" "small spaces, narrow passages, being boxed in"
   "angustia, angustiae" "small space, narrow passage, being boxed in"

   "angustī" "small space, narrow passage, being boxed in"
   "angustōs" "small space, narrow passage, being boxed in"
   "angustum" "small space, narrow passage, being boxed in"
   "angustum, angustī" "small space, narrow passage, being boxed in"
   "angustus" "small space, narrow passage, being boxed in"

   "angusta" "narrow"
   "angustam" "narrow"
   "angustior" "narrower"
   "angustius" "narrower"
   "angustus, angusta -um, angustior -or -us, angustissimus -a -um" "narrow"

   "anhēlābat" "he was gasping, panting, exhaling"
   "anhēlāre" "to pant, gasp, exhale"
   "anhēlō, anhēlāre, anhēlāvī, anhēlātus" "to pant, gasp, exhale"
   
   "anima" "soul, mind, life"
   "animam" "soul, mind, life"
   "animās" "souls, minds, lives"
   "animō" "soul, mind, life"
   "animōs" "souls, minds, lives"
   "anima, animae" "soul, mind, life"
   "animae" "soul, mind, life"
   "animīs" "souls, minds, lives"

   "animal" "animal"
   "animālia" "animals"
   "animal, animālis" "animal"
   
   "animantia" "living, giving life"
   "animāvit" "it animated, inspired"
   "animō, animāre, animāvī, animātus" "to give live, to animate, to revive"

   "animadvertit" "he observes, he observed"
   "animadvertisset" "he (might) have had observed"
   "animadvertere" "to observe"
   "animadvertō, animadvertere, animadvertī, animadversus" "to observe"

   "annālibus" "annals, chronicles"
   "annālis, annālis" "annals, chronicles"
   
   "annī" "year"
   "annīs" "years"
   "annō" "year"
   "annōrum" "of years"
   "annōs" "years"
   "annum" "year"
   "annus" "year"
   "annus, annī" "year"
   
   "annonam" "yearly income"
   "annōnā" "yearly income"
   "annōna, annōnae" "yearly income"

   "annuente" "agreeing"
   "annuit" "he agreed"
   "annuere" "to agree"
   "annuō, annuere, annuī, annūtus" "to agree"

   "annulum" "ring"
   "annulus" "ring"
   "annulus, annulī" "ring"
   
   "antecēdentēs" "preceeding"
   "antecēdēbat" "he was preceeding"
   "antecēdēbant" "they were preceeding"
   "antecēdō, antecēdere, antecessī, antecessum" "to precede"

   "antepaenultimus" "second-to-last"
   "antepaenultima" "second-to-last"
   "antepaenultimum" "second-to-last"
   "antepaenultimus, antepaenultima, antepaenultimum" "second-to-last"
   
   "anteriōrēs" "earlier, previous, former"
   "anteriōribus" "earlier, previous, former"
   "anterior, anterior, anterius" "earlier, previous, former"

   "antiochīa" "Antioch (city in Roman Syria/modern Turkey)"
   "Antiochīa" "Antioch (city in Roman Syria/modern Turkey)"
   "antiochīae" "of Antioch (city in Roman Syria/modern Turkey)"
   "antiochīam" "Antioch (city in Roman Syria/modern Turkey)"
   "Antiochīa, Antiochīae" "Antioch (city in Roman Syria/modern Turkey)"

   "antiochēnam" "Antiochian"
   "antiochēnō" "Antiochian"
   "Antiochēnus, Antiochēna, Antiochēnum" "Antiochian"

   "antīqua" "ancient"
   "antīquam" "ancient"
   "antīquī" "of the ancient"
   "antīquō" "ancient"
   "antīquōrum" "of the ancients"
   "antīquus, antīqua -um, antīquior -or -us, antīquissimus -a -um" "antique"

   "antistes" "overseer"
   "antistitis" "overseer"
   "antistes, antistitis" "overseer"

   "ānulī" "ring's"
   "ānulīs" "rings"
   "ānulō" "ring"
   "ānulōrum" "of rings"
   "ānulōs" "rings"
   "ānulum" "ring"
   "ānulus" "ring"
   "ānulus, ānulī" "ring"

   "ānxietās" "anxiety"
   "ānxietātī" "anxiety"
   "ānxietātēs" "anxiety"
   "ānxietātis" "anxiety"
   "ānxietās, ānxietātis" "anxiety"

   "anxiēns" "worrying"
   "anxiāre" "to worry"
   "anxiō, anxiāre, anxiāvī, anxiātus" "to worry"

   "apertā"  "having been opened"
   "apertam" "having been opened"
   "apertīs" "having been opened"
   "apertō"  "having been opened"
   "apertum" "having been opened"
   "aperiēns" "opening"
   "aperīre" "to open"
   "aperiō, aperīre, aperuī, apertus" "to open"
   "aperiēs" "you will open"
   "aperīrent" "they might open"
   "aperit" "he opens"
   "aperī" "open!"
   "aperītur" "it is opened"
   "apertē" "openly"
   "aperuī" "I opened"

   "apum" "of bees"
   "apis, apis" "bee"
   
   "apostolī" "apostle"
   "apostolum" "apostle"
   "apostolus" "apostle"
   "apostolō" "apostle"
   "apostolōrum" "of apostles"
   "apostolōs" "apostle"
   "apostolus, apostolī" "apostle"

   "apostolicae" "the Pope (medieval usage), bishop, apostle"
   "apostolicō" "the Pope (medieval usage), bishop, apostle"
   "apostolicus" "the Pope (medieval usage), bishop, apostle"
   "apostolicus, apostolicī" "the Pope (medieval usage), bishop, apostle"

   "apostolicās" "apostolic"
   "apostolicus, apostolica, apostolicum" "apostolic"
   
   "appāruisset" "he (might) have had appeared"
   "appārēbat" "he was appearing"
   "appāret" "he appears"
   "appāreō, appārēre, appāruī, appāritus" "to appear" ;; no past perfect participle?
   "appāruērunt" "they appeared"
   "appāruit" "he appeared"
   "appāruerat" "he had appeared"

   "appellābat" "he was calling, he was naming"
   "appellābātur" "he was being called"
   "appellant" "they called"
   "appellantur" "they are called"
   "appellārētur" "it was called"
   "appellatur" "they are called"
   "appellātī" "having been called"
   "appellātus" "having been called"
   "appellāvit" "he called, he named"
   "appellō, appellāre, appellāvī, appellātus" "to call, to name"

   "appellātiō" "name, pronunciation"
   "appellātiōnis" "name, pronunciation"
   "appellātiōne"  "name, pronunciation"
   "appellātiōnem" "name, pronunciation"
   "appellātiōnēs" "names, pronunciations"
   "appellātiōnum" "of names, pronunciations"
   "appellātiōnibus" "names, pronunciations"
   "appellātiō, appellātiōnis" "name, pronunciation"

   "appellātīva" "appellative, common (noun)"
   "appellātīvōrum" "of appellatives, common (nouns)"
   "appellātīvus, appellātīva, appellātīvum" "appellative, common (noun)"

   "appendicēs" "supplements, additions"
   "appendicis" "supplement, addition"
   "appendix"   "supplement, addition"
   "appendix, appendicis" "supplement, addition"

   "appetītus" "appetite"
   "appetītus, appetītūs" "appetite"
   
   "appendentibus" "hanging"
   "appendō, appendere, appendī, appēnsus" "to hang"
   
   "appōnere" "to place, to set before"
   "appōnit" "he places before"
   "apposuit" "he placed, he set before"
   "appōnō, appōnere, apposuī, appositus" "to place, to set before"

   "appreciābantur" "they were valuing, purchasing"
   "appreciāre" "to value, purchase"
   "appreciō, appreciāre, appreciāvī, appreciātus" "to value, purchase"

   "apprehendēns" "seizing"
   "apprehendit" "he seizes, he seized"
   "apprehendēbāmus" "we were seizing"
   "apprehendērunt" "they seized"
   "apprehēnsō" "having been seized"
   "apprehendere" "to seize, to grasp"
   "apprehendō, apprehendere, apprehendī, apprehēnsus" "to seize, to grasp"

   "appretiāvērunt" "they valued, appraised"
   "appretiāre" "to value, appraise"
   "appretiō, appretiāre, appretiāvī, appretiātus" "to value, appraise"

   "appropinquāverat" "he had approached"
   "appropinquāre" "to approach"
   "appropinquō, appropinquāre, appropinquāvī, appropinquātus" "to approach"
   "appropinquābat" "he approached"
   "appropinquābant" "they approached"
   "appropinquant" "they approach"
   "appropinquāvērunt" "they had approached"
   "appropinquāvimus" "we had approached"
   "appropinquāvissem" "I (might) have had approached"
   "appropinquāvisset" "he (might) have had approached"
   "appropinquāvissent" "they (might) have had approached"
   "appropinquāvit" "he approached"
   "appropinquante" "approaching"
   "appropinquāns" "approaching"

   "approximent" "they might approach"
   "approximāre" "to approach"
   "approximō, approximāre, approximāvī, approximātus" "to approach"

   "aptārī" "to be adapted, to be fit in"
   "aptāre" "to adapt, to fit in"
   "aptō, aptāre, aptāvī, aptātus" "to adapt, to fit in"
   
   "aptissimum" "very ready, very apt"
   "aptum" "ready, apt"
   "aptus, apta -um, aptior -or -us, aptissimus -a -um" "ready, apt"
   
   "aqua, aquae" "water"
   "aqua" "water"
   "aquae" "water"
   "aquam" "water"
   "aquās" "water"

   "aquila" "eagle, eagle standard"
   "aquilā" "eagle, eagle standard"
   "aquilae" "eagle, eagle standard"
   "aquilam" "eagle, eagle standard"
   "aquilās" "eagles, eagle standards"
   "aquila, aquilae" "eagle, eagle standard"

   "aquilōne"  "north wind"
   "aquilōnem" "north wind"
   "aquilō, aquilōnis" "north wind"

   "aquītānī" "Aquitanian"
   "aquītānīs" "Aquitanian"
   "Aquītānus, Aquītāna, Aquītānum" "Aquitanian"

   "Aquītānia"  "Aquitaniae, a province in western France"
   "aquītānia"  "Aquitaniae, a province in western France"
   "Aquītāniae" "Aquitaniae, a province in western France"
   "Aquītānia, Aquītāniae" "Aquitaniae, a province in western France"

   "arabās" "Arabs"
   "arabēs" "Arabs"
   "arabum" "of the Arabs"
   "Arabs, Arabis" "Arab"

   "arāta" "having been plowed, having been cultivated"
   "arāre" "to plow, to cultivate"
   "arō, arāre, arāvī, arātus" "to plow, to cultivate"

   "ārās" "altars, refuges"
   "āra, ārae" "altar, refuge"

   "arbiter" "eye-witness, judge"
   "arbiter, arbitrī" "eye-witness, judge"

   "arbitrāris" "you believe, witness, observe"
   "arbitrātur" "he believes, witnesses, observes"
   "arbitrārī" "to believe, witness, observe"
   "arbitror, arbitrārī, arbitrātus" "to believe, witness, observe"

   "arbitriī" "will, arbitration"
   "arbitriō" "will, arbitration"
   "arbitrium" "will, arbitration"
   "arbitrium, arbitriī" "will, arbitration"
   
   "arbor" "tree"
   "arboris" "tree"
   "arbor, arboris" "tree"
   "arbore" "tree"
   "arborem" "tree"
   "arborēs" "trees"
   "arboribus" "trees"
   "arborum" "of trees"
   "arbustam" "planted with trees"
   "arbustus, arbusta, arbustum" "planted with trees"

   "arca" "chest, coffer, coffin, cell"
   "arca, arcae" "chest, coffer, coffin, cell"

   "arcessīvit" "he summoned"
   "arcessītam" "having been summoned, fetched"
   "arcesse" "summon! fetch!"
   "arcessit" "he summons, fetches"
   "arcessere" "to summon, to fetch"
   "arcessō, arcessere, arcessīvī, arcessītus" "to summon, to fetch"

   "archiepiscopus" "archbishop"
   "archiepiscopīs" "archbishops"
   "archiepiscopus, archiepiscopī" "archbishop"

   "arcum" "bow"
   "arcus" "bow"
   "arcus, arcūs" "bow"

   "ārdēbant" "they were burning"
   "ārdēns" "burning"
   "ārdent" "they burn"
   "ardentem" "burning"
   "ardentēs" "burning"
   "ārdēre" "to burn"

   "ardua" "steep, high, lofty, difficult"
   "arduus, ardua -um, arduior -or -us, arduissimus -a -um" "steep, high, lofty, difficult"

   "argentea" "silver"
   "argenteō" "silver"
   "argenteum" "silver"
   "argenteus, argenteī" "silver"
   
   "ārsa" "being burned"
   "ārdente" "burning"
   "ārdeō" "I burn"
   "ārdeō, ārdēre, ārsī, ārsus" "to burn"
   
   "arēna" "sand"
   "arēnam" "sand"
   "arēna, arēnae" "sand"
   
   "argentī" "silver"
   "argentō" "silver"
   "argentum" "silver"
   "argentum, argentī" "silver"

   "arguās" "you might argue, charge"
   "arguere" "to argue, charge"
   "arguō, arguere, arguī, argūtus" "to argue, charge"

   "āriditās"   "dryness, drought"
   "āriditātis" "dryness, drought"
   "āriditāte"  "dryness, drought"
   "āriditās, āriditātis" "dryness, drought"

   "ārida"  "dry"
   "āridam" "dry"
   "āridō" "dry"
   "āridōs" "dry"
   "āridum" "dry"
   "āridus, ārida -um, āridior -or -us, āridissimus -a -um" "dry"

   "ariēs" "ram"
   "arietum" "of rams"
   "ariēs, arietis" "ram"

   "armāmentīs" "equipmento"
   "armāmentum, armāmentī" "equipment"

   "armārī" "to be armed, to be rigged"
   "armātus" "having been armed"
   "armāvit" "he armed, he rigged"
   "armō, armāre, armāvī, armātus" "to arm, to rig"

   "armātī" "armed man, soldier"
   "armātum" "armed man, soldier"
   "armātus, armātī" "armed man, soldier"

   "armiger" "squire, armor-bearer"
   "armigerōs" "squires, armor-bearers"
   "armiger, armigerī" "squire, armor-bearer"
   
   "armīs" "weapons"
   "armōrum" "of weapons"
   "armum, armī" "weapon"

   "arma" "weapons"

   "arripuērunt" "they took hold of, snatched"
   "arripuit" "he took hold of, he snatched"
   "arripere" "to take hold of, to snatch, to arrest"
   "arripiō, arripere, arripuī, arreptus" "to take hold of, to snatch, to arrest"

   "ars" "art, skill"
   "arte" "art, skill"
   "artem" "art, skill"
   "artibus" "arts, skills"
   "artis" "of art"
   "ars, artis" "art, skill"

   "artificēs" "artist, actor"
   "artifex, artificis" "artist, actor"

   "arta" "close, narrow"
   "artōs" "close, narrow"
   "artus, arta -um, artior -or -us, artissimus -a -um" "close, narrow"

   "artus" "joint, limb"
   "artus, artūs" "joint, limb"
   
   "arūrae" "square fields of 100 cubits"
   "arūra, arūrae" "a square field of 100 cubits"

   "arce" "citadel"
   "arcis" "citadel"
   "arx" "citadel"
   "arx, arcis" "citadel"

   "arvīs" "fields, countrysides"
   "arva" "field, country"
   "arva, arvae" "field, country"
   
   "ascendentibus" "ascending"
   "ascendēns" "ascending"
   "ascendente" "ascending"
   "ascendentem" "ascending"
   "ascendentēs" "ascending"
   "ascendere" "to ascend"
   "ascendimus" "we ascend"
   "ascendit" "he ascends, he ascended"
   "ascende" "ascend!"
   "ascendite" "ascend!"
   "ascendēbat" "he was ascending"
   "ascendēbant" "they were ascending"
   "ascendissem" "I (might) have had ascended"
   "ascendissent" "they (might) have had ascended"
   "ascendendum" "ascending"
   "ascendō, ascendere, ascendī, ascēnsus" "to ascend"
   "ascendērunt" "they had ascended"
   "ascēnsus" "having been ascended"
   
   "ascensum" "ascent"
   "ascensus, ascensūs" "ascent"

   "ascēnsiō"    "ascent"
   "ascēnsiōnem" "ascent"
   "ascēnsiōnis" "ascent"
   "ascēnsiō, ascēnsiōnis" "ascent"

   "asellus" "small ass"
   "asellus, asellī" "small ass"

   "asinī" "of an ass"
   "asinō" "ass"
   "asinōrum" "of donkeys or asses"
   "asinōs" "asses"
   "asinus" "ass"
   "asinus, asinī" "ass"

   "asinīnās" "pertaining to donkeys or asses"
   "asinīnus, asinīna, asinīnum" "pertaining to donkeys or asses"

   "aspergētur" "it will be sprinkled"
   "aspergerētur" "it was sprinkled, inflicted"
   "aspergātur" "it is sprinkled, inflicted"
   "aspergō, aspergere, aspersī, aspersus" "to sprinkle, to inflict"

   "aspēxērunt" "they looked at"
   "aspēxissent" "they (might) have had looked at"
   "aspiciēbat" "he was looking at"
   "aspiciēbant" "they were looking at"
   "aspēxit" "he looked at, contemplated"
   "aspicit" "he looks at"
   "aspicite" "look at!"
   "aspiciunt" "they look at"
   "aspice" "look at!"
   "aspicere" "to look at, to contemplate"
   "aspiciō, aspicere, aspēxī, aspectus" "to look at, to contemplate"

   "aspīrante" "breathing, influencing"
   "aspīrāre" "to breath, influence"
   "aspīrō, aspīrāre, aspīrāvī, aspīrātus" "to breath, influence"

   "assīgnāvit" "he assigned"
   "assīgnāre" "to assign"
   "assīgnō, assīgnāre, assīgnāvī, assīgnātus" "to assign"
   
   "asportābant" "they were carrying away"
   "asportārent" "they might carry away"
   "asportō, asportāre, asportāvī, asportātus" "to carry away"

   "assentīre" "to assent, agree"
   "assentiō, assentīre, assēnsī, assēnsus" "to assent, agree"

   "asseruit" "he alleged, claimed, defended"
   "asserō, asserere, asseruī, assertus" "to allege, claim, defend"

   "associentur" "they (might) be joining"
   "associāre" "to join, to associate"
   "associō, associāre, associāvī, associātus" "to join, to associate"
   
   "assūmptiōne" "assumption, taking, receiving"
   "assūmptiō, assūmptiōnis" "assumption, taking, receiving"

   "astābat" "he was standing by"
   "astāre" "to stand by"
   "astō, astāre, astitī, -" "to stand by"

   "astra" "stars"
   "astrum" "star"
   "astrum, astrī" "star"

   "astūtus" "astute, sly"
   "astūtus, astūta -um, astūtior -or -us, astūtissimus -a -um" "astute, sly"

   "ablāta" "things having been carried away"
   "ablātīs" "things having been carried away"

   "atavus" "ancestor"
   "atavus, atavī" "ancestor"

   "āthlēta" "athlete"
   "āthlēta, āthlētae" "athlete"

   "ātriō" "atrium"
   "ātrium" "atrium"
   "ātrium, ātrī" "atrium"

   "attendam" "I will attend"
   "attendendum" "attending"
   "attendere" "to attend"
   "attendō, attendere, attendī, attentus" "to attend"

   "attigerit" "he might have touched, bordered, reached"
   "attingēbat" "they were touching"
   "attingit" "it touches, it borders"
   "attingō, attingere, attigī, attāctus" "to touch, to border on, to reach"

   "attrahere" "to draw, attract"
   "attrahō, attrahere, attrāxī, attractus" "to draw, attract"

   "aucta" "increased"
   "auctus, aucta, auctum" "increased"

   "auctōre"  "authority"
   "auctōrem" "authority"
   "auctōrēs" "authorities"
   "auctōribus" "authorities"
   "auctor, auctōris" "authority"
   
   "auctōritāte" "authority"
   "auctōritās, auctōritātis" "authority"

   "auctibus" "growth, increase"
   "auctus, auctūs" "growth, increase"

   "audācis" "bold, daring"
   "audāx" "bold, daring"
   "audāx, audācis (gen.), audācior -or -us, audācissimus -a -um" "bold, daring"

   "audēbit" "he will dare"
   "ausam" "having been dared"
   "audente" "daring"
   "audērent" "they had dared"
   "audēret" "he might dare"
   "audeat" "he might dare"
   "audēbāmus" "we were daring"
   "audēbat" "he was daring"
   "audēbant" "they were daring"
   "audet" "he dares"
   "audent" "they dare"
   "audēre" "to dare"
   "audeō, audēre, ausus sum" "to dare"

   "audiēns" "hearing"
   "audientēs" "hearing"
   "audītis" "you hear"
   "audit" "he hears"
   "audiunt" "they hear"
   "audīvērunt" "they heard"
   "audiēbant" "they were hearing"
   "audīvimus" "we heard"
   "audīre" "to hear"
   "audīvissem" "I (might) have had heard"
   "audīvisset" "he (might) have had heard"
   "audīvissent" "they (might) have had heard"
   "audīvit" "he heard"
   "audītā" "having been heard"
   "audiō" "I hear"
   "audīvī" "I heard"
   "audī" "to be heard"
   "audīrī" "to be heard"
   "audiō, audīre, audīvī, audītum" "to hear"

   "audītō" "having been heard"
   "audītus" "listening, hearing"
   "audītus, audītūs" "listening, hearing"

   "abstulimus" "we carried away"
   "abstulisset" "he (might) have carried away"
   "abstulistī" "you carried away"
   "abstulit" "he carried away"
   "abstulērant" "they had carried away"
   "abstulērunt" "they carried away"
   "auferēbant" "they were carrying away"
   "auferrētis" "carry yourselves away"
   "auferre" "to carry away, to remove"
   "auferō, auferre, abstulī, ablātus" "to carry away, to remove"

   "aufugit" "he flees"
   "aufugiō, aufugere, aufūgī, aufugitūrus" "to flee"

   "auget" "it increases"
   "augēbantur" "they were being increased"
   "augēre" "to increase, augment"
   "augeō, augēre, auxī, auctus" "to increase, augment"

   "Augustī" "august, venerable"
   "augustus, augusta, augustum" "august, venerable"

   "aula" "court"
   "aulae" "court"
   "aulam" "court"
   "aula, aulae" "court"

   "aulaea" "canopies, curtains"
   "aulaeum, aulaeī" "canopy, curtain"

   "auream" "golden"
   "aureōs" "golden"
   "aureum" "golden"
   "aureus" "golden"
   "aureus, aurea, aureum" "golden"

   "aurem" "ear"
   "aurēs" "ears"
   "auribus" "ears"
   "auris, auris" "ear"

   "aurīga"  "charioteer"
   "aurīgae" "charioteer"
   "aurīga, aurīgae" "charioteer"
   
   "aurōra" "dawn, sunrise"
   "aurōram" "dawn, sunrise"
   "aurōra, aurōrae" "dawn, sunrise"

   "aurō" "gold"
   "aurum" "gold"
   "aurī" "of gold"
   "aurum, aurī" "gold"

   "auscultāns" "listening, overhearing, obeying"
   "auscultāre" "to listen, to overhear, to obey"
   "auscultō, auscultāre, auscultāvī, auscultātus" "to listen, to overhear, to obey"

   "austrō" "south"
   "austrum" "south wind"
   "auster, austrī" "south wind"
   "austrālem" "southern"
   "austrālis, austrālis, austrāle" "southern"
   
   "ausus" "daring"
   "ausūs" "daring"
   "ausus, ausūs" "daring"
   "ausī" "daring, risking"
   
   "autumnālī" "autumnal"
   "autumnālis, autumnālis, autumnāle" "autumnal"

   "auxiliandī" "helping"
   "auxiliāre" "to help"
   "auxiliō, auxiliāre, auxiliāvī, auxiliātus" "to help"

   "auxiliō" "help, aid"
   "auxilium" "help, aid"
   "auxilium, auxiliī" "help, aid"
   
   "avem" "bird"
   "avis" "bird"
   "avis, avis" "bird"
   "avium" "of birds"
   "avibus" "birds"

   "avidē" "greedily, eagerly, ardently"
   "avidus, avida -um, avidior -or -us, avidissimus -a -um" "greedy, eager, ardent"

   "avum" "forefather, godfather"
   "avus" "forefather, godfather"
   "avus, avī" "forefather, godfather"

   "axe" "axis"
   "axis" "axis"
   "axis, axis" "axis"})
