(ns whitakers-clj.dict-n)

(def dict-n
  {"nactus" "having been obtained"
   "nancīscor, nancīscī, nactus sum" "to obtain"
   
   "nārēs" "noses, nostrils"
   "nāris, nāris" "nose, nostril"
   "nāribus" "nostrils"
   
   "nārrā" "narrate!"
   "nārrat" "he tells, narrates"
   "nārrātē" "narrate!"
   "nārrāns" "narrating"
   "nārrāvit" "he told"
   "nārrāre" "to narrate, to tell about"
   "nārrō, nārrāre, nārrāvī, nārrātus" "to narrate, to tell about"

   "nāsum" "nose"
   "nāsus" "nose"
   "nāsus, nāsī" "nose"
   
   "nātū" "birth"
   "nātus" "having been born"
   "nātum" "having been born"
   "nāscitur" "he is being born"
   "nāscerētur" "he (perhaps) will be born"
   "nāscētur" "he will be born"
   "nāscor, nāscī, nātus sum" "to be born"
   "nāscī" "to be born"
   "nātīs" "having been born"

   "natābat" "he was swimming"
   "natābant" "they were swimming"
   "natandō" "swimming"
   "natat" "he swims"
   "natant" "they swim"
   "natantium" "swimming"
   "natāvit" "he swam"
   "natāre" "to swim"
   "natō, natāre, natāvī, natātus" "to swim"

   "nātiōne" "race, tribe, nation"
   "nātiōnēs" "races, tribes, nations"
   "nātiōnibus" "race, tribe, nation"
   "nātiōnum" "of races, tribes, nations"
   "nātiō, nātiōnis" "race, tribe, nation"

   "nātāle" "birthday"
   "nātālem" "birthday"
   "nātālis" "birthday"
   "nātālis, nātālis" "birthday"
   "nātīvitās" "birth, nativity"
   "nātīvitās, nātīvitātis" "birth, nativity"
   "nātīvitāte"  "birth, nativity"
   "nātīvitātem" "birth, nativity"
   "nātīvitātis" "birth, nativity"

   "nātūra" "nature"
   "nātūra, nātūrae" "nature"

   "nātūrālī" "natural"
   "nātūrālis, nātūrālis, nātūrāle" "natural"

   "naufragiō" "shipwreck"
   "naufragium" "shipwreck"
   "naufragium, naufragiī" "shipwreck"

   "nautīs" "sailors"
   "nauta" "sailor"
   "nauta, nautae" "sailor"

   "nāve" "boat"
   "nāvem" "boat"
   "nāvēs" "boats"
   "nāvibus" "boats"
   "nāvicula" "small boat"
   "nāviculae" "small boat"
   "nāviculam" "small boat"
   "nāvicula, nāviculae" "small boat"
   "nāvī" "boat"
   "nāvium" "of boats"
   "nāvim" "boat"
   "nāvis" "boat"
   "nāvis, nāvis" "boat"
   
   "nāvigā" "sail (imperative)"
   "nāvigābam" "I was sailing"
   "nāvigābant" "they were sailing"
   "nāvigābat" "he was sailing"
   "nāvigābimus" "we will sail"
   "nāvigābitis" "you will sail"
   "nāvigandō" "sailing"
   "nāvigantibus" "navigating"
   "nāvigāre" "to sail"
   "nāvigāvī" "I sailed"
   "nāvigō, nāvigāre, nāvigāvī, nāvigātus" "to sail, to navigate"
   "nāvigēmus" "let us sail"
   "nāvigārent" "they sailed"
   "nāvigāvit" "he sailed"
   "nāvigāvērunt" "they sailed"
   "nāvigāvisse" "to have sailed"
   "nāvigāvisset" "he (might) have navigated"
   "nāvigāvissent" "they (might) have navigated"
   "nāvigandum" "sailing, navigating"
   "nāvigārī" "to be sailed"
   "nāvigantēs" "sailing"

   "nāvigia" "vessels, ships, sailings, navigation"
   "nāvigiī" "vessel, ship, sailing, navigation"
   "nāvigium" "vessel, ship, sailing, navigation"
   "nāvigium, nāvigi(ī)" "vessel, ship, sailing, navigation"

   "nebula"  "fog, cloud"
   "nebulae" "fog, cloud"
   "nebulam" "fog, cloud"
   "nebula, nebulae" "fog, cloud"

   "necāvērunt" "they killed, destroyed"
   "necāvit" "he killed, destroyed"
   "necāre" "to kill, destroy"
   "necō, necāre, necāvī, necātus" "to kill, destroy"
   
   "necesse" "necessary"
   "necesse, undeclined" "necessary"

   "necessāriae" "necessary"
   "necessāriō" "necessary"
   "necessārius, necessāria, necessārium" "necessary"
   
   "necessitās" "necessity"
   "necessitāte" "necessity"
   "necessitātis" "necessity"
   "necessitātem" "necessity"
   "necessitās, necessitātis" "necessity"

   "nefanda" "impious, wicked"
   "nefandum" "impious, wicked"
   "nefandus, nefanda, nefandum" "impious, wicked"

   "negāvit" "he denied, refused"
   "negāre" "to deny, to refuse"
   "negō, negāre, negāvī, negātus" "to deny, to refuse"

   "negligentiam" "neglect, carelessness, coldness, disrespect"
   "negligentia, negligentiae" "neglect, carelessness, coldness, disrespect"

   "neglegenda" "disregarding"
   "neglegere" "to disregard"
   "neglegō, neglegere, neglēxī, neglēctus" "to disregard"

   "negōtiātiō" "business"
   "negōtiātiōnis" "business"
   "negōtiātiō, negōtiātiōnis" "business"
   
   "negōtiātor" "merchant, trader"
   "negōtiātor, negōtiātōris" "merchant, trader"

   "nēmine" "no one"
   "nēminī" "no one"
   "nēmō" "no one"
   "nēmō, nēminis" "no one"

   "nemoribus" "woods, forests"
   "nemus" "wood, forest"
   "nemus, nemoris" "wood, forest"
   
   "nemorōsam" "woody, shaded"
   "nemorōsus" "woody, shaded"
   "nemorōsus, nemorōsa, nemorōsum" "woody, shaded"

   "nepōs"   "grandson"
   "nepōtis" "grandson"
   "nepōs, nepōtis" "grandson"

   "nēquissimus" "very good-for-nothing"
   "nēquam" "good-for-nothing"

   "nequeō" "I am unable"
   "nequībat" "he was unable"
   "nequībant" "they were unable"
   "nequīmus" "we are unable"
   "nequīvērunt" "they were unable"
   "nequīvimus" "we were unable"
   "nequīvit" "he was unable"
   "nequeunt" "they are unable"
   "nequīrent" "they might have been unable"
   "nequeō, nequīre, nequivī(iī), nequitus" "to be unable"

   "nescīmus" "we do not know"
   "nesciō" "I don't know"
   "nescīvit" "he didn't know"
   "nesciērunt" "they didn't know"
   "nesciō, nescīre, nescīvī, nescītus" "to not know"

   "neuter"  "neither"
   "neutrum" "neither"
   "neuter, neutra, neutrum" "neither"

   "necis" "death, slaughter"
   "nex, necis" "death, slaughter"

   "nīcomediam" "Nicomedia"
   "Nīcomedia" "Nicomedia"
   "Nīcomedia, Nīcomediae" "Nicomedia"

   "nīdī" "nests"
   "nīdīs" "nests"
   "nīdō" "nest"
   "nīdōs" "nests"
   "nīdum" "nest"
   "nīdus" "nest"
   "nīdus, nīdī" "nest"

   "nigra" "black"
   "nigrum" "black"
   "niger, nigra, nigrum" "black"

   "nihilī" "nothing"
   "nihilō" "nothing"
   "nihilum" "nothing"
   "nihilum, nihilī" "nothing"

   "nimiam" "too much, superabundance"
   "nimiīs" "too much, superabundance"
   "nimium" "too much, superabundance"
   "nimium, nimiī" "too much, superabundance"

   "nitet" "it shines, glitters, thrives"
   "niteō, nitēre, nituī, -" "to shine, glitter, thrive"

   "nitida" "shining, bright"
   "nitidīs" "shining, bright"
   "nitidus, nitida, nitidum" "shining, bright"

   "nīsōs" "having advanced, pressed upon"
   "nītor, nītī, nīsus sum" "to advance, press upon"

   "niveō" "snowy white"
   "niveus, nivea, niveum" "snowy white"

   "nivium" "of snow"
   "nix" "snow"
   "nix, nivis" "snow"

   "nōbile" "noble, famous, high-born"
   "nōbilibus" "noble, famous, high-born"
   "nōbilis" "noble, famous, high-born"
   "nōbilissimōs" "very noble, famous, high-born"
   "nōbilissimum" "very noble, famous, high-born"
   "nōbilissimus" "very noble, famous, high-born"
   "nōbilis, nōbilis, nōbile" "noble, famous, high-born"

   "nōbilitās" "celebrity, fame, renown"
   "nōbilitātis" "celebrity, fame, renown"
   "nōbilitās, nōbilitātis" "celebrity, fame, renown"

   "nocet" "it harms"
   "nocēret" "he (might) have harmed"
   "nocērī" "to be harmed"
   "nocuit" "he harmed"
   "nocendī" "harming"
   "nocēre" "to harm"
   "noceō, nocēre, nocuī, nocitus" "to harm"

   "nocumenta" "harms"
   "nocumentum" "harm"
   "nocumentum, nocumentī" "harm"

   "nōmina" "names"
   "nōmine" "name"
   "nōminibus" "names"
   "nōmen" "name"
   "nōmen, nōminis" "name"

   "nōminat" "it names"
   "nōminābātur" "he was named, called"
   "nōminor" "I am called"
   "nōmināre" "to name"
   "nōminō, nōmināre, nōmināvī, nōminātus" "to name"
   
   "noster" "our"
   "noster, nostra, nostrum" "our"
   "nostra" "our"
   "nostrās" "our"
   
   "nocte" "night"
   "noctēs" "nights"
   "noctem" "night"
   "noctīs" "nights"
   "noctium" "of nights"

   "nocturnīs" "nocturnal"
   "nocturnus, nocturna, nocturnum" "nocturnal"

   "nōlēbant" "they were not wanting"
   "nōluērunt" "they didn't want"
   "nōlēmus" "we won't want"
   "nōlentēs" "not wanting"
   "nōlēns" "not wanting"
   "nōlō" "I don't want"
   "nōluissent" "they might have been unwilling"
   "nōluit" "he didn't want"
   "nōllem" "I might not have wanted"
   "nōlō, nōlle, nōluī, -" "to not want"

   "nōnāgēnāriīs" "ninety years"
   "nōnāgēnārius" "ninety years old"
   "nōnāgīnta, nōnāgēsīmus -a -um, nōnāgeni -ae -a, nonagie (n)s" "ninety years old"

   "notanda" "writing, observing"
   "notō, notāre, notāvī, notātus" "to write, to observe"

   "notārium" "stenographer, person who writes down another's dictation"
   "notārius" "stenographer, person who writes down another's dictation"
   "notārius, notāriī" "stenographer, person who writes down another's dictation"

   "nōta" "known"
   "nōtīs" "known"
   "nōtissimīs" "very well known"
   "nōtus" "known"
   "nōtus, nōta -um, nōtior -or -us, nōtissimus -a -um" "known"

   "novācula" "sharp knife, dagger"
   "novācula, novāculae" "sharp knife, dagger"

   "novem" "nine"

   "Novembris" "of November"
   "novembris" "of November"
   "November, Novembris, Novembre" "November"
   "november, novembris, novembre" "November"

   "nova" "new, inexperienced"
   "novī" "new, inexperienced"
   "novissimē" "very new, very inexperienced"
   "novissimō"  "very new, very inexperienced"
   "novissimum" "very new, very inexperienced"
   "novīs" "new, inexperienced"
   "novum" "new, inexperienced"
   "novō" "new, inexperienced"
   "novus" "new, inexperienced"
   "novus, nova -um, novior -or -us, novissimus -a -um" "new, inexperienced"

   "novitāte" "novelty"
   "novitātis" "novelty"
   "novitās, novitātis" "novelty"

   "nōvērunt" "they learned, knew"
   "nōvistī" "you learned"
   "nōvimus" "we learned"
   "nōscō, nōscere, nōvī, nōtus" "to learn"
   
   "noctibus" "nights"
   "nox" "night"
   "nox, noctis" "night"

   "noxium" "harmful"
   "noxius, noxia, noxium" "harmful"
   
   "nūbēs" "cloud"
   "nūbe" "cloud"
   "nūbis" "cloud"
   "nūbēs, nūbis" "cloud"

   "nūbila" "clouds"
   "nūbilum, nūbilī" "clouds"
   
   "nūbilās" "cloudy"
   "nūbilus, nūbila, nūbilum" "cloudy"

   "nūditās"   "nudity, nakedness"
   "nūditātēs" "nudity, nakedness"
   "nūditātis" "nudity, nakedness"
   "nūditās, nūditātis" "nudity, nakedness"
   
   "nūda" "naked"
   "nūdīs" "naked"
   "nūdōs" "naked"
   "nūdum" "naked"
   "nūdus" "naked"
   "nūdus, nūda, nūdum" "naked"

   "nūgīs" "jokes, trifles"
   "nūga, nūgae" "joke, trifle"
   
   "nūlla" "no, none, not any"
   "nūllae" "no, none, not any"
   "nūllam" "no, none, not any"
   "nūllās" "no, none, not any"
   "nūllī" "no, none, not any"
   "nūllīs" "no, none, not any"
   "nūllō" "no, none, not any"
   "nūllōs" "no, none, not any"
   "nūllum" "no, none, not any"
   "nūllus" "no, none, not any"
   "nūllus, nūlla, nūllum (gen -ius)" "no, none, not any"

   "numerā" "count! number!"
   "numerat" "he counts"
   "numerārī" "to be counted, numbered"
   "numerāre" "to number, count"
   "numerō, numerāre, numerāvī, numerātus" "to number, count"

   "numerōsās" "numerous"
   "numerōsus" "numerous"
   "numerōsus, numerōsa -um, numerōsior -or -us, numerōsissimus -a -um" "numerous"

   "numerō"  "number, division, troop"
   "numerum" "number, division, troop"
   "numerus" "number, division, troop"
   "numerus, numerī" "number, division, troop"

   "nummīs" "coins"
   "nummōrum" "of coins"
   "nummōs" "coins"
   "nummus, nummī" "coin"

   "nūnciīs" "messengers"
   "nūncius, nūnci(i)" "messenger"

   "nūntiat" "he announces"
   "nūntiātum" "having been announced"
   "nūntiāvērunt" "they announced"
   "nūntiāvit" "he announced"
   "nūntiāret" "he announced"
   "nūntiāre" "to announce"
   "nūntiō, nūntiāre, nūntiāvī, nūntiātus" "to announce"

   "nūntiī" "message, news"
   "nūntiīs" "messages, news"
   "nūntiō" "message, news"
   "nūntium, nūntiī" "message, news"

   "nūntiōs" "messengers"
   "nūntium" "messenger"
   "nūntius" "messenger"
   "nūntius, nūntiī" "messenger"

   "nurus" "young woman, daughter-in-law"
   "nurus, nurūs" "young woman, daughter-in-law"

   "nūtrīmenta" "nourishments"
   "nūtrīmentō" "nourishment"
   "nūtrīmentīs" "nourishments"
   "nūtrīmentum, nūtrīmentī" "nourishment"

   "nūtrit" "it nourishes"
   "nūtrītus" "having been nourished"
   "nūtrīvit" "he nourished"
   "nūtriō, nūtrīre, nūtrīvī, nūtrītus" "to nourish"

   "nūtū" "command, will, pleasure"
   "nūtus" "command, will, pleasure"
   "nūtus, nūtūs" "command, will, pleasure"

   "nucem" "nut"
   "nucēs" "nuts"
   "nux, nucis" "nut"
   })
