(ns whitakers-clj.dict-d)

(def dict-d
  {"daemōn" "demon"
   "daemōnem" "demon"
   "daemōnēs" "demons"
   "daemōnibus" "demons"
   "daemōnum" "of demons"
   "daemōn, daemōnis" "demon"

   "daemoniaca" "demonic"
   "daemoniacus, daemoniaca, daemoniacum" "demonic"
   
   "dalmaticīs" "deacon's vestmests"
   "dalmatica"  "deacon's vestmests"
   "dalmaticae" "deacon's vestmests"
   "dalmatica, dalmaticae" "deacon's vestmests"

   "damnantur" "they are condemned"
   "damnatur" "he is condemned"
   "damnātus" "having been condemned"
   "dampnāre" "to condemn"
   "damnō, damnāre, damnāvī, damnātus" "to condemn"

   "damnāta" "condemned"
   "damnātum" "condemned"
   "damnātus, damnāta, damnātum" "condemned"

   "damna" "damages, injuries"
   "damnī" "damage, injury"
   "damnum" "damage, injury"
   "damnum, damnī" "damage, injury"

   "dampna" "damages, injuries"
   "dampnum, dampnī" "damage, injury"

   "dāniēle" "Daniel"
   "dāniēlem" "Daniel"
   "Dāniēl, Dāniēlis" "Daniel"

   "dānōrum: of the Danes; plural masculine genitive from Dānus, Dānī"
   "Dānus: the Danes; singular masculine nominative from Dānus, Dānī"

   "dā" "give!"
   "darī" "to be given"
   "dans" "giving"
   "dant" "they give"
   "dat" "he gives"
   "datūrum" "will be giving"
   "datūrōs" "to be given"
   "data" "things given"
   "dētur" "is given"
   "dederant" "they had given"
   
   "datō" "gift"
   "datum" "gift"
   "datum, datī" "gift"

   "dēbellandum" "fighting out"
   "dēbellāre" "to fight out"
   "dēbellō, dēbellāre, dēbellāvī, dēbellātus" "to fight out"
   
   "dēbēmus" "we should, we aught"
   "dēbent" "they should"
   "dēbeō" "I should"
   "dēbēs" "you should"
   "dēbet" "he should"
   "dēbētis" "you should"
   "dēbērent" "they should"
   "dēbēret" "he should"
   "dēbēre" "to owe, to ought"
   "dēbeō, dēbēre, dēbuī, dēbitus" "to owe, to ought"
   
   "dēbitum" "debt, due, duty"
   "dēbitum, dēbitī" "debt, due, duty"
   
   "dēbuissent" "they (might) have had owed"
   "dēbuissēmus" "we (might) have had owed"
   
   "decānus" "dean, chief"
   "decānus, decānī" "dean, chief"

   "decas" "decade"
   "decadis" "of the decade"
   "decas, decadis" "decade"

   "dēcesserat" "he had departed, abandoned"
   "dēcēdere" "to depart, abandon"
   "dēcēdō, dēcēdere, dēcessī, dēcessus" "to depart, abandon"

   "decemnovennalem" "nineteen-year cycle; singular accusative adjective from decemnovennalis"
   "decemnovennalēs" "nineteen-year cycle; plural nominative adjective from decemnovennalis"
   "decemnovennalis" "nineteen-year cycle; singular nominative adjective from decemnovennalis"

   "dēceptus" "having been cheated, deceived"
   "dēcipere" "to cheat, deceive"
   "dēcipiō, dēcipere, dēcēpī, dēceptus" "to cheat, deceive"

   "dēclīnābat" "he diverted, distracted"
   "dēclīnāre" "to divert, to distract"
   "dēclīnō, dēclīnāre, dēclīnāvī, dēclīnātus" "to divert, to distract"

   "dēclīvī" "slopes"
   "dēclīvum, dēclīvī" "slope"

   "dēcrēvī" "I decided"
   "dēcrēvimus" "we decided"
   "dēcrēvit" "he decided"
   "dēcernō, dēcernere, dēcrēvī, dēcrētus" "to decide"

   "dēcessum" "departure"
   "dēcessus, dēcessūs" "departure"

   "decēbat" "it was fitting"
   "decet" "it is fitting"
   "decet, decēre, decuit, -" "it is fitting"
   
   "dēclārābitur" "he will announce"
   "dēclārō, dēclārāre, dēclārāvī, dēclārātus" "to announce"

   "dēcoquēbant" "they were boiling, stewing"
   "dēcoquere" "to boil, stew"
   "dēcoquō, dēcoquere, dēcoxī, dēcoctus" "to boil, stew"

   "decōra" "elegance, beauty"
   "decōris" "elegance, beauty"
   "decor, decōris" "elegance, beauty"
   
   "dēcrēscant" "they (might) be decreasing"
   "dēcrēvērunt" "they decreased"
   "dēcrēscit" "it decreased"
   "dēcrēscō, dēcrēscere, dēcrēvī, dēcrētus" "to decrease, to diminish"
   
   "dēcrētum" "decree, decision"
   "dēcrētum, dēcrētī" "decree, decision"

   "decus" "honor distinction, glory"
   "decus, decoris" "honor distinction, glory"

   "dēdecore" "disgrace, shame"
   "dēdecus" "disgrace, shame"
   "dēdecus, dēdecoris" "disgrace, shame"

   "dēditiō"    "surrender, capitulation"
   "dēditiōnem" "surrender, capitulation"
   "dēditiōnis" "surrender, capitulation"
   "dēditiō, dēditiōnis" "surrender, capitulation"

   "dēdūcēbat" "he escorted, removed"
   "dēdūcēbant" "they escorted, removed"
   "dēdūxit" "he escorted, he removed"
   "dēdūcunt" "they lead down, escort, remove"
   "dēdūcerēmus" "we had lead down, escorted, removed"
   "dēdūcere" "to escort, to remove"
   "dēducta" "having been escorted, removed"
   "dēductī" "having been escorted, removed"
   "dēdūceret" "he carried away"
   "dēductīs" "having been led away"
   "dēdūcī" "to be removed, escorted, led away"
   "dēdūcō, dēdūcere, dēdūxī, dēductus" "to escort, to remove"

   "dederit" "he will give"
   "dedērunt" "they gave"

   "dēdidit" "he surrendured, gave up"
   "dēdita" "having been surrendured"
   "dēdō, dēdere, dēdidī, dēditum" "to surrender"

   "dēfectiōne" "defection, revolt"
   "dēfectiōnis" "defection, revolt"
   "dēfectiō, dēfectiōnis" "defection, revolt"

   "dēerit" "it will lack"
   "dēerat" "it lacked"
   "dēerant" "they lacked"
   "dēfuit" "he lacked"
   "dēesset" "he lacked"
   "dēessent" "they lacked"
   "dēesse" "to lack"
   "dēsum, dēesse, dēfuī, dēfutūrus" "to lack"

   "dēfendit" "he defends"
   "dēfendēbat" "he was defending"
   "dēfendēbant" "they were defending"
   "dēfendentēs" "defending"
   "dēfendēs" "you will defend"
   "defendet" "he will defend"
   "dēfendere" "to defend"
   "dēfenderet" "he was defending"
   "dēfendis" "you defend"
   "dēfendistī" "you defended"
   "dēfendō" "I defend"
   "dēfendant" "they might defend"
   "dēfendendum" "defending"
   "dēfendō, dēfendere, dēfendī, dēfēnsus" "to defend"
   
   "dēficiō, dēficere, dēfēcī, dēfectus" "to run short, to lack"
   "dēfēnsor" "defender, protector"
   "dēfēnsor, dēfēnsōris" "defender, protector"
   "dēfīnīvit" "he defined, he limited"
   "dēfīniō, dēfīnīre, dēfīnīvī, dēfīnītus" "to define, to limit"
   
   "dēfōrmem" "deformed"
   "dēfōrmis" "deformed"
   "dēfōrmō, dēfōrmāre, dēfōrmāvī, dēfōrmātus" "deformed"
   
   "dēfūnctō" "dead"
   "dēfūnctus" "dead"
   "dēfūnctus, dēfūncti" "dead"

   "dēgere" "to spend, carry on"
   "dēgō, dēgere, dēgī, -" "to spend, carry on"
   
   "dēglutīre" "to swallow"
   "dēglutīvit" "I swallowed"
   "dēglutiō, dēglutīre, dēglutīvī, dēglutītus" "to swallow"

   "dēgunt" "they spend"
   "dēgō, dēgere, dēgī" "to spend"

   "dēiēcerat" "he had thrown down, overthrew"
   "dēiēcērunt" "they threw down, overthrew"
   "dēicientēs" "throwing down"
   "dēiciet" "he will overthrow"
   "dēicerentur" "they (might) have been throwing down"
   "dēicere" "to throw down"
   "dēiciō, dēicere, dēiēcī, dēiectus" "to throw down"

   "dēlectantur" "they are delighted"
   "dēlectāre" "to delight"
   "dēlectō, dēlectāre, dēlectāvī, dēlectātus" "to delight"

   "dēlēbuntur" "they will be erased"
   "dēlērentur" "it was erased"
   "dēlēre" "to erase"
   "dēleō, dēlēre, dēlēvī, dēlētus" "to erase"

   "dēlīberanda"  "deliberating"
   "dēlīberandum" "deliberating"
   "dēlīberāre" "to deliberate"
   "dēlīberō, dēlīberāre, dēlīberāvī, dēlīberātus" "to deliberate"

   "dēlīberātiō" "deliberation"
   "dēlīberātiōne" "deliberation"
   "dēlīberātiōnis" "deliberation"
   "dēlīberātiō, dēlīberātiōnis" "deliberation"
   
   "dēliciārum" "of delights"
   "dēliciae, dēliciārum" "delights"
   "dēliciōsa" "delicious"
   "dēliciōsam" "delicious"
   "dēliciīs" "delicious"
   "dēliciōsus, dēliciōsa, dēliciōsum" "delicious"

   "dēligātae" "having been tied, fastened"
   "dēligāre" "to tie, to fasten"
   "dēligō, dēligāre, dēligāvī, dēligātus" "to tie, to fasten"

   "dēlēcta" "having been chosen"
   "dēligitur" "it is chosen"
   "dēligere" "to choose, to select"
   "dēligō, dēligere, dēlēgī, dēlēctus" "to choose, to select"

   "dēlictīs" "having been failed, offended"
   "dēlinquere" "to fail, offend"
   "dēlinquō, dēlinquere, dēlīquī, dēlictus" "to fail, offend"

   "dēlūdentēs" "deceiving"
   "dēlūdere" "to deceive"
   "dēlūdō, dēlūdere, dēlūsī, dēlūsus" "to deceive"

   "dēmēns" "having been taken away"
   "dēmō, dēmere, dēmpsī, dēmptus" "to take away"

   "dēmersī" "I submerged, I sank"
   "dēmersus" "having been submerged, sunk"
   "dēmergō, dēmergere, dēmersī, dēmersus" "to submerge, to sink"

   "dēmissī" "having dropped, slipped out"
   "dēmittere" "to drop, slip out"
   "dēmittō, dēmittere, dēmīsī, dēmissus" "to drop, slip out"

   "dēmōnstrat" "he demonstrates"
   "dēmōnstrātum" "having been demonstrated"
   "dēmōnstrāveram" "I had demonstrated"
   "dēmōnstrāverat" "he had demonstrated"
   "dēmōnstrāvērunt" "they had demonstrated"
   "dēmōnstrārēmus" "we might have been demonstrating"
   "dēmōnstrāre" "to demonstrate"
   "dēmōnstrō, dēmōnstrāre, dēmōnstrāvī, dēmōnstrātus" "to demonstrate"
   
   "dēmorātus" "dwelling, detaining"
   "dēmorābantur" "they were dwelling, they were delaying"
   "dēmorārī" "to detain, to delay, to dwell"
   "dēmoror, dēmorārī, dēmorātus sum" "to detain, to delay, to dwell"

   "dēnāriīs" "denarii. A denarius is a type of coin"
   "dēnāriō" "denarii. A denarius is a type of coin"
   "dēnāriōs" "denarii. A denarius is a type of coin"
   "dēnārius" "denarius. A denarius is a type of coin"
   "dēnārius, dēnāriī" "denarius. A denarius is a type of coin"

   "dēnegō" "I deny, refuse"
   "dēnegāvērunt" "they denied, refused"
   "dēnegāre" "to deny, refuse"
   "dēnegō, dēnegāre, dēnegāvī, dēnegātus" "to deny, refuse"

   "dēns" "tooth"
   "dentem" "tooth"
   "dentēs" "teeth"
   "dentibus" "teeth"
   "dentis" "tooth's"
   "dēns, dentis" "tooth"

   "dēnsissimīs" "very dense"
   "dēnsus, dēnsa -um, dēnsior -or -us, dēnsissimus -a -um" "dense"

   "dēnūdātur" "it is uncovered"
   "dēnūdāre" "to uncover"
   "dēnūdō, dēnūdāre, dēnūdāvī, dēnūdātus" "to uncover"

   "dēnūntiābat" "he was foretelling, giving notice"
   "dēnūntiāre" "to foretell, to give notice"
   "dēnūntiō, dēnūntiāre, dēnūntiāvī, dēnūntiātus" "to foretell, to give notice"

   "dēportāvērunt" "they carried down"
   "dēportāre" "to carry down"
   "dēportō, dēportāre, dēportāvī, dēportātus" "to carry down"

   "dēposcit" "he asked for, requested, demanded"
   "dēpōscere" "to demand, require, challenge"
   "dēpōscō, dēpōscere, dēpopōscī, -" "to demand, require, challenge"

   "dēpositīs" "deposits, trusts"
   "dēpositum, dēpositī" "deposit, trust"

   "dēpraedāta" "having been plundered"
   "dēpraedārentur" "they might plunder"
   "dēpraedārī" "to plunder, pillage"
   "dēpraedor, dēpraedārī, dēpraedātus" "to plunder, pillage"

   "dēprecāns" "praying"
   "dēprecantēs" "praying"
   "dēpreco, dēprecāre, dēprecāvī, dēprecātus" "to pray"
   "dēprecor" "I prayed"
   "dēprecātiō, dēprecātiōnis" "deprecation; averting by prayer"
   "dēprecātiōnum" "of deprecations"
   "dēprecāvisset" "they (might) have had prayed"
   "dēprecābātur" "they were praying"
   "dēprecārī" "to be prayed"

   "dēpressōs" "having been suppressed"
   "dēprimī" "to be suppressed"
   "dēprimere" "to suppress"
   "dēprimō, dēprimere, dēpressī, dēpressus" "to suppress"

   "dērelinquēmus" "we will abandon"
   "dērelīquērunt" "they abandoned"
   "dērelinquere" "to abandon"
   "dērelinquō, dērelinquere, dērelīquī, dērelictus" "to abandon"

   "dērīdet" "he mocks, laughs at"
   "dērīdēre" "to mock, laugh at"
   "dērīdeō, dērīdēre, dērīsī, dērīsus" "to mock, laugh at"

   "deī" "god, diety"
   "deō" "god"
   "deōrum" "of gods"
   "deōs" "gods"

   "dēscenderet" "he might have descended"
   "dēscenderent" "they might have descended"
   "dēscendentēs" "descending"
   "dēscenderant" "they had descended"
   "dēscendērunt" "they descended"
   "dēscendisse" "to have descended"
   "dēscendit" "he descended"
   "dēscendere" "to descend"
   "dēscendō, dēscendere, dēscendī, dēscēnsus" "to descend"

   "dēscrībere" "to describe"
   "dēscrībō, dēscrībere, dēscrīpsī, dēscrīptus" "to describe"

   "dēserta" "deserts"
   "dēsertum, dēsertī" "desert"

   "dēsīderābam" "I was desiring"
   "dēsīderant" "they desire"
   "dēsīderāret" "he desired"
   "dēsīderāre" "to desire"
   "dēsīderō, dēsīderāre, dēsīderāvī, dēsīderātus" "to desire"

   "dēsīderiī" "longing, desire, wish"
   "dēsīderiō" "longing, desire, wish"
   "dēsīderium" "longing, desire, wish"
   "dēsīderium, dēsīderiī" "longing, desire, wish"
   
   "dēsīgnāvisset" "he (might) have had designated"
   "dēsīgnō, dēsīgnāre, dēsīgnāvī, dēsīgnātus" "to designate"

   "desiliendum" "jumping down"
   "desilīre" "to jump down"
   "desilīte" "jump down!"
   "desiluērunt" "they jumped down"
   "desiluit" "he jumped down"
   "desiliunt" "they jump down"
   "desiliō, desilīre, desiluī, desultus" "to jump down"

   "dēsinam" "I will stop, leave off"
   "dēsinere" "to stop, leave off"
   "dēsinō, dēsinere, dēsīvī, dēsitus" "to stop, leave off"

   "dēspērāta" "desperate"
   "dēspērātus, dēspērāta, dēspērātum" "desperate"
   
   "dēspēximus" "we disdained"
   "dēspiciō, dēspicere, dēspēxī, dēspectus" "to disdain"

   "dēstinante" "determining"
   "dēstinō, dēstināre, dēstināvī, dēstinātus" "to determine"

   "dēstinātum" "target, purpose, destination"
   "dēstinātum, dēstinātī" "target, purpose, destination"

   "dēstrūxit" "he destroyed"
   "dēstrūxerant" "they had destroyed"
   "dēstrūxērunt" "they destroyed"
   "dēstruere" "to destroy"
   "dēstruō, dēstruere, dēstrūxī, dēstrūctus" "to destroy"

   "dēterget" "he wipes off"
   "dētergēre" "to wipe away"
   "dētergeō, dētergēre, dētersī, dētersus" "to wipe away"
   
   "dēterrimum" "worst"
   "-, -, dēterior -or -us, dēterrimus -a -um" "worst"
   "dētrīmentum" "harm, detriment"
   "dētrīmentī" "harm, detriment"
   "dētrīmentō" "harm, detriment"
   "dētrīmentum, dētrīmentī" "harm, detriment"

   "dētruncātae" "having been beheaded"
   "dētruncandō" "cutting off, beheading"
   "dētruncāvērunt" "they cut off, behead"
   "dētruncāre" "to cut off, behead"
   "dētruncō, dētruncāre, dētruncāvī, dētruncātus" "to cut off, behead"

   "dēturbārētur" "it might be beat down, dislodged"
   "dēturbāre" "to beat down, dislodge"
   "dēturbō, dēturbāre, dēturbāvī, dēturbātus" "to beat down, dislodge"

   "diī" "gods"
   "deum" "god"
   "deus" "god"
   "deus, deī" "god, diety"

   "dēvastābant" "they were devastating, ravaging"
   "dēvāstantēs" "devastating, ravaging"
   "dēvastāte" "devastate! ravage!"
   "dēvāstāre" "to devastate, ravage"
   "dēvāstō, dēvāstāre, dēvāstāvī, dēvāstātus" "to devastate, ravage"

   "dēvēnit" "he came to"
   "dēveniō, dēvenīre, dēvēnī, dēventus" "to come to"

   "dēvīcimus" "we conquered entirely"
   "dēvictī" "having been conquered entirely"
   "dēvictīs" "having been conquered entirely"
   "dēvictōs" "having been conquered entirely"
   "dēvictūra" "conquering entirely"
   "dēvincere" "to conquer entirely"
   "dēvincō, dēvincere, dēvīcī, dēvictus" "to conquer entirely"
   
   "dēvorat" "he devours"
   "dēvoret" "he (may) devour"
   "dēvorandōs" "devouring"
   "dēvorābit" "he will devour"
   "dēvorābitis" "you will devour"
   "dēvorābunt" "they will devour"
   "dēvorandum" "devouring"
   "dēvorāre" "to devour"
   "dēvorātum" "having been devoured"
   "dēvorāvērunt" "they devoured"
   "dēvorāvit" "he devoured"
   "dēvorō, dēvorāre, dēvorāvī, dēvorātus" "to devour"

   "dēvōtē" "devotedly"
   
   "dēvorātōrem" "devourer, glutton"
   "dēvorātor, dēvorātōris" "devourer, glutton"

   "dextera" "right hand, right side"
   "dextera, dexterae" "right hand, right side"

   "dextra" "right hand, right side"
   "dextram" "right hand, right side"
   "dextrum" "right hand, right side"
   "dextra, dextrae" "right hand, right side"
   
   "diabolī"  "devil, demon"
   "diabolō"  "devil, demon"
   "diabolum" "devil, demon"
   "diabolus" "devil, demon"
   "diabolus, diabolī" "devil, demon"

   "diabolicā"  "diabolic, devilish"
   "diabolicam" "diabolic, devilish"
   "diabolicum" "diabolic, devilish"
   "diabolicus, diabolica, diabolicum" "diabolic, devilish"

   "diadēma" "diadem, crown"
   "diadēmatis" "diadem, crown"
   "diadēmate" "diadem, crown"
   "diadēma, diadēmatis" "diadem, crown"

   "dīc" "say!"
   "dīcam" "I will say"
   "dīcās" "you might say"
   "dīcēbat" "he was saying"
   "dīcēbant" "they were saying"
   "dīcēns" "saying"
   "dīcentem" "saying"
   "dīcentēs" "saying"
   "dīcere" "to say"
   "dīcerent" "they (might) have been saying"
   "dīceret" "he (might) have been saying"
   "dīcī" "to be said"
   "dīcis" "you say"
   "dīcit" "he says"
   "dīcitur" "it is said"
   "dictā" "having been said"
   "dictī" "things having been said"
   "dictīs" "things having been said"
   "dictō" "having been said"
   "dīcunt" "they say"
   "dictus" "having been said"
   "dīcēbantur" "they were said"
   "dicendum" "for saying"
   "dīxēre" "they said"
   "dictae" "having been said"
   "dictam" "having been said"
   "dīxisse" "to have said"
   "dīxerō" "I will have said"
   "dīcent" "they will say"
   "dictūrōs" "saying"
   "dīcendō" "saying"
   "dīcimus" "we say"
   "dīcite" "say!"
   "dīcō, dīcere, dīxī, dictus" "to say"

   "dictābat" "he was saying"
   "dictāre" "to say"
   "dictō, dictāre, dictāvī, dictātus" "to say"

   "dictātōrēs" "dictators"
   "dictātor, dictātōris" "dictator"

   "dictiōnis" "saying, talk"
   "dictiō" "saying, talk"
   "dictiō, dictiōnis" "saying, talk"

   "dictum" "words, saying"
   "dictum, dictī" "words, saying"
   
   "diēs" "day"
   "diē" "day"
   "diēī" "day"
   "diēbus" "days"
   "diem" "day"
   "diērum" "days"
   "diēs, diēī" "day"

   "diffāmāta" "having been defamed"
   "diffāmāre" "to defame, slander"
   "diffāmō, diffāmāre, diffāmāvī, diffāmātus" "to defame, slander"

   "differunt" "they delay, they differ"
   "differre" "to delay, to differ"
   "differt" "it differs"
   "differō, differre, distulī, dīlātus" "to delay, to differ"
   
   "difficillimum" "very difficult"
   "difficilius" "difficult"
   "difficilis" "difficult"
   "difficile" "difficult"
   "difficilis, difficile, difficilior -or -us, difficillimus -a -um" "difficult"

   "difficultās" "difficulty"
   "difficultās, difficultātis" "difficulty"

   "Diffīdēns" "distrusting"
   "diffīdēns" "distrusting"
   "diffīdō, diffīdere, diffīsus" "to distrust"

   "digitō"  "finger, toe, digit"
   "digitōs" "fingers, toes, digits"
   "digitus" "finger, toe, digit"
   "digitī"  "finger, toe, digit"
   "digitīs" "fingers, toes, digits"
   "digitum" "finger, toe, digit"
   "digitus, digitī" "finger, toe, digit"
   
   "dīgnēminī" "you (might) be deemed worthy"
   "dīgnēris" "you (might) be deemed worthy"

   "dignitās" "worth, honor, esteem, rank"
   "dignitās, dignitātis" "worth, honor, esteem, rank"
   "dignitāte" "worth, honor, esteem, rank"
   "dignitātem" "worth, honor, esteem, rank"
   "dignitātis" "worth, honor, esteem, rank"

   "dīgnārētur" "he deemed worthy"
   "dīgnatus" "having been deemed worthy"
   "dīgnata" "having been deemed worthy"
   "dīgnō, dīgnāre, dīgnavī, dīgnatus" "to deem worthy, to deign"

   "dīgnās" "worthy, appropriate"
   "dīgnum" "worthy, appropriate"
   "dīgnus, dīgna, dīgnum" "worthy, appropriate"

   "dīlaniāns" "tearing to pieces"
   "dīlaniāre" "to tear to pieces"
   "dīlaniō, dīlaniāre, dīlaniāvī, dīlaniātus" "to tear to pieces"

   "dīlāpsōs" "having broken down, flowed out"
   "dīlābor, dīlābī, dīlāpsus sum" "to break down, flow out"

   "dīlātāvērunt" "they expanded, prolonged"
   "dīlātō, dīlātāre, dīlātāvī, dīlātātus" "to expand, prolong"

   "dīlēctiōne" "love"
   "dīlēctiōnem" "love"
   "dīlēctiō, dīlēctiōnis" "love"
   
   "dīlēxī" "I loved"
   "dīlēxit" "he loved"
   "dīligātis" "you might love"
   "dīligēbat" "he was loving"
   "dīligimus" "we love"
   "dīligis" "you love"
   "dīligit" "he loves"
   "dīligō" "I love"
   "dīlēctus" "having been loved"
   "dīligō, dīligere, dīlēxī, dīlēctus" "to love"
   
   "dīligentia" "diligence"
   "dīligentia, dīligentiae" "diligence"

   "dīlūculō"  "daybreak, dawn"
   "dīlūculum" "daybreak, dawn"
   "dīlūculum, dīlūculī" "daybreak, dawn"

   "dīluviō" "flood, destruction"
   "dīluvium" "flood, destruction"
   "dīluvium, dīluviī" "flood, destruction"

   "dīmicābat" "he fought"
   "dīmicandō" "fighting"
   "dīmicantēs" "fighting"
   "dīmicāvērunt" "they fought"
   "dīmicent" "they fight"
   "dīmicō, dīmicāre, dīmicāvī, dīmicātus" "to fight"
   
   "dīmīsērunt" "they sent away, they dismissed"
   "dīmīsī" "he sent away, he dismissed"
   "dīmīsimus" "we sent away"
   "dīmīsistī" "you sent away"
   "dīmīsistis" "you sent away"
   "dīmitte" "dismiss! send away!"
   "dīmittite" "dismiss! send away!"
   "dīmittētur" "it might be sent away"
   "dīmittere" "to dismiss, to send away"
   "dīmittō, dīmittere, dīmīsī, dīmissus" "to dismiss, to send away"
   "dīmissa" "having been sent away"
   "dīmissō" "having been sent away"
   "dīmissus" "having been sent away"
   "dīmīsit" "he sent away"

   "dīra" "ominous, dreadful"
   "dīrās" "ominous, dreadful"
   "dīrus, dīra -um, dīrior -or -us, dīrissimus -a -um" "ominous, dreadful"
   
   "dīrigis" "you align, you direct"
   "dīrigit" "he aligns, he directs"
   "dīrigēbat" "he was aligning/directing"
   "dīrigeret" "he might direct"
   "dīrigite" "arrange! direct!"
   "dīrēxerit" "he will have aligned, directed"
   "dīrēctus" "having been directed"
   "dīrigō, dīrigere, dīrēxī, dīrēctus" "to arrange in line, to align, to direct"

   "dītis" "rich"
   "dītissimus" "rich"
   "dīs, dītis (gen.), dītior -or -us, dītissimus -a -um" "rich"

   "discēdit" "he departs"
   "discēdendum" "departing"
   "discēdēns" "departing"
   "discēdunt" "they depart"
   "discessērunt" "they departed"
   "discessissent" "they had departed"
   "discēdere" "to depart"
   "discēdō, discēdere, discessī, discessus" "to depart"

   "dīscant" "they might learn"
   "didicit" "he learned"
   "dīsceret" "he might learn"
   "dīscō, dīscere, didicī, dīscitus" "to learn"

   "discernerent" "they were discerning, separating"
   "discernere" "to discern, distinguish, separate"
   "discernō, discernere, discrēvī, discrētus" "to discern, distinguish, separate"

   "disciplīna" "teaching, instruction"
   "disciplīna, disciplīnae" "teaching, instruction"

   "discipulīs" "students"
   "discipulus" "student"
   "discipulus, discipulī" "student"
   
   "discooperta" "having been uncovered"
   "discoopertum" "having been uncovered"
   "discooperiō, discooperīre, discooperuī, discoopertus" "to bare, to disclose"

   "discordia" "discord, disagreement"
   "discordiam" "discord, disagreement"
   "discordia, discordiae" "discord, disagreement"

   "discrīmen" "distinction, division"
   "discrīmen, discrīminis" "distinction, division"
   
   "discubuissent" "he (might) have had reclined at table/laid down"
   "discumbō, discumbere, discubuī, discubitus" "to recline at table, to lie down"

   "discursum" "discourse"
   "discursus, discursūs" "discourse"
   
   "discurrō, discurrere, discurrī, discursus" "to run around"
   "discurrentēs" "running around"

   "discussō" "having been struck down"
   "discutere" "to strike down"
   "discutiō, discutere, discussī, discussus" "to strike down"

   "diserta" "skilled in speaking"
   "disertus, diserta, disertum" "skilled in speaking"

   "dispersērunt" "they spread out"
   "dispersōs" "spread out"
   "dispersus, dispersa, dispersum" "spread out"

   "disperge" "scatter!"
   "dispergendum" "spreading out"
   "dispergere" "to spread out"
   "dispergō, dispergere, dispersī, dispersus" "to spread out"

   "dispositīs" "having been arranged, distributed"
   "disposuit" "he arranged, distributed"
   "dispositūrus" "for arranging"
   "dispōnō, dispōnere, disposuī, dispositus" "to arrange, distribute"

   "disrumperent" "they shattered"
   "disrumpō, disrumpere, disrūpī, disruptus" "to shatter"

   "dissentīrent" "they were disagreeing"
   "dissentīre" "to disagree"
   "dissentiō, dissentīre, dissēnsī, dissēnsus" "to disagree"

   "dissēparābat" "he was separating, dividing"
   "dissēparāre" "to separate, divide"
   "dissēparō, dissēparāre, dissēparāvī, dissēparātus" "to separate, divide"

   "dissimulāns" "concealing, disguising, hiding"
   "dissimulāre" "to conceal, disguise, hide"
   "dissimulō, dissimulāre, dissimulāvī, dissimulātus" "to conceal, disguise, hide"

   "dissipā" "scatter! disperse!"
   "dissipāvissent" "they had scattered, dispersed"
   "dissipāre" "to scatter, disperse"
   "dissipō, dissipāre, dissipāvī, dissipātus" "to scatter, disperse"

   "distat" "it stands apart, it is distant"
   "distō, distāre, -, -" "to stand apart, be distant"

   "districtā" "busy, pulled in many directions"
   "districtus, districta -um, districtior -or -us, districtissimus -a -um" "busy, pulled in many directions"

   "distillābat" "it was dripping"
   "distīllō, distīllāre, distīllāvī, distīllātus" "to drip"

   "dītāvit" "he enriched"
   "dītāret" "he might have enriched"
   "dītāre" "to enrich"
   "dītō, dītāre, dītāvī, dītātus" "to enrich"
   
   "dīversae" "diverse"
   "dīversa" "diverse"
   "dīversam" "diverse"
   "dīversārum" "diverse"
   "dīversās" "diverse"
   "dīversī" "diverse"
   "dīversīs" "diverse"
   "dīversōs" "diverse"
   "dīversus" "diverse"
   "dīversus, dīversa, dīversum" "diverse"

   "dīves" "rich"
   "dīvitēm" "rich"
   "dīvitēs" "rich"
   "dīvitī" "rich"
   "dīvitis" "rich"
   "dīvitum" "rich"
   "dīves, dīvitis (gen.), dīvitior -or -us, dīvitissimus -a -um" "rich"
   
   "dīvīna" "divine"
   "dīvīnum" "divine"
   "dīvīnō" "divine"
   "dīvīnus, dīvīna -um, dīvīnior -or -us, dīvīnissimus -a -um" "divine"
   
   "dīvidit" "he divides"
   "dīvidunt" "they divide"
   "dīvīsa" "having been divided"
   "dīvīsae" "having been divided"
   "dīvīsērunt" "they divided"
   "dīvīsōs" "having been divided"
   "dīvīsī" "having been divided"
   "dīvīsit" "he divided"
   "dīvidō, dīvidere, dīvīsī, dīvīsus" "to divide"

   "dīvīsiō" "division"
   "dīvīsiōnis" "division"
   "dīvīsiō, dīvīsiōnis" "division"
   
   "dīxerat" "he had said"
   "dīxērunt" "they said"
   "dīxī" "I said"
   "dīxistī" "you said"
   "dīxisset" "he (might) have had said"
   "dīxit" "he said"
   "dīximus" "we said"
   
   "dedit" "he gave"
   "dispendia" "pay, nourishment"
   "dispendiīs" "pay, nourishment"
   "dispendium, dispendiī" "pay, nourishment, expense, cost"
   "distringit" "he stretches"
   "distringō, distringere, distrīnxī, districtus" "to stretch"
   
   "distribuit" "he distributed"
   "distribūtīs" "having be distributed"
   "distribuere" "to distribute"
   "distribuō, distribuere, distribuī, distribūtus" "to distribute"
   "dedissent" "they (might) have had given"
   "dēlātīs" "having been transferred, having been brought down"
   "dēferunt" "they transfer"
   "dēferret" "he (might) have been bringing"
   "dēfertur" "it is being transferred"
   "dētulērunt" "they transferred"
   "dēferrent" "they transferred"
   "dēferat" "he transfers"
   "dēferēbant" "they were transferring"
   "dēferēns" "transferring"
   "dēferentēs" "transferring"
   "dēferrī" "to be transferred"
   "dēlātum" "having been transferred"
   "dēferō, dēferre, dētulī, dēlātus" "to bring down, to transfer"
   
   "dīmidium" "half"
   "dīmidium, dīmidiī" "half"

   "dīvitia, dīvitiae" "riches, wealth"
   "dīvitiās" "riches, wealth"

   "dabatur" "he was being given"
   "dabantur" "they were being given"
   "dabant" "they were giving"
   "dabimus" "we will give"
   "dabō" "I will give"
   "dedī" "I gave"
   "dare" "to give"
   "daret" "he gave"
   "datūrus" "will be given"
   "dabat" "he was giving"
   "dabit" "he will give"
   "darētur" "he was being given"
   "dederat" "he had given"
   "dent" "they might give"
   "det" "he might give"
   "dō, dare, dedī, datus" "to give (irregular)"

   "docēbant" "they were teaching"
   "docent" "they teach"
   "docuit" "he taught"
   "docēre" "to teach"
   "doceō, docēre, docuī, doctus" "to teach"

   "doctor" "teacher, instructor"
   "doctōrem" "teacher, instructor"
   "doctōris" "teacher, instructor"
   "doctor, doctōris" "teacher, instructor"

   "doctrīnae" "doctrine, teaching, instruction"
   "doctrīna, doctrīnae" "doctrine, teaching, instruction"

   "doctissimō" "very learned, knowledgeable"
   "doctissimus" "very learned, knowledgeable"
   "doctus" "learned, knowledgeable"

   "dogma" "doctrine, dogma"
   "dogmate" "doctrine, dogma"
   "dogmatis" "doctrine, dogma"
   "dogma, dogmatis" "doctrine, dogma"

   "dolor" "pain, sorrow"
   "dolōre" "pain, sorrow"
   "dolōrī" "to pain, sorrow"
   "dolor, dolōris" "pain, sorrow"

   "dolēbat" "he was sorrying, grieving, feeling pain"
   "dolēns" "sorrying, grieving"
   "dolentēs" "sorrying, grieving"
   "dolentibus" "sorrying, grieving"
   "dolet" "it hurts"
   "doluērunt" "they were sorrying, grieving"
   "dolēre" "to sorry, grieve, feel pain"
   "doleō, dolēre, doluī, dolitus" "to sorry, grieve, feel pain"

   "dolōsa" "crafty, cunning"
   "dolōsī" "crafty, cunning"
   "dolōsum" "crafty, cunning"
   "dolōsus" "crafty, cunning"
   "dolōsus, dolōsa, dolōsum" "crafty, cunning"

   "dolum" "trickery, deception"
   "dolus" "trickery, deception"
   "dolus, dolī" "trickery, deception"

   "domina" "mistress"
   "dominae" "of the mistress"
   "domina, dominae" "mistress"

   "domāret" "he subdued, tamed"
   "domāre" "to subdue, tame"
   "domō, domāre, domuī, domitus" "to subdue, tame"

   "dominābantur" "he was being mastered"
   "dominārī" "to be mastered"
   "domināre" "to master"
   "dominō, domināre, domināvī, dominātus" "to master"

   "dominātū" "rule, mastery, tyranny"
   "dominātus" "rule, mastery, tyranny"
   "dominātus, dominātūs" "rule, mastery, tyranny"
   
   "domestica" "domestic"
   "domesticī" "domestic"
   "domesticus, domestica, domesticum" "domestic"
   
   "domine" "lord, master"
   "dominī" "of the lord"
   "dominō" "lord"
   "dominum" "lord"
   "dominicīs" "Sundays"
   "dominica" "Sunday"
   "dominicae" "Sunday"
   "dominicō" "Sunday"
   "Dominica" "Sunday"
   "Dominica, Dominicae" "Sunday"
   "dominicam" "Sunday"
   "dominicum" "Sunday"
   "dominicus" "Sunday"

   "dominium" "dominion"
   "dominium, dominiī" "dominion"
   
   "dominorum" "of the lords, of the masters"
   "dominus" "lord, master"
   "dominus, dominī" "lord, master"

   "domnus" "lord, master"
   "domnus, domnī" "lord, master"

   "domī" "at home"
   "domibus" "houses"
   "domō" "house"
   "domōrum" "of houses"
   "domōs" "houses"
   "domum" "house"
   "domus" "house"
   "domūs" "house"
   "domus, domūs" "house"

   "dōnābant" "they were giving"
   "dōnāmus" "we are giving"
   "dōnāvit" "he gave"
   "dōnātus" "having been given"
   "dōnō, dōnāre, dōnāvī, dōnātus" "to give"

   "dōna" "gifts"
   "dōnīs" "gifts"
   "dōnō" "gift"
   "dōnum, dōnī" "gift"

   "dormientem" "sleeping"
   "dormientis" "sleeping"
   "dormit" "he sleeps"
   "dormiēbat" "he was sleeping"
   "dormiēbant" "they were sleeping"
   "dormiam" "I will sleep"
   "dormiās" "you (might) sleep"
   "dormiēns" "sleeping"
   "dormiente" "sleeping"
   "dormientēs" "sleeping"
   "dormīmus" "we sleep"
   "dormītum" "having slept"
   "dormīvērunt" "they slept"
   "dormīvit" "he slept"
   "dormī" "sleep!"
   "dormīre" "to sleep"
   "dormiō, dormīre, dormīvī, dormītus" "to sleep"

   "dorsa"  "back"
   "dorsum" "back"
   "dorsō" "back"
   "dorsum, dorsī" "back"

   "dracō" "dragon, snake"
   "dracōnēs" "dragons, snakes"
   "dracō, dracōnis" "dragon, snake"
   
   "dubium" "doubt"
   "dubiō" "doubt"
   "dubium, dubiī" "doubt"

   "dubitāns" "hesitating, doubting"
   "dubitantēs" "hesitating, doubting"
   "dubitāret" "he hesitated, doubted"
   "dubitātiōne" "hesitating, doubting"
   "dubitāre" "to doubt, hesitate"
   "dubitō, dubitāre, dubitāvī, dubitātus" "to doubt, hesitate"

   "dūcēns" "leading"
   "dūcit" "he leads"
   "ductīs" "to have been lead"
   "dūcere" "to lead"
   "ducta" "having been lead"
   "dūcēbant" "they were leading"
   "dūcēbātur" "he was being lead"
   "dūcant" "they (might) lead"
   "dūcerentur" "they (might) have been leading"
   "dūcet" "you will lead"
   "dūcendam" "leading"
   "ductus" "having been lead"
   "dūcī" "to be lead"
   "dūcō, dūcere, dūxī, ductus" "to lead"
   "dūcerent" "they might lead"
   "ductī" "having been lead"
   "dūcitur" "it is drawn"
   
   "ductor" "leader"
   "ductōre" "leader"
   "ductōrēs" "leaders"
   "ductor, ductōris" "leader"

   "dulcia" "pleasant, charming, flattering"
   "dulcissime" "pleasant, charming, flattering"
   "dulcis, dulce, dulcior -or -us, dulcissimus -a -um" "pleasant, charming, flattering"

   "duae" "two"
   "duābus" "two"
   "duōrum" "two"
   "duās" "two"
   "duōbus" "two"
   "duo -ae o, secundus -a -um, bīnī -ae -a, bis" "two"

   "duplex" "double"
   "duplicēs" "double"
   "duplex, (gen.), duplicis" "double"
   "duplicem" "double"

   "dūra" "hard"
   "dūrī" "hard"
   "dūrior" "harder"
   "dūrius" "harder"
   "dūrum" "hard"
   "dūrus, dūra -um, dūrior -or -us, dūrissimus -a -um" "hard"

   "dūrāverat" "it had endured"
   "dūrāvit" "it endured"
   "dūrāre" "to harden, endure"
   "dūrō, dūrāre, dūrāvī, dūrātus" "to harden, endure"

   "duce" "leader"
   "ducem" "leader"
   "ducēs" "leaders"
   "ducis" "of the leader"
   "ducum" "of leaders"
   "ducibus" "leaders"
   "dux" "leader"
   "dux, ducis" "leader"
   
   "dūxērunt" "they were leading"
   "dūxēre" "they were leading"
   "dūximus" "we lead"
   "dūxit" "he lead"
   })
