(ns whitakers-clj.dict-r)

(def dict-r
  {"radiantēs" "beaming, shining"
   "radiāre" "to beam, to shine"
   "radiō, radiāre, radiāvī, radiātus" "to beam, to shine"
   
   "rādīcibus" "roots"
   "rādīx, rādīcis" "root"
   "rādīcēs" "roots"
   
   "rāmī" "branches"
   "rāmō" "branch"
   "rāmīs" "branches"
   "rāmōs" "branches"
   "rāmum" "branch"
   "rāmus" "branch"
   "rāmus, rāmī" "branch"

   "rapuit" "he seized, pillaged"
   "rapere" "to seize, to pillage"
   "rapiō, rapere, rapuī, raptus" "to seize, to pillage"

   "rapidī" "quick"
   "rapidissimō" "very quick"
   "rapidō" "quick"
   "rapidus, rapida -um, rapidior -or -us, rapidissimus -a -um" "quick"

   "raptōre" "robber, plunderer"
   "raptor" "robber, plunderer"
   "raptōris" "robber, plunderer"
   "raptor, raptōris" "robber, plunderer"

   "raptus" "snatching away, robbery"
   "raptus, raptūs" "snatching away, robbery"
   
   "rāra" "thin, far apart, rare"
   "rārō" "thin, far apart, rare"
   "rārum" "thin, far apart, rare"
   "rārus" "thin, far apart, rare"
   "rārus, rāra -um, rārior -or -us, rārissimus -a -um" "thin, far apart, rare"

   "ratēs" "rafts, barks, vessels"
   "ratis, ratis" "raft, bark, vessel"

   "ratiōnālis" "reasonable"
   "ratiōnālis, ratiōnālis, ratiōnāle" "reasonable"

   "ratiōne" "reason"
   "rationem" "reason"
   "ratiōnis" "reason"
   "ratiō, ratiōnis" "reason"

   "reātūs" "accusation, charge"
   "reātus, reātūs" "accusation, charge"

   "rebellāvit" "he rebelled"
   "rebellāre" "to rebel"
   "rebellō, rebellāre, rebellāvī, rebellātus" "to rebel"

   "rebelliōne" "renewal of war, rebellion"
   "rebelliōnem" "renewal of war, rebellion"
   "rebelliō" "renewal of war, rebellion"
   "rebelliōnis" "renewal of war, rebellion"
   "rebelliō, rebelliōnis" "renewal of war, rebellion"

   "rebellis" "rebellious"
   "rebellis, rebelle" "rebellious"

   "recalcitrāre" "to kick back, be disobedient"
   "recalcitrō, recalcitrāre, recalcitrāvī, recalcitrātus" "to kick back, be disobedient"
   
   "recēdās" "you (might) recede, withdraw"
   "recēdātis" "you (might) recede, withdraw"
   "recēde" "recede! withdraw!"
   "recēdēbant" "they were receding, they were withdrawing"
   "recēdunt" "they withdraw"
   "recēdet" "he will withdraw"
   "recēdit" "it recedes"
   "recēdite" "withdraw!"
   "recesserit" "it will have withdrawn"
   "recessērunt" "they withdrew"
   "recessimus" "we withdrew"
   "recessit" "he withdrew"
   "recessūrus" "withdrawing"
   "recēdere" "to recede, to withdraw"
   "recēdō, recēdere, recessī, recessus" "to recede, to withdraw"

   "receptum" "engagement, obligation"
   "receptum, receptī" "engagement, obligation"
   
   "recēpistī" "you received"
   "receptās" "having been received"
   "receptī"  "having been received"
   "receptīs" "having been received"
   "receptō" "having been received"
   "receptōs" "having been received"
   "recēpērunt" "they received, they kept back"
   "recēperat" "he had received"
   "recēpimus" "we received"
   "recēpit" "he received"
   "recipī" "to be received"
   "recipiam" "I might receive"
   "reciperet" "he might receive"
   "recēpissem" "I might have had received"
   "recipiendam" "receiving"
   "recipere" "to receive"
   "recipiō, recipere, recēpī, receptus" "to receive"
   
   "receptiō" "reception"
   "receptiō, receptiōnis" "reception"
   
   "reciprocābant" "they were going back and forth"
   "reciprocō, reciprocāre, reciprocāvī, reciprocātus" "to go back and forth"

   "recitāvit" "he recited"
   "recitāre" "to recite"
   "recitō, recitāre, recitāvī, recitātus" "to recite"

   "recolligam" "I will recover, collect"
   "recolligere" "to recover, collect"
   "recolligō, recolligere, recollēgī, recollēctus" "to recover, collect"

   "recōgnōscere" "to recognize"
   "recōgnōscō, recōgnōscere, recōgnōvī, recōgnitus" "to recognize"

   "reconciliāta" "having been reconciled"
   "reconciliātī" "having been reconciled"
   "reconciliō, reconciliāre, reconciliāvī, reconciliātus" "to reconcile"

   "recondita" "having been hidden, concealed, put away"
   "reconditae" "having been hidden, concealed, put away"
   "recondere" "to hide, conceal, put away"
   "recondō, recondere, recondidī, reconditus" "to hide, conceal, put away"
   
   "rēctitūdinis" "straightness, rectitude"
   "rēctitūdō, rēctitūdinis" "straightness, rectitude"

   "rēctor" "leader, ruler"
   "rēctor, rēctōris" "leader, ruler"

   "rēctā" "straight, proper, correct"
   "rēctō" "straight, proper, correct"
   "rēctum" "straight, proper, correct"
   "rēctus, rēcta -um, rēctior -or -us, rēctissimus -a -um" "straight, proper, correct"

   "recuperātī" "having regained"
   "recuperanda" "to be regained"
   "recuperō, recuperāre, recuperāvī, recuperātus" "to regain"

   "recursū" "return, running back"
   "recursus" "return, running back"
   "recursus, recursūs" "return, running back"
   
   "reddēbant" "they were rending, they were returning"
   "redeuntēs" "returning"
   "redīret" "he (might) have been returning"
   "reddāmus" "let us return"
   "redde" "return!"
   "reddite" "return!"
   "redditum" "having being returned"
   "reddō, reddere, reddidī, redditus" "to return, to render"
   "reddētur" "to be returned"
   "reddidit" "he returned"
   "reddī" "to be returned"
   "redderent" "they might return"
   "reddidērunt" "they returned"
   "reddita" "having been returned"
   "redīrent" "they might have returned"
   "redībō" "I will return"
   "reddēmus" "we will return"
   "reddendam" "returning"

   "redēmptiō" "redemption"
   "redēmptiōne" "redemption"
   "redēmptiōnis" "redemption"
   "redēmptiō, redēmptiōnis" "redemption"
   
   "redēmptor" "redeemer"
   "redēmptōris" "redeemer"
   "redēmptōrem" "redeemer"
   "redēmptor, redēmptōris" "redeemer"

   "redācta"  "having been driven back"
   "redāctam" "having been driven back"
   "redigere" "to drive back, to render"
   "redigō, redigere, redēgī, redāctus" "to drive back, to render"

   "redimātur" "is being bought back"
   "redēmit" "he brought back, redeemed"
   "redēmī" "I redeemed"
   "redimerem" "I redeemed"
   "redimere" "to bring back"
   "redimō, redimere, redēmī, redēmptus" "to bring back"
   "redēmptī" "having been redeemed"

   "redimītus" "having been brought back"
   "redimīre" "having been brought back"
   "redimiō, redimīre, redimiī, redimītus" "having been brought back"

   "redeam" "I return"
   "redīre" "to return, to go back"
   "redīrem" "I (might) have returned"
   "redīvit" "he returned"
   "reditum" "having been returned"
   "rediērunt" "they returned"
   "redivērunt" "they returned"
   "redeuntem" "returning"
   "rediēns" "returning"
   "rediēre" "they returned"
   "reditūrus" "to be returned"
   "redeō, redīre, redivī(iī), reditus" "to return, to go back"

   "reditiōnis" "return"
   "reditiō" "return"
   "reditiō, reditiōnis" "return"

   "reditū" "returning, return"
   "reditus, reditūs" "returning, return"
   
   "redūcō, redūcere, redūxī, reductus" "to lead back, to bring back"
   "redūcet" "he will lead back, he will bring back"
   "redūxit" "he lead back"
   "redūxērunt" "they lead back"
   
   "refectiō" "refreshing, restoring, repairing"
   "refectiōne" "refreshing, restoring, repairing"
   "refectiōnem" "refreshing, restoring, repairing"
   "refectiō, refectiōnis" "refreshing, restoring, repairing"
   
   "reficiēminī" "you will refresh, you will restore"
   "reficere" "to rebuild, to repair, to restore"
   "reficiō, reficere, refēcī, refectus" "to rebuild, to repair, to restore"
   "refēcērunt" "they refreshed"
   "reficiēbant" "they were rebuilding/repairing/restoring"
   "reficiēbat" "he was rebuilding/repairing/restoring"
   "reficiendō" "refreshing, rebuilding"
   "reficient" "they will refresh, they will rebuild"
   "reficiunt" "they refresh, they rebuild"
   "refice" "restore!"
   "reficite" "restore!"
   "reficiantur" "they (might) be refreshed"
   "refēcit" "he refreshed, he rebuilt"
   "reficiendās" "restoring, refreshing"
   "refectī" "having been refreshed"
   "reficiat" "let him refresh"

   "refertās" "having been filled up, stuffed full"
   "refercīre" "to fill up, stuff full"
   "referciō, refercīre, refersī, refertus" "to fill up, stuff full"

   "rettulērunt" "they brought back, reported"
   "referēns" "bringing back, reporting"
   "referentēs" "bringing back, reporting"
   "referēbant" "they were bringing back"
   "referimus" "we report, bring back"
   "referrentur" "they (might) be being reported"
   "referre" "to bring back, to report"
   "refers" "you bring back, report"
   "refert" "he brings back"
   "referō, referre, rettulī, relātus" "to bring back, to report"

   "reflectere" "to bend back"
   "reflectō, reflectere, reflexī, reflexus" "to bend back"
   
   "refocilātiō" "refreshment"
   "refocillātiō, refocillātiōnis" "refreshment"

   "refectōriō"  "dining room, refectory"
   "refectōrium" "dining room, refectory"
   "refectōrium, refectōriī" "dining room, refectory"
   
   "refrēnāre" "to restrain, curb, check"
   "refrēnō, refrēnāre, refrēnāvī, refrēnātus" "to restrain, curb, check"
   
   "refrīgerium" "cooling, consolation"
   "refrīgerium, refrīgeriī" "cooling, consolation"
   "refulsit" "it shone"
   "refulgeō, refulgēre, refulsī, -" "to shine"

   "refugiō"  "refuge"
   "refugium" "refuge"
   "refugium, refugiī" "refuge"

   "rēgālem" "royal"
   "rēgālī" "regal, royal"
   "rēgālia" "regal, royal"
   "rēgāle, rēgālis" "regal, royal"
   "rēgālis" "regal, royal"
   "rēgālibus" "regals, royals"
   "rēgālis, rēgālis, rēgāle" "regal, royal"

   "rēgia" "royal palace, court"
   "rēgiīs" "royal palaces, courts"
   "rēgia, rēgiae" "royal palace, court"

   "regimen" "control, steering"
   "regimine" "control, steering"
   "regiminis" "control, steering"
   "regimen, regiminis" "control, steering"

   "rēgīna" "queen"
   "rēgīnam" "queen"
   "rēgīna, rēgīnae" "queen"
   
   "regiō" "region"
   "regiōne" "region"
   "regiōnibus" "regions"
   "regiōnis" "regions"
   "regiōnem" "region"
   "regiōnēs" "regions"
   "regiō, regiōnis" "region"

   "rēgius" "royal, regal"
   "rēgius, rēgia, rēgium" "royal, regal"

   "rēgna" "kingdoms"
   "rēgnī" "of the kingdom"
   "rēgnīs" "kingdoms"
   "rēgnō" "kingdom"
   "rēgnum" "kingdom"
   "rēgnum, rēgnī" "kingdom"

   "regēbat" "he was ruling"
   "regitur" "is ruled"
   "regit" "he rules"
   "regentem" "reigning"
   "regere" "to rule"
   "regō, regere, rēxī, rēctus" "to rule"

   "rēgnābat" "he was reigning"
   "rēgnandum" "reigning"
   "rēgnante" "reigning"
   "rēgnantem" "reigning"
   "rēgnāvit" "he reigned"
   "regnavērunt" "they reigned"
   "rēgnāret" "he reigned"
   "rēgnārent" "they reigned"
   "rēgnantibus" "reigning"
   "rēgnat" "he reigns"
   "regerent" "they might have ruled"
   "rēgnātūra" "reigning"
   "rēgnāre" "to reign"
   "rēgnō, rēgnāre, rēgnāvī, rēgnātus" "to reign"

   "regressī" "having returned"
   "regrediēns" "returning"
   "regredior, regredī, regressus sum" "to return"
   
   "regressus" "return"
   "regressus, regressūs" "return"

   "rēgulīs" "rules, principles"
   "rēgulam" "rule, principle"
   "rēgula, rēgulae" "rule, principle"

   "rēgulī" "prince"
   "rēgulōs" "princes"
   "rēgulus" "prince"
   "rēgulus, rēgulī" "prince"

   "religiōsīs" "religious"
   "religiōsus, religiōsa, religiōsum" "religious"

   "relicta" "having been left behind"
   "relictīs" "leaving behind"
   "relictō" "having been left behind"
   "relinquit" "he leaves"
   "relinquerent" "they left behind"
   "relinquō, relinquere, relīquī, relictum" "to leave behind"

   "reliquiae" "relics, remains"
   "reliquiae, reliquiārum" "relics, remains"

   "reliqua" "remaining"
   "reliquae" "remaining"
   "reliquam" "remaining"
   "reliquās" "remaining"
   "reliquī" "remaining"
   "reliquīs" "remaining"
   "reliquōs" "remaining"
   "reliquus, reliqua, reliquum" "remaining"

   "reprōmissiō, reprōmissiōnis" "promise"
   "reprōmissiōnis" "promise"

   "reprōmissās" "having been promised"
   "reprōmittere" "to promise"
   "reprōmittō, reprōmittere, reprōmīsī, reprōmissum" "to promise"
   
   "rē" "thing"
   "rēbus" "things"
   "reī" "thing"
   "rem" "thing"
   "rēs" "things"

   "remanent" "they remain"
   "remanēre" "to remain"
   "remanēbimus" "we will remain"
   "remanēbit" "he will remain"
   "remanēret" "he (might) have been remaining"
   "remānsit" "he remained"
   "remanēbunt" "they will remain"
   "remānserant" "they had remained"
   "remānserat" "he had remained"
   "remānsērunt" "they remained"
   "remānserit" "they remained"
   "remānsimus" "we remained"
   "remaneat" "he might remain"
   "remaneam" "I might remain"
   "remaneō, remanēre, remānsī, remānsus" "to remain"

   "remeāvit" "he returned"
   "remeāre" "to come back, return"
   "remeō, remeāre, remeāvī, remeātus" "to come back, return"

   "remedium" "remedy, cure"
   "remedium, remediī" "remedy, cure"

   "remigrāre" "to move back, to return"
   "remigrō, remigrāre, remigrāvī, remigrātus" "to move back, to return"

   "rēmigāre" "to row"
   "rēmigō, rēmigāre, rēmigāvī, rēmigātus" "to row"

   "remīsērunt" "they sent back"
   "remissī" "having been sent back"
   "remissus" "having been sent back"
   "remittere" "to send back"
   "remittō, remittere, remīsī, remissus" "to send back"

   "rēmīs" "oars"
   "rēmōrum" "of oars"
   "rēmus, rēmī" "oar"

   "remōta" "having been removed"
   "remōtae" "having been removed"
   "removet" "he removes"
   "removērī" "to be removed"
   "removēre" "to remove"
   "removeō, removēre, remōvī, remōtus" "to remove"

   "rēnis" "kidney"
   "rēn, rēnis" "kidney"

   "repentīna" "unexpected, sudden"
   "repentīnae" "unexpected, sudden"
   "repentīnī" "unexpected, sudden"
   "repentīnum" "unexpected, sudden"
   "repentīnus" "unexpected, sudden"
   "repentīnus, repentīna, repentīnum" "unexpected, sudden"

   "reperit" "he finds"
   "reperiunt" "they find"
   "reperītur" "it is discovered, found"
   "reperiuntur" "they are discovered"
   "reperiētur" "will be discovered, found out"
   "repperērunt" "they discovered, found out"
   "repertō" "having been discovered"
   "repperit" "he discovered"
   "reperīrī" "to be found"
   "reperīre" "to discover, find out"
   "reperiō, reperīre, repperī, repertus" "to discover, find out"

   "repetendus" "demanding back, returning"
   "repetō, repetere, repetīvī, repetītus" "to demand back, return"

   "reparāvit" "he repaired"
   "reparāre" "to repair"
   "reparō, reparāre, reparāvī, reparātum" "to repair"

   "repedāre" "to return, retreat"
   "repedō, repedāre, repedāvī, repedātus" "to return, retreat"

   "replētī" "having been filled/re-filled"
   "repleō, replēre, replēvī, replētus" "to fill again"

   "reportārī" "to be reported"
   "reportāre" "to report"
   "reportō, reportāre, reportāvī, reportātus" "to report"

   "rēptāre" "to move slowly, crawl"
   "rēptō, rēptāre, rēptāvī, rēptātum" "to move slowly, crawl"

   "repūgnandī" "fighting back"
   "repūgnō, repūgnāre, repūgnāvī, repūgnātus" "to fight back"
   
   "reputābitur" "it will be thought over"
   "reputō, reputāre, reputāvī, reputātus" "to think over, to reflect"
   
   "requiēm" "rest, repose"
   "requiēs" "rest, repose"
   "requiēs, requiēī" "rest, repose"
   "requiēscam" "I will rest"
   "requiēscēns" "resting"
   "requiēscite" "rest!"
   "requiēscō, requiēscere, requiēvī, requiētum" "to rest, to quiet down"

   "requīsīvit" "he asked for, he required, he missed"
   "requīrat" "he requires, asks for"
   "requīrō, requīrere, requīsīvī, requīsītus" "to require, to ask for, to miss"

   "rērum" "of things"
   "rēs, reī" "thing"

   "rescindī" "to be rescinded, cut out"
   "rescindō, rescindere, rescidī, rescissus" "to rescind, cut out"

   "resēdit" "he sat, he settled"
   "residēre" "to sit down, to settle"
   "resīdēbat" "he was sitting down"
   "residentibus" "sitting down"
   "residēbant" "they were sitting down"
   "resideō, residēre, resēdī, resessus" "to sit down, to settle"
   "resēdērunt" "they sat down"
   "resēdisset" "he (might) have had sat down"
   "resēdissent" "they (might) have had sat down"

   "resonābat" "he was resounding"
   "resonābant" "they were resounding"
   "resonō, resonāre, resonāvī, resonātus" "to resound"

   "respēxī" "I looked back, considered"
   "respiciēns" "looking back"
   "respicit" "he looked back"
   "respicere" "to look back"
   "respiciō, respicere, respēxī, respectus" "to look back"
   
   "respīrantem" "breathing"
   "respīrō, respīrāre, respīrāvī, respīrātus" "to breathe"

   "respondēbō" "I will respond"
   "respondēns" "responding"
   "respondeō" "I respond"
   "respondet" "he responds"
   "respondēbat" "he was responding"
   "respondēbant" "they were responding"
   "respondērunt" "they responded"
   "respondī" "I responded"
   "respondisset" "he might have had answered"
   "respondit" "he responded"
   "respondēre" "to respond"
   "respondeō, respondēre, respondī, respōnsus" "to respond"

   "responsoria" "responsory, a chant or anthem recited after a reading in a church service"
   "responsorium" "responsories, chants or anthems recited after a reading in a church service"
   "responsoria, responsoriae" "responsory, a chant or anthem recited after a reading in a church service"
   
   "respōnsum" "response"
   "respōnsum, respōnsī" "response"

   "respuimus" "we rejected, spewed out"
   "respuere" "to reject, spew out"
   "respuō, respuere, respuī, respūtus" "to reject, spew out"
   
   "restitit" "he resisted"
   "restitērunt" "they resisted"
   "restituerat" "he had resisted"
   "resistēns" "resisting"
   "resistere" "to resist"
   "resistite" "resist!"
   "resistō, resistere, restitī, -" "to resist"
   
   "restant" "they stay behind, they remain"
   "restat" "it remains"
   "restāret" "he stayed behind, remained"
   "restāre" "to stay behind, to remain"
   "restō, restāre, restitī, -" "to stay behind, to remain"

   "restaurāvērunt" "they restored, rebuilt"
   "restaurāret" "he might restore, rebuild"
   "restaurāre" "to restore, to rebuild"
   "restaurō, restaurāre, restaurāvī, restaurātus" "to restore, to rebuild"

   "resurgentem" "rising again"
   "resurgere" "to rise again, to lift oneself"
   "resurgō, resurgere, resurrēxī, resurrēctus" "to rise again, to lift oneself"
   
   "resurrēctiōnis" "resurrection"
   "resurrēctiōnem" "resurrection"
   "resurrēctiō, resurrēctiōnis" "resurrection"

   "reticēre" "to keep silent"
   "reticeō, reticēre, reticuī, -" "to keep silent"

   "retentus" "having been retained"
   "retinenda" "retaining"
   "retinēbant" "they were holding back, they were retaining"
   "retinent" "they hold back, retain"
   "retinet" "he holds back, retains"
   "retinētur" "he holds back, retains"
   "retinuit" "he retained, held back"
   "retineō, retinēre, retinuī, retentus" "they were holding back, they were retaining"

   "retractantēs" "withdrawing"
   "retractō, retractāre, retractāvī, retractātus" "to withdraw"

   "retribūtiō" "retribution, recompense"
   "retribūtiō, retribūtiōnis" "retribution, recompense"

   "retrōcēdentēs" "receding"
   "retrōcēdere" "to recede"
   "retrōcēdō, retrōcēdere, retrōcessī, retrōcessus" "to recede"

   "revēxit" "he carried back"
   "revehere" "to carry back"
   "revehō, revehere, revēxī, revectus" "to carry back"

   "revēlā" "reveal!"
   "revēlāvīt" "he revealed"
   "revēlārī" "to be revealed"
   "revēlātum" "having been shown, revealed"
   "revēlō, revēlāre, revēlāvī, revēlātus" "to show, to reveal"
   "revēlābō" "I will reveal"
   "revēlāre" "to reveal"
   "revēlēs" "you reveal"
   "revēlante" "revealing"
   
   "revēlātiō" "revelation"
   "revēlātiōnem" "revelation"
   "revēlātiō, revēlātiōnis" "revelation"
   
   "revēlātor" "revealer"

   "revulsī" "having been torn away"
   "revellere" "to tear away"
   "revellō, revellere, revellī, revulsus" "to tear away"

   "revenit" "he returns"
   "revenīre" "to return"
   "reveniō, revenīre, revēnī, reventus" "to return"
   
   "reverentia" "reverence, timidity, shyness"
   "reverentia, reverentiae" "reverence, timidity, shyness"

   "reversiō" "turning back, return"
   "reversiōnem" "turning back, return"
   "reversiō, reversiōnis" "turning back, return"
   
   "revertentēs" "returning"
   "revertāmur" "we (might) return"
   "revertērunt" "they returned"
   "revertī" "I returned"
   "revertit" "he returned"
   "revertiminī" "you return"
   "revertar" "I will return"
   "revertātur" "it might have returned"
   "reversī" "returned"
   "revertam" "I will return"
   "revertere" "to return"
   "revertētis" "you will return"
   "revertite" "return!"
   "revertēbantur" "they were returning"
   "reverterentur" "they (might) been returning"
   "revertendī" "of returning"
   "revertendum" "returning"
   "revertō, revertere, revertī, reversum" "to return"

   "revocāvit" "he revoked"
   "revocāret" "he might revoke"
   "revocāre" "to revoke"
   "revocō, revocāre, revocāvī, revocātus" "to revoke"

   "revolvō" "I turn over, I repeat"
   "revolvō, revolvere, revolvī, revolūtus" "to turn over, to repeat"

   "rēge" "king"
   "rēgem" "king"
   "rēgis" "of the king"
   "rēgēs" "kings"
   "rēgī" "king"
   "rēgibus" "kings"
   "rēgum" "of kings"
   "rēx" "king"
   "rēx, rēgis" "king"

   "Rhēnī"  "The Rhine"
   "rhēnī"  "The Rhine"
   "Rhēnō"  "The Rhine"
   "rhēnō"  "The Rhine"
   "Rhēnum" "The Rhine"
   "rhēnum" "The Rhine"
   "Rhēnus" "The Rhine"
   "rhēnus" "The Rhine"
   "Rhēnus, Rhēnī" "The Rhine"
   "rhēnus, rhēnī" "The Rhine"

   "Rhodanī"  "The Rhone"
   "rhodanī"  "The Rhone"
   "Rhodanō"  "The Rhone"
   "rhodanō"  "The Rhone"
   "Rhodanum" "The Rhone"
   "rhodanum" "The Rhone"
   "Rhodanus" "The Rhone"
   "rhodanus" "The Rhone"
   "Rhodanus, Rhodanī" "The Rhone"
   "rhodanus, Rhodanī" "The Rhone"

   "rīdēns" "laughing"
   "rīdet" "he laughs"
   "rīdēre" "to laugh"
   "rīdeō, rīdēre, rīsī, rīsus" "to laugh"

   "rigor" "rigor, roughness"
   "rigōrem" "rigor, roughness"
   "rigōris" "rigor, roughness"
   "rigor, rigōris" "rigor, roughness"

   "rīmandō" "searching, exploring"
   "rīmor, rīmārī, rīmātus sum" "so search, explore"
   
   "rīpa" "bank, shore"
   "rīpam" "bank, shore"
   "rīpae" "bank, shore"
   "rīpās" "banks, shores"
   "rīpa, rīpae" "bank, shore"

   "rītū" "rite, ceremony"
   "rītus" "rite, ceremony"
   "rītus, rītūs" "rite, ceremony"
   
   "rīvulus" "small brook, rivulet"
   "rīvulī" "small brook, rivulet"
   "rīvulīs" "small brooks, rivulets"
   "rīvulōs" "small brooks, rivulets"
   "rīvulus, rīvulī" "small brook, rivulet"

   "rīvī" "small stream"
   "rīvīs" "small streams"
   "rīvōs" "small streams"
   "rīvus" "small stream"
   "rīvus, rīvī" "small stream"
   
   "rapīnam" "robbery, pillage"
   "rapīna, rapīnae" "robbery, pillage"
   "rōborāminī" "you are strengthened"

   "rōbore" "made of oak"
   "roborīnō" "made of oak"

   "rōbur" "stronghold, oak"
   "rōboris" "stronghold, oak"
   "rōbur, rōboris" "stronghold, oak"
   
   "rōborō, rōborāre, rōborāvī, rōborātus" "to strengthen"

   "rōbustē" "strongly"
   "rōbustus, rōbusta -um, rōbustior -or -us, rōbustissimus -a -um" "strong, oaken"

   "rogābant" "they were asking"
   "rogāns" "asking"
   "rogant" "they ask"
   "rogantēs" "asking"
   "rogāvērunt" "they asked"
   "rogō" "I ask"
   "rogāre" "to ask"
   "rogō, rogāre, rogāvī, rogātus" "to ask"

   "rogitās" "you ask"
   "rogitāre" "to ask"
   "rogitō, rogitāre, rogitāvī, rogitātus" "to ask"
   
   "rogus" "funeral pyre, grave"
   "rogus, rogī" "funeral pyre, grave"

   "rōma" "Rome"
   "rōmae" "Rome"
   "rōmam" "Rome"
   "Rōma, Rōmae" "Rome"

   "rōmāne" "Roman"
   "rōmānae" "Roman"
   "Rōmānī" "Romans"
   "rōmānī" "Romans"
   "rōmānīs" "Romans"
   "rōmānō" "Roman"
   "Rōmānōrum" "Romans"
   "rōmānōrum" "Romans"
   "rōmānōs" "Romans"
   "rōmānum" "Roman"
   "Rōmānus" "Roman"
   "rōmānus" "Roman"
   "Rōmānus, Rōmānī" "Roman"

   "rōmānicī" "Romanic"
   "rōmānicae" "Romanic"
   "rōmānicō" "Romanic"
   "rōmānicus, rōmānica, rōmānicum" "Romanic"

   "rosa" "rose"
   "rosae" "roses"
   "rosam" "rose"
   "rosārum" "of roses"
   "rosās" "roses"
   "rosa, rosae" "rose"

   "rota" "wheel"
   "rotārum" "of wheels"
   "rota, rotae" "wheel"

   "rotantis" "rotating"
   "rotō, rotāre, rotāvī, rotātus" "to rotate"
   
   "rotunda" "round"
   "rotundum" "round"
   "rotundus, rotunda -um, rotundior -or -us, rotundissimus -a -um" "round"
   
   "rubricātīs" "red, reddened"
   "rubricātus, rubricāta, rubricātum" "red, reddened"

   "rubra" "red"
   "rubram" "red"
   "rubea" "red"
   "rubō" "red"
   "rubrum" "red"
   "ruber" "red"
   "ruber, rubra, rubrum" "red"

   "rūbīgō" "rust"
   "rūbīgine" "rust"
   "rūbīgō, rūbīginis" "rust"
   
   "rubus" "thorn bush"
   "rubum" "thorn bush"
   "rubus, rubī" "thorn bush"

   "rudis" "small stick, rod"
   "rudis, rudis" "small stick, rod"

   "rūfus" "red, ruddy"
   "rūfus, rūfa -um, rūfior -or -us, rūfissimus -a -um" "red, ruddy"

   "rūgiēns" "bellowing, roaring"
   "rūgiō, rūgīre, rūgīvī, rūgītus" "to bellow, roar"
   
   "ruīna" "collapse, ruin, destruction"
   "ruīna, ruīnae" "collapse, ruin, destruction"

   "ruit" "it falls, it fell"
   "ruō, ruere, ruī, rūtus" "to fall down"

   "rūmor" "rumor"
   "rūmōrem" "rumor"
   "rūmōris" "rumor"
   "rūmor, rūmōris" "rumor"

   "rumpēns" "breaking, destroying"
   "rumpit" "he breaks, destroys"
   "rūpit" "he broked, destroyed"
   "rupta" "having been broken, destroyed"
   "ruptūrōs" "to be breaking, destroying"
   "rumpere" "to break, destroy"
   "rumpō, rumpere, rūpī, ruptus" "to break, destroy"

   "rūpe" "cliff"
   "rūpēs" "cliff"
   "rūpibus" "cliffs"
   "rūpēs, rūpis" "cliff"

   "rūra" "farms"
   "rūs, rūris" "country"
   
   "rūsticam" "rural"
   "rūsticīs" "rural, rustics"
   "rūsticus" "rural"
   "rūsticus, rūstica, rūsticum" "rural"
   })
