(ns whitakers-clj.dict-v)

(def dict-v
  {"vacca" "cow"
   "vaccae" "cows"
   "vaccās" "cows"
   "vacca, vaccae" "cow"

   "vacua" "empty, vacant"
   "vacuam" "empty, vacant"
   "vacuī"  "empty, vacant"
   "vacuīs" "empty, vacant"
   "vacuum" "empty, vacant"
   "vacuus" "empty, vacant"
   "vacuus, vacua, vacuum" "empty, vacant"

   "vada" "shallows"
   "vadīs" "shallows"
   "vadum" "shallows"
   "vadum, vadī" "shallows"
   
   "vagor, vagārā, vagātus sum" "to wander, to roam"
   "vagāmur" "we wander"
   "vagantēs" "wandering"
   "vagantur" "they wander"
   "vagārentur" "they (might) have wandered"

   "vāgīna" "scabbard, sheath"
   "vāgīnam" "scabbard, sheath"
   "vāgīna, vāgīnae" "scabbard, sheath"

   "vagus" "vagrant"
   "vagus, vagī" "vagrant"

   "vadat" "let it go, advance, hurry"
   "vāde" "go!"
   "vādēns" "going"
   "vādō" "I go"
   "vādit" "he goes"
   "vādunt" "they go"
   "vādere" "to go, to walk"
   "vādō, vādere, vāsī, -" "to go, to walk"

   "valeāmus" "we might be healthy, able, strong"
   "valēbat" "he was healthy, able, strong"
   "valēbunt" "they will be healthy, able, strong"
   "valentēs" "being healthy, able, strong"
   "valuit" "he was healthy, able, strong"
   "valēret" "he might have been healthy, able, strong"
   "valērent" "they were healthy, able, strong"
   "valeātis" "you are healthy, able, strong"
   "valēns" "being well, able"
   "valet" "he is able, well"
   "valent" "they are able"
   "valentia" "being well, able"
   "valuērunt" "they were able"
   "valeō, valēre, valuī, valitūrus" "to be healthy, able, strong"
   "valē" "be well!"

   "valida" "strong, healthy"
   "validō" "strong, healthy"
   "validus, valida, validum" "strong, healthy"

   "valle" "valley"
   "vallem" "valley"
   "vallēs" "valleys"
   "vallibus" "valleys"
   "vallis" "valley"
   "vallis, vallis" "valley"

   "vallum" "wall, rampart"
   "vallum, vallī" "wall, rampart"

   "vānā" "empty, vain"
   "vānus, vāna, vānum" "empty, vain"

   "varia"  "various, diverse"
   "variō"  "various, diverse"
   "variīs" "various, diverse"
   "varius, varia, varium" "various, diverse"

   "vāsīs" "vessels"
   "vās, vāsis" "vessel"
   "vāsa" "vessel"
   
   "vāscula" "small vessel"
   "vāsculīs" "small vessels"
   "vāsculum" "small vessel"
   "vāsculum, vāsculī" "small vessel"
   "vāsculōrum" "of small vessels"

   "vāstāns" "ravaging, devastating"
   "vāstāvit" "he ravaged, devastated"
   "vāstāvērunt" "they ravaged, they devastated"
   "vāstāre" "to lay waste, to devastate, to ravage"
   "vāstō, vāstāre, vāstāvī, vāstātus" "to lay waste, to devastate, to ravage"

   "vāstī" "wild, deserted, empty, immense"
   "vāstus, vāsta -um, vāstior -or -us, vāstissimus -a -um" "wild, deserted, empty, immense"

   "vāticinātiō" "prophecy"
   "vāticinātiōnem" "prophecy"
   "vāticinātiō, vāticinātiōnis" "prophecy"

   "vectīgal" "tax, tribute, revenue"
   "vectīgal, vectīgālis" "tax, tribute, revenue"

   "vehemēns" "vehement, passionate, furious"
   "vehementī" "vehement, passionate, furious"
   "vehementissimō" "very vehement, passionate, furious"
   "vehementissimum" "very vehement, passionate, furious"
   "vehemēns, vehementis (gen.), vehementior -or -us, vehementissimus -a -um" "vehement, passionate, furious"

   "vehēbantur" "was being carried"
   "vehendārum" "of carrying"
   "vehō, vehere, vēxī, vectus" "to carry"

   "vellentēs" "uprooting"
   "vellere" "to uproot"
   "vellō, vellere, vellī, vulsus" "to uproot"
   
   "vēlōcissimō" "very quickly"
   "vēlōx" "quick"
   "vēlōx, vēlōcis (gen.), vēlōcior -or -us, vēlōcissimus -a -um" "very quickly"

   "vēlōcitās" "speed"
   "vēlōcitāte" "speed"
   "vēlōcitās, vēlōcitātis" "speed"
   
   "vēla" "sail, cloth"
   "vēlīs" "sails"
   "vēlum" "sail, cloth"
   "vēlum, vēlī" "sail, cloth"

   "vēnam" "vein, blood vessel"
   "vēnās" "vein, blood vessel"
   "vēna, vēnae" "vein, blood vessel"

   "vēndēbant" "they were selling"
   "vēndēbātur" "it was being sold"
   "vēndendum" "selling"
   "vēndentēs" "selling"
   "vēnderētur" "was being sold"
   "vēndit" "he sells"
   "vēndunt" "they sell"
   "vēndere" "to sell"
   "vēndō, vēndere, vēndidī, vēnditus" "to sell"
   
   "venerābilem" "venerable"
   "venerābilis" "venerable"
   "venerābilis, venerābilis, venerābile" "venerable"
   
   "vēnerat" "he had come"
   "vēnerint" "you will have come"
   "vēnērunt" "they came"
   "vēnēre" "they came"
   "veniēbat" "he was coming"
   "veniēbant" "they were coming"
   "venient" "they will come"
   "veniet" "he will come"
   "venīmus" "we come, we came"
   "venīre" "to come"
   "vēnissēs" "you (might) have had come"
   "vēnisset" "he (might) have had come"
   "ventūrum" "will be coming"
   "venīrent" "they came"
   "vēnistī" "you came"
   "vēnistis" "you came"
   "veniunt" "they come"
   "venīret" "he came"
   "vēnerit" "he will have come"
   "veniēns" "coming"
   "venientem" "coming"
   "venientēs" "coming"
   "veniat" "he came"
   "veniō, venīre, vēnī, ventus" "to come"
   "vēnisse" "to have come"
   "venīrēmus" "we came"
   "veniente" "coming"
   "veniant" "they might come"
   "venientibus" "coming"
   "veniēbāmus" "we were coming"

   "venia" "indulgence, kindness"
   "veniam" "indulgence, kindness"
   "venia, veniae" "indulgence, kindness"
   
   "vēnī" "I came"
   "vēnit" "he came"
   "venīte" "come!"
   "ventūra" "coming (in the future)"
   "ventūrōs" "coming (in the future)"

   "ventitāret" "he was coming regularly"
   "ventitāre" "to come regularly"
   "ventitō, ventitāre, ventitāvī, ventitātus" "to come regularly"
   
   "venter" "belly, abdomen"
   "ventribus" "bellies, abdomens"
   "ventre" "belly, abdomen"
   "ventrem" "belly, abdomen"
   "venter, ventris" "belly, abdomen"

   "ventī"  "of wind"
   "ventum" "wind"
   "ventus" "wind"
   "ventō" "wind"
   "ventus, ventī" "wind"

   "vēr" "spring"
   "vēre" "spring"
   "vēris" "spring"
   "vēr, vēris" "spring"

   "vērācem" "true"
   "vērācissimum" "very true"
   "vērāx" "true"
   "vērāx, vērācis (gen.), vērācior -or -us, vērācissimus -a -um" "true"
   
   "verberibus" "lashes, whips, rods"
   "verber, verberis" "lash, whip, rod"
   
   "verba" "word"
   "verbī" "word"
   "verbīs" "words"
   "verbum" "word"
   "verbum, verbī" "word"

   "vēridicus" "truthful"
   "vēridicus, vēridica, vēridicum" "truthful"

   "veritus" "having been revered, feared"
   "vereor, verērī, veritus sum" "to revere, to fear"

   "vēritāte" "truth"
   "vēritātem" "truth"
   "vēritātis" "truth"
   "vēritātī" "truth"
   "vēritās, vēritātis" "truth"

   "vermēs" "worms"
   "vermis" "worm"
   "vermis, vermis" "worm"
   
   "versibus" "verses, poetic lines"
   "versiculō" "verse, poetic line"
   "versiculum" "verse, poetic line"
   "versiculus, versiculī" "verse, poetic line"

   "versū" "verse, poetic line"
   "versum" "verse, poetic line"
   "versus" "verse, poetic line"
   "versus, versūs" "verse, poetic line"

   "versūtō" "crafty, cunning"
   "versūtus, versūta, versūtum" "crafty, cunning"

   "vertērunt" "they turned"
   "vertit" "he turns"
   "vertitur" "he is turned"
   "versī" "having been turned"
   "vertere" "to turn, to change"
   "vertō, vertere, vertī, versus" "to turn, to change"

   "vertice" "head, top, peak"
   "verticem" "head, top, peak"
   "vertex, verticis" "head, top, peak"

   "vēra" "true"
   "vērī" "of the true"
   "vērum" "true"
   "vērus" "true"
   "vērus, vēra -um, vērior -or -us, vērissimus -a -um" "true"
   
   "vesperā" "evening"
   "vesperam" "evening"
   "vesperās" "evening"
   "vespere" "evening"
   "vespera, vesperae" "evening"

   "vesperum" "evening"
   "vesper, vesperis" "evening"
   
   "vespertīnum" "evening"
   "vespertīna" "evening"
   "vespertīnās" "evening"
   "vespertīnus, vespertīna, vespertīnum" "evening"
   
   "vester" "your"
   "vester, vestra, vestrum" "your"

   "vestīgia" "footsteps, footprints"
   "vestīgium, vestīgiī" "footsteps, footprints"
   
   "vestīmenta" "clothes"
   "vestīmentī" "clothing"
   "vestīmentīs" "clothes"
   "vestīmentōrum" "clothes"
   "vestīmentum" "clothing"
   "vestīmentum, vestīmentī" "clothing, clothes"

   "veste" "clothing"
   "vestibus" "clothing"
   "vestis, vestis" "clothing"

   "vestī" "dress! clothe!"
   "vestit" "he clothes"
   "vestītur" "it is worn"
   "vestīre" "to clothe"
   "vestiō, vestīre, vestīvī, vestītus" "to clothe"

   "vetet" "he (might) reject"
   "vetō, vetāre, vetuī, vetitus" "to forbid, to reject"

   "veterī" "old"
   "veteribus" "old"
   "veteris" "old"
   "veterum" "of old"
   "vetus" "old"
   "vetus, vetus, vetus" "old"
   
   "vexentur" "they (might) be vexing"
   "vexātōrum" "having been vexed"
   "vexō, vexāre, vexāvī, vexātus" "to vex, to trouble"

   "vexilla" "flags, banners"
   "vēxillō"  "flag, banner"
   "vexillum" "flag, banner"
   "vexillī" "flag, banner"
   "vexillum, vexillī" "flag, banner"
   
   "via" "road"
   "viae" "road"
   "viam" "road"
   "viīs" "roads"
   "via, viae" "road"

   "vicecomes" "vice-count"
   "vicecomitem" "vice-count"
   "vicecomes, vicecomitis" "vice-count"

   "vīcēsimō" "twentieth"
   "vīcēsimus, vīcēsima, vīcēsimum" "twentieth"

   "vīcīna"  "neighbor"
   "vīcīnae" "neighbors"
   "vīcīna, vīcīnae" "neighbor"
   
   "vice" "time, turn"
   "vicis" "time, turn"
   "vīcīs" "time, turn"
   "vīcōs" "time, turn"
   "vicum" "of times, turns"
   "vicis, vicis" "time, turn"
   "vicibus" "times"
   
   "victima" "sacrificial victim"
   "victimās" "sacrificial victims"
   "victimīs" "sacrificial victim"
   "victima, victimae" "sacrificial victim"

   "victor" "victor"
   "victōre" "victor"
   "victōrēs" "victors"
   "victor, victōris" "victor"

   "victōria" "victory"
   "victōriam" "victory"
   "victōriās" "victory"
   "victōria, victōriae" "victory"

   "victrīx" "conqueror"
   "victrīcis" "conqueror"
   "victrīx, victrīcis" "conqueror"
   
   "victus" "victuals, nourishment, necessaries of life"
   "victūs" "victuals, nourishment, necessaries of life"
   "victus, victūs" "victuals, nourishment, necessaries of life"
   
   "vidē" "look!"
   "videātur" "he (might) appear"
   "vidēbātur" "he were appearing"
   "vidēbantur" "they were appearing"
   "videntibus" "looking"
   "vīderant" "they had seen"
   "videt" "he sees"
   "vidētur" "he appears"
   "videō" "I see"
   "vīdī" "I saw"
   "videō, vidēre, vīdī, vīsus" "to see"
   "videāmus" "we (might) see"
   "vidēbis" "you will see"
   "vidēbitis" "you will see"
   "vidēbunt" "they will see"
   "vidēmus" "we see"
   "vidēs" "you see"
   "vidēre" "to see"
   "vidērent" "they (might) have seen"
   "vidērētur" "he may have appeared"
   "vidēte" "look!"
   "vidētis" "you see"
   "vīdistis" "you saw"
   "vīdit" "he saw"
   "vīdērunt" "they saw"
   "vidērentur" "he (may) have appeared"
   "vīdisset" "he (might) have had seen"
   "vīdissent" "they (might) have had seen"
   "vidērēmur" "we (might) have appeared"
   "vīdimus" "we saw"
   "vīdistī" "you saw"
   "vidērī" "to appear"
   "vidēbat" "he was living"
   "videndum" "seeing, watching"
   "videndī" "of seeing"
   "vidēns" "seeing"
   "vidēret" "he saw"
   "videās" "you may see"
   "videntēs" "seeing"
   "vident" "they see"
   "vīsum" "to have been seen"

   "vigil" "vigil, sentry, watch"
   "vigil, vigilis" "vigil, sentry, watch"
   "vigiliā" "vigil, watch"
   "vigiliam" "vigil, watch"
   "vigiliārum" "vigil, watch"
   "vigiliās" "vigil, watch"
   "vigiliīs" "vigils, watches"
   "vigilia, vigiliae" "vigil, watch"
   "vigilābant" "they were watching, they were alert"
   "vigilō" "I am awake, I watch"
   "vigilā" "wake up!"
   "vigilāvit" "he woke up"
   "vigilandī" "of waking up"
   "vigilandum" "waking up"
   "vigilāns" "staying awake, waking up"
   "vigilant" "they keep watch"
   "vigilantēs" "keeping watch, waking up"
   "vigilat" "he keeps watch"
   "vigilāre" "to wake up"
   "vigilō, vigilāre, vigilāvī, vigilātus" "to be awake, to watch for"

   "vīlī" "cheap, worthless"
   "vīlissima" "most cheap, worthless"
   "vīlissimum" "most cheap, worthless"
   "vīlis, vīlis, vīle" "cheap, worthless"

   "vīlla"  "farm, villa"
   "vīllae" "farms, villas"
   "vīllam" "farm, villa"
   "vīllās" "farm, villa"
   "vīlla, vīllae" "farm, villa"

   "vīcerint" "they will have conquered"
   "vincēbantur" "they were conquered"
   "vīctī" "having been conquered"
   "vincendī" "conquering"
   "vincent" "they will conquer"
   "vincentur" "they will be conquered"
   "vīctūra" "conquering"
   "vīctūrī" "conquering"
   "vincere" "to conquer"
   "vincō, vincere, vīcī, victus" "to conquer"

   "vincula" "chains"
   "vinculīs" "chains"
   "vinculum" "chain"
   "vinculum, vinculī" "chain"

   "vindicā" "vindicate!"
   "vindicandum" "vindicating"
   "vindicāvit" "he vindicated, avenged"
   "vindicō, vindicāre, vindicāvī, vindicātus" "to vindicate, avenge"

   "vindicta"  "protection, revenge, punishment"
   "vindictam" "protection, revenge, punishment"
   "vindicta, vindictae" "protection, revenge, punishment"

   "vīnea" "vineyard"
   "vīneās" "vineyards"
   "vīnea, vīneae" "vineyard"

   "vīnī" "wine"
   "vīnō" "wine"
   "vīnum" "wine"
   "vīnum, vīnī" "wine"

   "violentia" "violence"
   "violentia, violentiae" "violence"
   
   "violet" "he (might) violate"
   "violāre" "to violate"
   "violō, violāre, violāvī, violātus" "to violate"
   
   "virentibus" "green"
   "viridis" "green"
   "viride" "green"
   "viridis, viridis, viride" "green"
   
   "vireō, virēre, viruī, -" "to be green, to be vigorous"
   "vir" "man"
   "virī" "man"
   "virīs" "men"
   "vir, virī" "man"
   "virō" "man"
   "virōrum" "of the men"
   "virōs" "men"
   "virum" "man"

   "virgam" "stick"
   "virga, virgae" "stick"

   "virgine" "virgin"
   "virginem" "virgin"
   "virginēs" "virgins"
   "virginis" "virgin"
   "virgō" "virgin"
   "virgō, virginis" "virgin"
   
   "virtūs" "virtue, manliness, power"
   "virtūtē" "virtue, manliness, power"
   "virtūtēs" "virtue, manliness, power"
   "virtūtem" "virtue, manliness, power"
   "virtūtibus" "virtues, manliness, power"
   "virtutum" "of virtues, manliness, power"
   "virtūs, virtūtis" "virtue, manliness, power"

   "vim" "strength"
   "vīrēs" "strength"
   "vīribus"  "strength"
   "vī" "strength"
   "vīs, vīs" "strength, power"
   
   "vīsitābō" "I will visit"
   "vīsiōne"  "vision"
   "vīsiōnem" "vision"
   "vīsiō, vīsiōnis" "vision"

   "vīsitāvissem" "I (might) have had visited"
   "vīsitāre" "to visit"
   "vīsitō, vīsitāre, vīsitāvī, vīsitātus" "to visit"

   "vīsus" "appearance"
   "vīsus, vīsūs" "appearance"
   
   "vīta" "life"
   "vītam" "life"
   "vītae" "life"
   "vīta, vītae" "life"

   "vītīs" "vines"
   "vītis, vītis" "vine"

   "vītāret" "they were avoiding"
   "vītāre" "to avoid"
   "vītō, vītāre, vītāvī, vītātus" "to avoid"

   "vitellus" "small calf"
   "vitellus, vitellī" "small calf"
   
   "vitium" "vice, crime"
   "vitiī" "vice, crime"
   "vitiīs" "vices, crimes"
   "vitium, vitiī" "vice, crime"

   "vitream" "of glass, glassy, resemblingg glass in its color (greenish), translucency, or glitter"
   "vitreus, vitrea, vitreum" "of glass, glassy, resemblingg glass in its color (greenish), translucency, or glitter"
   
   "vitreum" "glass"
   "vitreum, vitreī" "glass"

   "vitulus" "calf"
   "vitulī"  "calf"
   "vitulīs" "calves"
   "vitulō" "calf"
   "vitulōs" "calves"
   "vitulum" "calf"
   "vitulus, vitulī" "calf"

   "vīvificāre" "to bring to life"
   "vīvificō, vīvificāre, vīvificāvī, vīvificātus" "to bring to life"
   
   "vīvēbam" "I was living"
   "vīvēbat" "he was living"
   "vīvēbant" "they were living"
   "vīvere" "to live"
   "vīvit" "he lives"
   "vīvunt" "they live"
   "vīvō" "I live"
   "vīxit" "he lived"
   "vīveret" "he might live"
   "vīvēbāmus" "we were living"
   "vīvō, vīvere, vīxī, vīctus" "to live"

   "vīvī" "living"
   "vīvōs" "those alive"
   "vīvum" "alive"
   "vīvus" "alive"
   "vīvus, vīva, vīvum" "alive"

   "vocābātur" "it was being called, summoned"
   "vocantur" "they are called"
   "vocārētur" "he (might) have been called"
   "vocārī" "to be called"
   "vocātur" "it is called"
   "vōcibus" "voices"
   "vocāvit" "he called"
   "vocātum" "having been called"
   "vocer" "I am being called"
   "vocentur" "they were called"
   "vocāris" "you will have been called"
   "vocat" "he calls"
   "vocor" "I am called"
   "vocandō" "calling"
   "vocātus" "having been called"
   "vocātī" "having been called"
   "vocāta" "having been called"
   "vocāre" "to call, to summon"
   "vocant" "they call"
   "vocō, vocāre, vocāvī, vocātus" "to call, to summon"

   "vōciferātus" "having been yelled"
   "vōciferantēs" "crying, yelling"
   "vōciferō, vōciferāre, vōciferāvī, vōciferātus" "to cry, yell"

   "vocitant" "they call"
   "vocitābant" "they called"
   "vocitātō"  "having been called"
   "vocitātus" "having been called"
   "vocitātur" "it is called"
   "vocitāre" "to call"
   "vocitō, vocitāre, vocitāvī, vocitātus" "to call"
   
   "volātū" "flying, flight"
   "volātus" "flying, flight"
   "volātus, volātūs" "flying, flight"

   "volitārent" "they might have been flying"
   "volitāre" "to fly"
   "volitō, volitāre, volitāvī, volitātus" "to fly"

   "volat" "he flies"
   "volant" "they fly"
   "volābat" "he was flying"
   "volāre" "to fly"
   "volō, volāre, volāvī, volātus" "to fly"

   "volueritis" "you will have wanted"
   "voluerit" "he will have wanted"
   "vellet" "he was wanting"
   "vellent" "they (might) have been wanting"
   "volēbat" "he was wanting"
   "volēbant" "they were wanting"
   "volō" "I want"
   "voluisset" "he (might) have had wanted"
   "voluērunt" "they wanted"
   "voluit" "he wanted"
   "volumus" "we want"
   "vīs" "you want"
   "velint" "they (might) want"
   "voluī" "I wanted"
   "volens" "wanting"
   "velle" "to want"
   "volō, velle, voluī, -" "to want"
   "volentēs" "willing"
   "voluissent" "they had wanted"
   "vellētis" "you might have wished"
   "voluissem" "I had wished"
   "voluistī" "you wanted"
   "voluerint" "they might have wanted"

   "voluminibus" "books, volumes"
   "volūmen" "book, volume"
   "volūmen, volūminis" "book, volume"
   
   "vōcem" "voice"
   "vōx" "voice"
   "vōx, vōcis" "voice"
   "vōce" "voice"
   "vōcēs" "voices"
   
   "volāns" "flying"
   "volāvit" "he flew"

   "voluistis" "you wanted"
   "voluntās" "will"
   "voluntāte" "will"
   "voluntātem" "will"
   "voluntās, voluntātis" "will"
   
   "volvissent" "they (might) have had rolled"
   "volvitur" "it is rolled"
   "volvēns" " rolling, tumbling"
   "volvō, volvere, volvī, volūtum" "to roll, to tumble"

   "vorāginis" "abyss, gulf, depth"
   "vorāgō" "abyss, gulf, depth"
   "vorāgine" "abyss, gulf, depth"
   "vorāgō, vorāginis" "abyss, gulf, depth"
   
   "vōs" "you"

   "vōta" "vows"
   "vōtī" "vow"
   "vōtīs" "vows"
   "vōtum" "vow"
   "vōtum, vōtī" "vow"

   "vulnerandō" "wounding"
   "vulnerātī"  "having been wounded"
   "vulnerātus" "having been wounded"
   "vulnerāre" "to wound"
   "vulnerō, vulnerāre, vulnerāvī, vulnerātus" "to wound"
   
   "vulneribus" "wounds"
   "vulnus" "wound"
   "vulnus, vulneris" "wound"
   
   "vultū" "face, expression, appearance"
   "vultum" "face, expression, appearance"
   "vultus, vultūs" "face, expression, appearance"
   })
