(ns whitakers-clj.dict-t)

(def dict-t
  {"tabellārium""letter carrier"
   "tabellārius" "letter carrier"
   "tabellāriō" "letter carrier"
   "tabellāriōs" "letter carriers"
   "tabellārius, tabellāriī" "letter carrier"

   "tabella" "writing-tablet"
   "tabellīs" "writing-tablets"
   "tabella, tabellae" "writing-tablet"

   "taberna"  "shop"
   "tabernā"  "shop"
   "tabernae" "shop"
   "tabernam" "shop"
   "tabernās" "shop"
   "taberna, tabernae" "shop"

   "tabernāriī" "storekeeper's"
   "tabernāriīs" "storekeepers"
   "tabernāriō"  "storekeeper"
   "tabernārius" "storekeeper"
   "tabernārius, tabernāriī" "storekeeper"
   
   "tabula" "tablet"
   "tabulā" "tablet"
   "tabulae" "tablets"
   "tabulam" "tablet"
   "tabula, tabulae" "tablet"

   "tacē" "be silent!"
   "tacēbat" "he was being silent"
   "tacendī" "of being silent"
   "tacendum" "being silent"
   "tacēre" "to be silent"
   "tacet" "he is silent"
   "tacent" "they are silent"
   "tacuit" "he was silent"
   "taceō, tacēre, tacuī, tacitus" "to be silent"

   "taediōsus" "tedious, wearisome"
   "taediōsus, taediōsa, taediōsum" "tedious, wearisome"
   
   "taediō" "weariness, tedium"
   "taedium" "weariness, tedium"
   "taedium, taediī" "weariness, tedium"

   "talenta" "talents (a measure of weight)"
   "talentum" "talent (a measure of weight)"
   "talentī" "talent (a measure of weight)"
   "talentum, talentī" "talent (a measure of weight)"
   
   "tālem" "such"
   "tālēs" "such"
   "tālia" "such"
   "tālibus" "such"
   "tālis" "such"
   "tālis, tālis, tāle" "such"
   
   "tanta" "so much, so great, this many"
   "tantī" "so much, so great, this many"
   "tantō" "so much, so great, this many"
   "tantam" "so much, so great, this many"
   "tantās" "so much, so great, this many"
   "tantōrum" "so much, so great, this many"
   "tantum" "so much, so great, this many"
   "tantus" "so much, so great, this many"
   "tantus, tanta, tantum" "so much, so great, this many"

   "tetigī" "I touched"
   "tetigit" "he touched"
   "tangit" "he touches"
   "tangere" "to touch, to strike"
   "tangō, tangere, tetigī, tāctus" "to touch, to strike"

   "tardum" "slow"
   "tardus, tarda -um, tardior -or -us, tardissimus -a -um" "slow"

   "tēctum" "having been covered"
   "tēctus" "having been covered"
   "tegēbant" "they were covering, hiding"
   "tegit" "it covers, hides"
   "tegitur" "it is covered, hidden"
   "tegō, tegere, tēxī, tēctus" "to cover, hide"

   "televisōrium" "television"
   "televisōrium, televisōriī" "television"

   "tellūs" "earth, territory"
   "tellūs, tellūris" "earth, territory"

   "tēla" "spears"
   "tēlōrum" "of spears"
   "tēlum, tēlī" "spear"

   "tēmō" "pole, wagon"
   "tēmōnem" "pole, wagon"
   "tēmōnis" "pole, wagon"
   "tēmō, tēmōnis" "pole, wagon"

   "temperātūrōs" "to be tempered, moderated"
   "temperāre" "to temper, to moderate"
   "temperō, temperāre, temperāvī, temperātus" "to temper, to moderate"

   "tempestātēs" "storms"
   "tempestās" "weather, storm"
   "tempestās, tempestātis" "weather, storm"
   
   "templum" "temple"
   "templī"  "temple"
   "templum, templī" "temple"

   "temptābat" "he was tempting"
   "temptāns" "tempting"
   "temptant" "they tried"
   "temptāvēre" "they tempted"
   "temptāvit" "he tried"
   "temptāre" "to tempt"
   "temptō, temptāre, temptāvī, temptātus" "to tempt"
   
   "temptātiōnem" "temptation"
   "temptātiō, temptātiōnis" "temptation"
   
   "tempora" "times, periods"
   "tempus" "time, period"
   "tempore" "time, period"
   "temporis" "of times, of periods"
   "temporibus" "of times, of periods"
   "temporum" "of times, of periods"
   "tempus, temporis" "time, period"
   
   "tendite" "hold!"
   "tenuit" "he held, he had"
   "tenuērunt" "they held"
   "teneat" "he holds"
   "teneant" "they (might) hold"
   "tenēbat" "he was holding"
   "tenēbant" "they were holding"
   "tenēbantur" "they were held"
   "tenēns" "holding"
   "tenente" "holding"
   "tenentēs" "holding"
   "tenet" "he holds"
   "tenuissent" "they (might) have had held"
   "tenēre" "to hold"
   "tenēbunt" "they will hold"
   "tenenda" "holding"
   "tenendae" "holding"
   "tenent" "they hold"
   "tenuēre" "they held, alternative spelling of tenuērunt"
   "teneō, tenēre, tenuī, tentus" "to hold, to keep"
   "tenēret" "he might hold"
   "tenuerant" "they had had"
   "teneō" "I hold, keep"
   "tenē" "hold!"
   
   "tenebrōsus" "dark"
   "tenebrōsus, tenebrōsa, tenebrōsum" "dark"

   "tenebrae" "darkness"
   "tenebrārum" "of darkness"
   "tenebrae, tenebrārum" "darkness"

   "tenerrimē" "very tenderly"
   "tener, tenera -um, tenerior -or -us, tenerrimus -a -um" "soft, tender, delicate"

   "tenōre" "course, tenor"
   "tenor, tenōris" "course, tenor"

   "tentōria" "tents"
   "tentōrium" "tent"
   "tentōriō" "tent"
   "tentōriī" "tent"
   "tentōriīs" "tents"
   "tentōrium, tentōriī" "tent"

   "tenuēs" "thin, slender, weak"
   "tenuis" "thin, slender, weak"
   "tenuis, tenue, tenuior -or -us, tenuissimus -a -um" "thin, slender, weak"

   "teris" "you rub, you wear out"
   "terō, terere, trīvī, trītus" "to rub, to wear out"

   "tergē" "wipe dry!"
   "terget" "he wipes dry"
   "tergēns" "wiping"
   "tergēre" "to wipe dry"
   "tergeō, tergēre, tersī, tersus" "to wipe dry"

   "terga" "back"
   "tergī" "back"
   "tergō" "back"
   "tergum, tergī" "back"

   "terminī" "end, boundary, limit"
   "terminō" "end, boundary, limit"
   "terminōs" "ends, boundaries, limits"
   "terminum" "end, boundary, limit"
   "terminus" "end, boundary, limit"
   "terminus, terminī" "end, boundary, limit"
   
   "ternōs" "three each"
   
   "terra" "land"
   "terrae" "land"
   "terrās" "lands"
   "terrīs" "lands"
   "terra, terrae" "land"
   "terrārum" "of lands"

   "terrēnum" "land, ground"
   "terrēnum, terrēnī" "land, ground"

   "terrēnīs" "earthly"
   "terrēnus, terrēna, terrēnum" "earthly"

   "terrērentur" "they were being frightened"
   "terret" "he terrifies"
   "territa" "having been frightened"
   "territum" "having been frightened"
   "territus" "having been frightened"
   "terruērunt" "they frightened"
   "terruit" "he frightened"
   "terrēre" "to frighten"
   "terreō, terrēre, terruī, territus" "to frighten"

   "terror" "terror"
   "terrōrī" "terror"
   "terrōris" "terror"
   "terrōre" "terror"
   "terror, terrōris" "terror"
   
   "tetendit" "he stretched, he extended"
   "tetendērunt" "they stretched, they extended"
   "tendēbant" "they were stretching"
   "tetendimus" "we stretched out, extended"
   "tendere" "to stretch, to extend"
   "tendō, tendere, tetendī, tentus" "to stretch, to extend"

   "testamenti" "of a will, of a testament"
   "testāmentum, testāmentī" "will, testament"

   "testimōniō" "witness, evidence"
   "testimōnium, testimōniī" "witness, evidence"

   "tēterrimum" "very foul, ugly"
   "tēter, tētra -um, tētrior -or -us, tēterrimus -a -um" "foul, ugly"

   "textūra" "weaving, texture"
   "textūra, textūrae" "weaving, texture"

   "thēsaurīs" "treasures"
   "thēsaurus" "treasure"
   "thēsaurus, thēsaurī" "treasure"
   
   "thronum" "throne"
   "thronus, thronī" "throne"

   "tībiam" "leg"
   "tībia, tībiae" "leg"
   
   "timēbant" "they were fearing"
   "timēbis" "you will fear"
   "timētis" "you fear"
   "timuērunt" "they feared"
   "timuistis" "you feared"
   "timenda" "to be feared"
   "timēns" "fearing"
   "timentēs" "fearing"
   "timeās" "you fear"
   "timeat" "it might fear"
   "timēbat" "he was fearing"
   "timent" "they fear"
   "timeō" "I fear"
   "timuisse" "to have feared"
   "timuit" "he feared"
   "timet" "he fears"
   "timēre" "to fear"
   "timeō, timēre, timuī, -" "to fear"

   "timor" "fear"
   "timōre" "fear"
   "timōrem" "fear"
   "timōrēs" "fears"
   "timor, timōris" "fear"

   "tīncta" "having been soaked, colored, imbued"
   "tinguō, tinguere, tīnxī, tīnctus" "to soak, color, imbue"

   "titulī"  "inscription, token"
   "titulus" "inscription, token"
   "titulus, titulī" "inscription, token"
   
   "tintinnābulum" "bell"
   "tintinnābulum, tintinnābulī" "bell"

   "toga" "toga"
   "togam" "toga"
   "toga, togae" "toga"

   "togātō"  "wearing a toga"
   "togātus" "wearing a toga"
   "togātus, togāta, togātum" "wearing a toga"

   "tollēbant" "they were taking up"
   "tollat" "he (might) lift up"
   "tollant" "they (might) lift up"
   "sublāta" "having been lifted up"
   "sustulerant" "they had lifted up"
   "tollō, tollere, sustulī, sublātus" "to raise up"

   "tondē" "cut! shear!"
   "tondeō, tondēre, totondī, tōnsus" "to cut, to shear"
   
   "tormenta" "torments"
   "tormentī" "torment"
   "tormentīs" "torments"
   "tormentōrum" "of torments"
   "tormentum, tormentī" "torment, cannon"

   "torpor" "numbness, stupefaction"
   "torpore" "numbness, stupefaction"
   "torpōris" "numbness, stupefaction"
   "torpor, torpōris" "numbness, stupefaction"

   "torrentem" "torrent"
   "torrentis" "torrent"
   "torrēns, torrentis" "torrent"
   
   "tōta" "whole, total"
   "tōtam" "whole, total"
   "tōtī" "whole, total"
   "tōtius" "of the whole"
   "tōtō" "whole, total"
   "tōtum" "whole, total"
   "tōtus" "whole, total"
   "tōtīs" "whole, total"
   "tōtus, tōta, tōtum (gen -ius)" "whole, total"

   "tractāns" "hauling, dragging, handling, discussing"
   "tractāre" "to haul, to drag, to handle, to discuss"
   "tractārent" "they might have been hauling, dragging, handling"
   "tractō, tractāre, tractāvī, tractātum" "to haul, to drag, to handle, to discuss"

   "trādam" "I might hand over"
   "trādēbātur" "he was handed over"
   "trādita" "having been handed over"
   "trāditae" "having been handed over"
   "trādiderat" "he had handed over"
   "trādidit" "he handed over"
   "trādidimus" "we handed over"
   "trādidistī" "you handed over"
   "trāditur" "it is handed over"
   "trādiderant" "they had handed over"
   "trādidērunt" "they had handed over"
   "trāderet" "he handed over"
   "trādētur" "it will be handed over"
   "trāde" "hand over!"
   "trādere" "to hand over"
   "trādō, trādere, trādidī, trāditus" "to hand over"

   "trāditiōne" "surrender, delivering up"
   "trāditiō, trāditiōnis" "surrender, delivering up"
   
   "trāditor" "traitor"
   "trāditor, trāditōris" "traitor"
   
   "trahēbat" "he was drawing, he was dragging"
   "trahentēs" "drawing, dragging"
   "trahit" "he draws, drags"
   "trahitur" "it is drawn"
   "trahuntur" "they are drawn, dragged"
   "traherent" "they might draw, drag"
   "traheret" "he might draw, drag"
   "trahere" "to draw, to drag"
   "trahī" "to be drawn, dragged"
   "trahō, trahere, trāxī, tractus" "to draw, to drag"

   "trāiēcerat" "they had transferred, transported"
   "trāiciēns" "transfering, transporting, passing through"
   "trāiciō, trāicere, trāiēcī, trāiectus" "to transfer, transport, pass through"

   "trāmes" "footpath"
   "trāmite" "footpath"
   "trāmes, trāmitis" "footpath"
   
   "tranquillitās" "tranquility"
   "tranquillitātis" "tranquility"
   "tranquillitās, tranquillitātis" "tranquility"
   "tranquillitāte" "tranquility"

   "trānscenderet" "he was stepping over"
   "trānscēnsīs" "having been stepped over"
   "trānscendō, trānscendere, trānscendī, trānscēnsus" "to step over"
   
   "trānsāctā" "having been accomplished"
   "trānsactō" "having been accomplished"
   "trānsactīs" "having been accomplished"
   "trānsigō, trānsigere, trānsēgī, trānsactum" "to stab, to pierce, to accomplish"

   "trānsfretantēs" "passing over, ferrying"
   "trānsfretāret" "he passed over, ferried"
   "trānsfretāvērunt" "they passed over, ferried"
   "trānsfretāssent" "they might have crossed over, ferried"
   "trānsfretāvit" "he passed over the sea, ferried"
   "trānsfretō, trānsfretāre, trānsfretāvī, trānsfretātus" "to pass over the sea, to ferry"

   "trānsgressō" "transgressor"
   "trānsgressor" "transgressor"
   "trānsgressōris" "transgressor"
   "trānsgressor, trānsgressōris" "transgressor"
   
   "trānsītur" "being crossed"
   "trānsībat" "he was going over, he was crossing"
   "trānsīvisset" "he (might) have had crossed"
   "transivit" "he crossed"
   "trānsīre" "to go over, to cross"
   "trānsisse" "to have crossed"
   "trānsivisse" "to have crossed"
   "trānsiverant" "they had gone over, they had crossed over"
   "trānsivērunt" "they went over, they crossed over"
   "trānseuntium" "crossing"
   "trānsitūrum" "will be crossing over"
   "trānsīret" "he crossed over"
   "trānsīrēmus" "we crossed over"
   "trānseō, trānsīre, trānsivi(iī), trānsitus" "to go over, to cross"

   "trānsēgit" "he stabbed, accomplished"
   "trānsigō, trānsigere, trānsēgī, trānsactus" "to stab, accomplish"

   "trānsmarīnīs" "overseas"
   "trānsmarīnus" "overseas"
   "trānsmarīnus, trānsmarīna, trānsmarīnum" "overseas"
   
   "trānsmeāre" "to go across, to pass over"
   "trānsmeō, trānsmeāre, trānsmeāvī, trānsmeātus" "to go across, to pass over"

   "trānsmigrātiōne"  "transmigration"
   "trānsmigrātiōnem" "transmigration"
   "trānsmigrātiō, trānsmigrātiōnis" "transmigration"

   "trānsmissō" "having been sent"
   "trānsmittam" "I will send"
   "trānsmittēbant" "they sent across"
   "trānsmittō, trānsmittere, trānsmīsī, trānsmissus" "to send"
   
   "trāxit" "he hauled, he discussed"
   "trāns" "across, beyond"

   "trānsportāverat" "he had carried across"
   "trānsportandum" "to carry across"
   "trānsportō, trānsportāre, trānsportāvī, trānsportātus" "to carry across"

   "trānsverberāvit" "he pierced through"
   "trānsverberō, trānsverberāre, trānsverberāvī, trānsverberātus" "to pierce through"
   
   "tertia" "third"
   "tertium" "third"
   "tertius" "third"
   "tertiam" "third"
   "tonitruum" "thunder"
   "tonitruum, tonitruī" "thunder"
   "trēs" "three"
   "tertiō" "third"
   "trēs -es -ia, tertius -a -um, terni -ae -a, ter" "third"
   "tribus" "three"

   "trecentī" "three hundred"
   "trecentīs" "three hundred"
   "trecentī -ae -a, trecentesimus -a -um, trecenī -ae -a, trecentie (n)s" "three hundred"

   "tremefactī"  "having been caused to tremble"
   "tremefactus" "having been caused to tremble"
   "tremefacere" "to cause to tremble"
   "tremefaciō, tremefacere, tremefēcī, tremefactus" "to cause to tremble"

   "tremens" "trembling"
   "tremis" "you tremble"
   "tremō" "I tremble"
   "tremere" "to tremble"
   "tremō, tremere, tremuī, - " "to tremble"

   "trepidōs" "agitated, nervous"
   "trepidus, trepida, trepidum" "agitated, nervous"

   "trībulātiō" "distress, trouble, tribulation"
   "trībulātiōne" "distress, trouble, tribulation"
   "trībulātiōnēs" "distresses, troubles, tribulations"
   "trībulātiōnis" "distress, trouble, tribulation"
   "trībulātiō, trībulātiōnis" "distress, trouble, tribulation"
   
   "tribuam" "I will assign"
   "tribuent" "they will assign"
   "tribuit" "he divides, assigns"
   "tribuere" "to divide, to assign, to attribute"
   "tribuō, tribuere, tribuī, tribūtus" "to divide, to assign, to attribute"

   "tribūtāriās" "relating to tribute"
   "tribūtārius, tribūtāria, tribūtārium" "relating to tribute"

   "tribūnī" "tribunes"
   "tribūnus, tribūnī" "tribunes"
   
   "triduānās" "three days"
   "trīduānīs" "three days"
   "triduānum" "three days"
   "triduānō" "three days"
   "triduānōs" "three days"
   "triduāna, triduānae" "three days"
   
   "trīnitās" "Trinity"
   "trīnitāte" "Trinity"
   "trīnitātem" "Trinity"
   "trīnitātī" "Trinity"
   "trīnitātis" "Trinity"
   "trīnitās, trīnitātis" "Trinity"

   "trīnō"  "triple"
   "trīnum" "triple"
   "trīnus" "triple"
   "trīnus, trīna, trīnum" "triple"

   "triplex" "triple"

   "tripudiō" "dance, favorable omen"
   "tripudium" "dance, favorable omen"
   "tripudium, tripudī" "dance, favorable omen"
   
   "trīstēs" "sad"
   "tristia" "sad"
   "trīstibus" "sad"
   "trīstis" "sad"
   "trīstis, trīstis, trīste" "sad"

   "trīstitia" "sadness"
   "trīstitiam" "sadness"
   "trīstitia, trīstitiae" "sadness"
   
   "trium" "three"

   "triumphābant" "they were celebrating, rejoicing"
   "triumphantēs" "celebrating, rejoicing"
   "triumphāre" "to celebrate, rejoice"
   "triumphō, triumphāre, triumphāvī, triumphātus" "to celebrate, rejoice"

   "triumphō" "triumph"
   "triumphus, triumphī" "triumph"

   "troiānum" "Trojan"
   "Trojānus, Trojāna, Trojānum" "Trojan"
   
   "trophaeō" "sign, trophy"
   "trophaeum" "sign, trophy"

   "truncāvērunt" "they maimed, mutilated"
   "truncāre" "to maim, mutilate"
   "truncō, truncāre, truncāvī, truncātus" "to maim, mutilate"
   
   "tu" "you"
   "tua" "you"
   "tuae" "your"
   "tuam" "your"
   "tuās" "yours"
   "tuī" "your"
   "tuīs" "yours"
   "tuō" "your"
   "tuōs" "your"
   "tuārum" "of your"

   "tuendam" "looking at, protecting"
   "tueor, tuērī, tuitus sum" "to look at, protect"

   "tumba" "tomb"
   "tumbās" "tombs"
   "tumba, tumbae" "tomb"

   "tumēbant" "they were swelling up"
   "tumeō, tumēre, -, -" "to be swollen, puffed up"

   "tumidī" "swollen, pompous"
   "tumidus, tumida, tumidum" "swollen, pompous"

   "tumultū" "uproar"
   "tumultus" "uproar"
   "tumultus, tumultūs" "uproar"

   "tumulī" "mound, hill"
   "tumulīs" "mounds, hills"
   "tumulō" "mound, hill"
   "tumulum" "mound, hill"
   "tumulus" "mound, hill"
   "tumulus, tumulī" "mound, hill"

   "tunica" "tunic, undergarment"
   "tunicam" "tunic, undergarment"
   "tunica, tunicae" "tunic, undergarment"

   "turba" "disturbance, quarrel, troop"
   "turbae" "disturbance, quarrel, troop"
   "turbam" "disturbance, quarrel, troop"
   "turbīs" "disturbances, quarrels, troops"
   "turba, turbae" "disturbance, quarrel, troop"

   "turbantur" "they are disturbed, confused"
   "turbātus" "disturbed, confused"
   "turbō, turbāre, turbāvī, turbātus" "disturbed, confused"
   
   "turbine" "whirlwind, revolution"
   "turben, turbinis" "whirlwind, revolution"

   "turbida" "turbid, troubled, muddy"
   "turbidō" "turbid, troubled, muddy"
   "turbidus" "turbid, troubled, muddy"
   "turbidus, turbida, turbidum" "turbid, troubled, muddy"
   
   "turma" "troop, group, crowd"
   "turmae" "troop, group, crowd"
   "turmam" "troop, group, crowd"
   "turmās" "troop, group, crowd"
   "turma, turmae" "troop, group, crowd"

   "turpī" "ugly, filthy"
   "turpius" "uglier"
   "turpissima" "ugly, nasty, repulsive, shameful"
   "turpiter" "ugly, unsightly"
   "turpis, turpe, turpior -or -us, turpissimus -a -um" "ugly, nasty, repulsive, shameful"

   "turpitūdō"    "ugliness, foulness"
   "turpitūdinis" "ugliness, foulness"
   "turpitūdine"  "ugliness, foulness"
   "turpitūdō, turpitūdinis" "ugliness, foulness"

   "turrēs" "towers"
   "turrī" "tower"
   "turribus" "towers"
   "turrim" "tower"
   "turris" "tower"
   "turris, turris" "tower"

   "tūtam" "safety"
   "tūtum" "safety"
   "tūtum, tūtī" "safety"

   "tūtē" "safely"
   "tūtī" "safe"
   "tūtior" "safer"
   "tūtiōrēs" "safer"
   "tūtissima" "very safe"
   "tūtus, tūta -um, tūtior -or -us, tūtissimus -a -um" "safe"
   
   "tuum" "your"
   "tuus" "your"

   "tyrannide" "tyranny"
   "tyrannis, tyrannidis" "tyranny"

   "tyrannī" "tyrants"
   "tyrannō" "tyrant"
   "tyrannum" "tyrant"
   "tyrannus" "tyrant"
   "tyrannus, tyrannī" "tyrant"
   })
