(ns whitakers-clj.dict-m)

(def dict-m
  {"māchina" "military machine"
   "māchinās" "military machines"
   "māchina, māchinae" "military machine"

   "maerēbat" "he was mourning"
   "maerens" "mourning"
   "maereō, maerēre, -, -" "to mourn"
   "maereō, maerēre, maeruī" "to mourn"

   "maeror" "mourning, lamentation"
   "maerōre" "mourning, lamentation"
   "maeror, maerōris" "mourning, lamentation"

   "maesta" "sad, mournful"
   "maestissima" "very sad, mournful"
   "maestissimus" "very sad, mournful"
   "maestus, maesta -um, maestior -or -us, maestissimus -a -um" "sad, mournful"

   "magus" "magician"
   "magī" "magician"
   "magum" "magician"
   "magōrum" "of magicians"
   "magōs" "magicians"
   "magus, magī" "magician"

   "magister" "teacher"
   "magistrī" "teacher"
   "magistrō" "teacher"
   "magistrum" "teacher"
   "magister, magistrī" "teacher"

   "magistrātus" "magistrate, official"
   "magistrātus, magistrātūs" "magistrate, official"
   
   "magna" "large"
   "magnae" "large"
   "magnam" "large"
   "magnās" "large"
   "magnī" "large"
   "magnīs" "large"
   "magnō" "large"
   "magnum" "large"
   "magnus" "large"
   "maximus" "largest"
   "maximō" "largest"
   
   "magnālia" "mighty works, mighty deeds"
   "magnāle, magnālis" "mighty work, mighty deed"
   
   "magnificāns" "esteeming greatly"
   "magnificantēs" "esteeming greatly"
   "magnificābant" "they were esteeming greatly"
   "magnificāvimus" "we esteemed greatly"
   "magnificō, magnificāre, magnificāvī, magnificātus" "to esteem greatly"

   "māgnificus" "magnificent"
   "māgnificus, māgnifica -um, māgnificentior -or -us, māgnificentissimus -a -u" "magnificent"
   
   "maior" "bigger"
   "maiōre" "bigger"
   "maiōrem" "bigger"
   "maiōrēs" "bigger"
   "maiōribus" "bigger"
   "maiōrum" "of the biggest"

   "magnitūdine" "magnitude, greatness"
   "magnitudinem" "magnitude, greatness"
   "magnitūdinis" "magnitude, greatness"
   "magnitūdō, magnitūdinis" "magnitude, greatness"

   "maxima" "biggest"
   "maximam" "biggest"
   "maximās" "biggest"
   "maximī" "biggest"
   "maximīs" "biggest"
   "maximōs" "biggest"
   "maximum" "biggest"
   "magnus, magna -um, major -or -us, maximus -a -um" "large"
   
   "māiestās, māiestātis" "majesty"
   "māiestātem" "majesty"

   "maiī" "of May"
   "Maiī" "of May"
   "Maius, Maia, Maium" "May"
   
   "maledīcitis" "you curse"
   "maledictus" "cursing"
   "maledīcō, maledīcere, maledīxī, maledictus" "to curse"
   "maledictiō" "curse"
   "maledictiō, maledictiōnis" "curse"
   "maledictum" "insult"
   "maledictum, maledictī" "insult"

   "maleficiō" "crime, misdeed"
   "maleficium, maleficiī" "crime, misdeed"

   "malīgnus" "wicked, malignant"
   "malīgnus, malīgna, malīgnum" "wicked, malignant"

   "malitiae" "malice"
   "malitia, malitiae" "malice"

   "māluērunt" "they preferred"
   "mālō, mālle, māluī, -" "to prefer"
   
   "malleōrum" "of hammers"
   "malleus, malleī" "hammer"

   "malās" "evil"
   "male" "in an evil manner (adverb)"
   "malōs" "evil"
   "malus, mala -um, pejor -or -us, -" "evil"

   "mālōrum" "of apples"
   "mālum" "apple"
   "mālum, mālī" "apple"

   "malvam" "mallow plant"
   "malva, malvae" "mallow plant"

   "mamilla"  "breast"
   "mamillae" "breast"
   "mamillās" "breasts"
   "mamilla, mamillae" "breast"

   "mandābat" "he was entrusting"
   "mandābit" "he will entrust"
   "mandāta" "having been entrusted"
   "mandāverat" "he had entrusted"
   "mandāvērunt" "they entrusted"
   "mandāvit" "he commanded"
   "mandārent" "they might entrusted"
   "mandāre" "to entrust"
   "mandō, mandāre, mandāvī, mandātus" "to entrust"

   "mandūcābant" "they were chewing, eating"
   "mandūcant" "they eat"
   "mandūcārēmus" "we were chewing"
   "mandūcāvī" "I chewed, I ate"
   "mandūcāre" "to chew, to eat"
   "mandūcō, mandūcāre, mandūcāvī, mandūcātus" "to chew, to eat"
   
   "manendī" "remaining"
   "manendum" "remaining"
   "manēbam" "I was remaining"
   "manēbat" "he was remaining"
   "manēbant" "they were remaining"
   "manēbit" "he will remain"
   "manēbitis" "you will remain"
   "mānserint" "they will have remained"
   "mānsērunt" "they have remained"
   "mānsit" "he remained"
   "manēbō" "I will remain"
   "manēre" "to remain"
   "maneō, manēre, mānsī, mānsus" "to remain"
   "manet" "he remains"
   "maneat" "he remains"
   "maneant" "they remain"
   "manēbunt" "they will remain"
   "manentem" "remaining"
   "manentēs" "remaining"
   "manēret" "it remained"
   "mānsisse" "to have remained"
   "mānsimus" "we remained"

   "manifēsta" "having been revealed"
   "manifestāvit" "he revealed"
   "manifestō, manifestāre, manifestāvī, manifestātus" "to reveal"
   
   "mānāre" "to flow, to spring"
   "mānō, mānāre, mānāvī, mānātus" "to flow, to pour, to spring"
   "mānantis" "flowing, pouring"
   "mānāvit" "it flowed"
   
   "mānsiō, mānsiōnis" "room"
   "mānsiōnibus" "rooms"
   "mansuētūdine" "tameness"
   "mansuētūdō, mansuētūdinis" "tameness"
   "manibus" "hands"
   "manū" "hand"
   "manum" "hand"
   "manūs" "hand"
   "manuum" "of hands"
   "manus, manūs" "hand"

   "marca" "mark, a weight of coin that in the 11th century was about 8 ounces"
   "marcās" "marks, a weight of coin that in the 11th century was about 8 ounces"
   "marca, marcae" "mark, a weight of coin that in the 11th century was about 8 ounces"
   
   "mare" "sea"
   "maria" "seas"
   "maribus" "seas"
   "maris" "sea"
   "marium" "of the seas"
   "mare, maris" "sea"
   "marī" "sea"

   "margarīta" "pearl"
   "margarītae" "pearl"
   "margarītās" "pearls"
   "margarītārum" "of pearls"
   "margarītīs" "pearls"
   "margarīta, margarītae" "pearl"

   "marīae" "of Mary"
   "Marīae" "of Mary"
   "marīa, marīae" "Mary"
   "Marīa, Marīae" "Mary"

   "maritimam" "maritime"
   "maritimōs" "maritime"
   "maritimus, maritima, maritimum" "maritime"
   
   "marmor" "marble"
   "marmor, marmoris" "marble"

   "martyriī"  "of martyrdom"
   "martyrium" "martyrdom"
   "martyrium, martyriī" "martyrdom"
   
   "masculus" "male"
   "masculum" "male"
   "masculus, masculī" "male"
   
   "māssa" "mass, bulk"
   "māssam" "mass, bulk"
   "māssās" "mass, bulk"
   "māssa, māssae" "mass, bulk"
   
   "māter" "mother"
   "mātre" "mother"
   "mātrem" "mother"
   "mātris" "mother"
   "māter, mātris" "mother"

   "māteria" "matter"
   "māteria, māteriae" "matter"

   "māteriēs" "material, substance"
   "māteriēs, māteriēī" "material, substance"

   "māterna" "motherly"
   "māternīs" "motherly"
   "māternus, māterna, māternum" "motherly"

   "mātrimōnium" "marriage"
   "mātrimōniō" "marriage"
   "mātrimōnium, mātrimōniī" "marriage"

   "mātrōna" "matron, married woman"
   "mātrōna, mātrōnae" "matron, married woman"

   "mātūrat" "he hastens, he ripens"
   "mātūrō, mātūrāre, mātūrāvī, mātūrātus" "to hasten, to ripen"
   
   "mātūra" "mature, early"
   "mātūrus, mātūra, mātūrum" "mature, early"
   
   "mātūtīnum, mātūtīnī" "morning"
   "mātūtīnās" "mornings"
   "mātūtīnīs" "mornings"

   "mea" "my"
   "meae" "my"
   "meam" "my"
   "meārum" "our"
   "meī" "my"
   "meīs" "our"

   "medērī" "to heal"

   "mediaevālis" "medieval"
   "mediaevālī" "medieval"
   "mediaevālis, mediaevālis, mediaevāle" "medieval"

   "mediante" "mediating"
   "medior, mediārī, mediātus" "mediating"

   "medice" "doctor"
   "medicī"  "doctor's"
   "medicō" "doctor"
   "medicōs" "doctors"
   "medicum" "doctor"
   "medicus" "doctor"
   "medicus, medicī" "doctor"
   
   "medietās" "center, midpoint"
   "medietās, medietātis" "center, midpoint"

   "mediā" "middle"
   "mediae" "middle"
   "mediam" "middle"
   "medius" "middle"
   "medius, media, medium" "middle"
   
   "mediō" "middle"
   "medium" "middle"
   "medium, mediī" "middle"

   "melle" "honey"
   "mellis" "honey"
   "mel, mellis" "honey"
   
   "membra" "limb, member"
   "membrum, membrī" "limb, member"
   "membrum" "limb, member"
   "membrīs" "limbs, members"

   "memorātī" "having been remembered"
   "memorātis" "you remember"
   "memorātum" "having been remembered"
   "memorō, memorāre, memorāvī, memorātus" "to remember"

   "memoria" "memory, historical account"
   "memoria, memoriae" "memory, historical account"

   "mente" "mind"
   "mentēs" "minds"
   "mentī" "to the mind"
   "mēns, mentis" "mind"
   
   "mēnsa" "table"
   "mēnsam" "table"
   "mēnsa, mēnsae" "table"
   "mēnsem" "month"
   "mēnsēs" "months"
   "mēnsibus" "months"
   "mēnsis" "month"
   "mēnsis, mēnsis" "month"
   "mēnsum" "of months"
   "mēnse" "month"
   
   "mēnsūra" "measure"
   "mēnsūram" "measure"
   "mēnsūra, mēnsūrae" "measure"
   "mēnsūrābat" "he was measuring"
   "mēnsūrandum" "measuring"
   "mēnsūrō, mēnsūrāre, mēnsūrāvī, mēnsūrātus" "to measure"

   "meās" "my"
   "meum" "my"
   "meus" "my"
   "mihī" "to me"

   "mercātor" "merchant"
   "mercātōrēs" "merchants"
   "mercātōrum" "of merchants"
   "mercātor, mercātōris" "merchant"

   "mercātum" "trade, market, fair"
   "mercātus" "trade, market, fair"
   "mercātus, mercātūs" "trade, market, fair"

   "mercenāriī" "hired servant, working man"
   "mercenārius, mercenāriī" "hired servant, working man"

   "mergit" "he plunges, sinks, drowns"
   "mersī" "having been plunged, sunk, drowned"
   "merge" "plunge!"
   "mergō, mergere, mersī, mersus" "to plunge, sink, drown"
   
   "merīdiem" "mid-day"
   "merīdiēs, merīdiēī" "mid-day"
   "merīdiānam" "noon, southern"
   "merīdiānum" "noon, southern"
   "merīdiānus" "noon, southern"

   "meritīs" "having been earned"
   "meruī" "I merited"
   "meruistī" "you earned"
   "mereō, merēre, meruī, meritus" "to earn, to deserve"
   "meritī" "merited"
   "meritō" "merited"
   "merērentur" "they merited"

   "merulās" "crenellations (battlements of a castle wall), blackbird"
   "merula, merulae" "crenellations (battlements of a castle wall), blackbird"
   
   "metallī" "metal"
   "metallum, metallī" "metal"

   "mētātī" "having been measured off"
   "mētō, mētāre, mētāvī, mētātus" "to measure off, mark out"

   "metendō" "reaping, cutting off"
   "metere" "to reap, to cut off"
   "metō, metere, messuī, messus" "to reap, to cut off"

   "mētiēris" "you will measure"
   "mētior, mētīrī, mēnsus, -" "to measure"

   "metū" "fear"
   "metus" "fear"
   "metus, metūs" "fear"

   "metuenda" "fearing"
   "metuit" "he feared"
   "metuere" "to fear"
   "metuō, metuere, metuī, metūtus" "to fear"
   
   "migrāvī" "I departed"
   "migrāvit" "he departed"
   "migrō, migrāre, migrāvī, migrātus" "to depart"
   
   "mīliāria" "milestones"
   "mīliāriī" "milestone"
   "mīliārium, mīliāriī" "milestone"

   "mīlitāris" "military"
   "mīlitāris, mīlitāris, mīlitāre" "military"
   
   "mīles" "soldier"
   "mīlite" "soldier"
   "mīlitem" "soldier"
   "mīlitēs" "soldiers"
   "mīlitī" "soldier"
   "mīlitis" "of a soldier"
   "mīlitibus" "soldiers"
   "mīlitum" "of soldiers"
   "mīles, mīlitis" "soldier"

   "mīlitia"  "military"
   "mīlitiae" "military"
   "mīlitiam" "military"
   "mīlitia, mīlitiae" "military"

   "mīlitābant" "they were fighting"
   "mīlitāre" "to fight"
   "mīlitō, mīlitāre, mīlitāvī, mīlitātus" "to fight"
   
   "milium" "millet"
   "milium, miliī" "millet"

   "mīllia" "miles"
   "mīlibus" "miles"
   "mīlle, mīlle" "mile"

   "minīs" "ambushes"
   "mina, minae" "ambush"

   "minābat" "he was pushing"
   "minō, mināre, mināvī, minātus" "to push, to impel"
   "minimae" "very small"

   "mingēbant" "they were making water"
   "mingō, mingere, mīnxī, mīnctus" "to make water"
   
   "ministrī" "ministers"
   "ministrīs" "ministers"
   "minister" "servant, waiter"
   "minister, ministrī" "servant, waiter"
   
   "ministerium" "ministry"
   "ministerium, ministeriī" "ministry"
   "ministrābat" "he was serving, he was attending"
   "ministrābant" "they were serving, they were attending"
   "ministrāre" "to serve, to attend to"
   "ministrantur" "being ministered to"
   "ministrātur" "he is being served"
   "ministrō" "I serve, I attend to"
   "ministrō, ministrāre, ministrāvī, ministrātus" "to serve, to attend to"
   
   "minor" "smaller"
   "minōrēs" "smaller"
   "parva" "small"
   "parvissimum" "smallest"
   "parvus" "small"
   "parvus, parva -um, minor -or -us, minimus -a -um" "small"

   "minuī" "I diminished"
   "minuitur" "to be diminished"
   "minūta" "having been diminished"
   "minuere" "to diminish"
   "minuō, minuere, minuī, minūtus" "to diminish"
   
   "mīrae" "wonderful, marvelous"
   "mīrī" "wonderful, marvelous"
   "mīrus, mīra, mīrum" "wonderful, marvelous"

   "mīrābile" "marvelous, wonderful"
   "mīrābilem" "marvelous, wonderful"
   "mīrābilia" "marvelous, wonderful"
   "mīrābilis" "marvelous, wonderful"
   "mīrābilior" "more marvelous"
   "mīrābilissimum" "most marvelous"
   "mīrābilis, mīrābilis, mīrābile" "marvelous, wonderful"

   "mīrābilibus" "miracles"
   "mīrābilia, mīrābilium" "miracles"
   
   "mīrāculum" "miracle"
   "mīrācula" "miracles"
   "mīrāculīs" "miracles"
   "mīrāculum, mīrāculī" "miracle"

   "mīrificus" "amazing, wonderful"
   "mīrificus, mīrifica, mīrificum" "amazing, wonderful"
   
   "miser" "miserable"
   "miserī" "miserable"
   "miser, misera -um, miserior -or -us, miserrimus -a -um" "miserable"
   "misera" "miserable"
   "miseriam" "miserable"
   "miserrima" "very miserable"

   "miseria"  "misfortune, suffering"
   "miseriae" "misfortune, suffering"
   "miseriās" "misfortunes, suffering"
   "miseria, miseriae" "misfortune, suffering"
   
   "misereātur" "he (might) pity"
   "miserēre" "to pity, to have compassion"
   "misereō, miserēre, miseruī, miseritus" "to pity, to have compassion"

   "miscētur" "it is mixed"
   "miscēre" "to mix, mingle"
   "misceō, miscēre, miscuī, mixtus" "to mix, mingle"

   "misericordia" "pity, compassion, mercy"
   "misericordiae" "pity, compassion, mercy"
   "misericordia, misericordiae" "pity, compassion, mercy"
   "misericordiam" "pity, compassion, mercy"

   "misericors" "merciful"
   "misericors, (gen.), misericordis" "merciful"
   
   "mīsērunt" "they sent"
   "mīsit" "he sent"
   
   "missa" "Mass"
   "missa, missae" "Mass"
   "missās" "Masses"
   "missam" "Mass"
   "missārum" "of Masses"

   "missile" "missile, javelin"
   "missilibus" "missiles, javelins"
   "missilis" "missile, javelin"
   "missile, missilis" "missile, javelin"
   
   "mīsissent" "they (might) have had sent"
   "mittite" "send! put!"
   "mīsī" "I threw, I cast"
   "mīssisset" "he (might) have had thrown"
   "missī" "having been sent"
   "missōs" "having been sent"

   "missū"  "throwing, dispatch"
   "missus" "throwing, dispatch"
   "missum" "throwing, dispatch"
   "missus, missūs" "throwing, dispatch"

   "missīs" "having been sent"
   "mīsisset" "he might have sent"
   "mittēbat" "he was sending"
   "mittēbant" "they were sending"
   "mittēbantur" "they were being sent"
   "mittēmus" "we will send"
   "mittitur" "he is being sent"
   "mittō" "I send"
   "mittunt" "they send"
   "mittuntur" "they are being sent"
   "mittente" "sending"
   "mittentem" "sending"
   "mitteret" "he was sending"
   "mitterent" "they might have been sending"
   "mīserant" "they had sent"
   "mittam" "I might send"
   "mittī" "to be sent"
   "mittere" "to send"
   "mittō, mittere, mīsī, missus" "to send"

   "mītem" "soft, mild, gentle"
   "mītī" "soft, mild, gentle"
   "mītis, mīte, mītior -or -us, mītissimus -a -um" "soft, mild, gentle"
   
   "mōbilitās" "mobility"
   "mōbilitātem" "mobility"
   "mōbilitātis" "mobility"
   "mōbilitās, mōbilitātis" "mobility"

   "modium" "peck (8 dry quarts)"
   "modius, modiī" "peck (8 dry quarts)"
   
   "modō" "mode, manner, way, measure, size"
   
   "modulātiō, modulātiōnis" "melody, modulation"
   "modulātiō" "melody, modulation"
   "modulātiōne" "melody, modulation"

   "modīs" "ways"
   "modum" "mode, manner, way, measure, size"
   "modus" "mode, manner, way, measure, size"
   "modus, modī" "mode, manner, way, measure, size"

   "mōle" "weight"
   "mōles, mōlis" "weight"

   "mōlīmen" "exertion, effort, endeavour"
   "mōlīmina" "exertion, effort, endeavour"
   "mōlīminis" "exertion, effort, endeavour"
   "mōlīmen, mōlīminis" "exertion, effort, endeavour"

   "mōlīrētur" "it (might) set in motion"
   "mōlior, mōlīrī, mōlītus" "to set in motion"

   "molliōris" "softer"
   "mollis, mollis, molle" "soft"
   
   "mollīrī" "to be softened, weakened"
   "molliō, mollīre, mollīvī, mollītus" "to soften, weaken"
   
   "monachī" "monk"
   "monachīs" "monks"
   "monachus" "monk"
   "monachum" "monk"
   "monachōs" "monks"
   "monachōrum" "of monks"
   "monachus, monachī" "monk"

   "monarchia" "monarchy"
   "monarchiam" "monarchy"
   "monarchia, monarchiae" "monarchy"
   
   "monastēriī" "monastery"
   "monastēriō" "monastery"
   "monastērium" "monastery"
   "monastērium, monastēriī" "monastery"

   "monita" "warnings, having been warned"
   "monēns" "warning"
   "monente" "warning"
   "monet" "he warns"
   "monitus" "having been warned"
   "monuī" "I warned"
   "monēre" "to warn"
   "moneō, monēre, monuī, monitus" "to warn"

   "mōnstrat" "he points out"
   "mōnstrant" "they point out"
   "mōnstrāvit" "he pointed out"
   "mōnstrātur" "it is pointed out"
   "mōnstrō, mōnstrāre, mōnstrāvī, mōnstrātus" "to point out"

   "montānea"  "mountain"
   "montāneam" "mountain"
   "montāneās" "mountains"
   "montānea, montāneae" "mountain"

   "montanam" "mountainous"
   "montānās" "mountainous"
   "montānīs" "mountainous"
   "montāna"  "mountainous"
   "montānus, montāna, montānum" "mountainous"
   
   "mōns, montis" "mountain"
   "mōns" "mountain"
   "monte" "mountain"
   "montem" "mountain"
   "montēs" "mountains"
   "montibus" "mountains"
   "montium" "of mountains"
   "montīs" "mountains"

   "mōnstrum" "monster"
   "mōnstrum, mōnstrī" "monster"

   "monumentum" "monument, memorial, tomb"
   "monumentum, monumentī" "monument, memorial, tomb"

   "mora" "delay"
   "morās" "delays"
   "mora, morae" "delay"

   "mōrātus" "having stayed, delayed"
   "morāns" "staying, delaying"
   "morantur" "they stay, delay"
   "morārī" "to stay, delay"
   "moror, morārī, morātus sum" "to stay, delay"

   "mortuōrum" "of the dead"
   "moriēris" "you will die"
   "moritur" "he dies"
   "moriāmur" "we might die"
   "moriar" "I will die"
   "moriēmur" "we will die"
   "morientēs" "dying"
   "moritūrus" "dying (in the future)"
   "mortuum" "having died"
   "morior, morī, mortuus sum" "to die"
   
   "mors, mortis" "death"
   "morte" "death"
   "mortem" "death"
   "mortis" "death"
   
   "mōre" "manner, custom"
   "mōribus" "customs, morals"
   "mōs" "manner, custom"
   "mōs, mōris" "manner, custom"
   
   "morsum" "little piece"
   "morsum, morsī" "little piece"
   "morsus" "bite, sting"
   "morsus, morsūs" "bite, sting"

   "mordēbit" "he will bite"
   "mordet" "he bites"
   "mordēbunt" "they will bite"
   "mordēre" "to bite"
   "mordeō, mordēre, momordī, morsus" "to bite"

   "mortālem" "mortal"
   "mortālēs" "mortals"
   "mortālī"  "mortal"
   "mortālis, mortālis, mortāle" "mortal"

   "mortālitās" "mortality"
   "mortālitās, mortālitātis" "mortality"

   "mortua" "dead"
   "mortuae" "dead"
   "mortuī" "dead"
   "mortuīs" "dead"
   "mortuō" "dead"
   "mortuōs" "dead"
   "mortuus" "dead"
   "mortuus, mortua, mortuum" "dead"

   "mōtiō" "motion"
   "mōtiō, mōtiōnis" "motion"

   "mōtū"  "movement, tumult"
   "mōtus" "movement, tumult"
   "mōtūs" "movement, tumult"
   "mōtus, mōtūs" "movement, tumult"
   
   "movēbat" "he was moving"
   "movent" "they move"
   "movērētur" "they (might) have been moving"
   "movētur" "he was moved"
   "moventur" "they are moved"
   "mōta" "having been moved"
   "mōtō" "having been moved"
   "movēns" "moving"
   "movet" "it moves"
   "movēre" "to move"
   "moveō, movēre, mōvī, mōtus" "to move"

   "moyse" "Moses"
   "moysen" "Moses"
   "moyses" "Moses"
   "Moyses, Moysis" "Moses"

   "mūgīs" "you low, you bellow"
   "mūgiō, mūgīre, mūgīvī, mūgītus" "to low, to bellow"

   "mulier"   "woman"
   "mulierēs" "women"
   "mulieribus" "women"
   "mulieris" "woman"
   "mulier, mulieris" "woman"

   "mūlōs" "mules"
   "mūlus" "mule"
   "mūlus, mūlī" "mule"

   "multiplicāta" "having been multiplied"
   "multiplicātī" "having been multiplied"
   "multiplicātus" "having been multiplied"
   "multiplicō, multiplicāre, multiplicāvī, multiplicātus" "to multiply, to increase"

   "multitūdō" "multitude, great number"
   "multitūdine" "multitude, great number"
   "multitūdinem" "multitude, great number"
   "multitūdō, multitūdinis" "multitude, great number"
   
   "multa" "many"
   "multae" "many"
   "multam" "many"
   "multēs" "many"
   "multum" "many"
   "multārum" "many"
   "multās" "many"
   "multī"  "many"
   "multīs" "many"
   "multō" "many"
   "multōrum" "many"
   "multōs" "many"
   "plūra" "more"
   "plūrēs" "more"
   "plūribus" "more"
   "plūrima" "very many"
   "plūrimārum" "of very many"
   "plūrimās" "very many"
   "plūrimōs" "very many"
   "plūrimum" "very many"
   "plūrimī" "very many"
   "multus, multa -um, -, plūrimus -a -um" "many"

   "mundābat" "he was cleaning"
   "mundō, mundāre, mundāvī, mundātus" "to cleanse"
   
   "mundī" "world"
   "mundō" "world"
   "mundum" "world"
   "mundus" "world"
   "mundus, mundī" "world"

   "mūnīmen" "defence, fortification, rampart"
   "mūnīmine" "defence, fortification, rampart"
   "mūnīminis" "defence, fortification, rampart"
   "mūnīmen, mūnīminis" "defence, fortification, rampart"

   "mūniam" "I will fortify"
   "mūniant" "they might fortify"
   "mūnīret" "he might have fortified"
   "mūnīvit" "he fortified"
   "mūnīre" "to fortify"
   "mūniō, mūnīre, mūnīvī, mūnītus" "to fortify"

   "mūnīta"  "fortified"
   "mūnītam" "fortified"
   "mūnītī"  "fortified"
   "mūnītō"  "fortified"
   "mūnītum" "fortified"
   "mūnītus" "fortified"
   "mūnītus, mūnīta, mūnītum" "fortified"

   "mūnere" "gift"
   "mūnera" "gifts"
   "mūnus, mūneris" "gift"

   "mūrālēs" "walled"
   "mūrālis, mūrālis, mūrāle" "walled"

   "mūrō" "city wall"
   "mūrīs" "city walls"
   "mūrōs" "city walls"
   "mūrum" "city wall"
   "mūrus" "city wall"
   "mūrī" "of the city wall"
   "mūrus, mūrī" "city wall"
   
   "mustō" "must (new wine)"
   "mustum, mustī" "must (new wine)"

   "mūtāvit" "he changed"
   "mūtāre" "to change"
   "mūtō, mūtāre, mūtāvī, mūtātus" "to change"

   "mystēria" "mysteries"
   "mystērium" "mystery"
   "mystērium, mystēriī" "mystery"
   })
